; SPEEDmaza (2014) by Jakub Husak - disassembly of the unpacked program
; Generated by tools/disasm.py from the image made by tools/unpack.py.
; Assemble: mads speedmaza.asm -o:speedmaza.xex   (see build.sh)
; The program was written in Action!; speedmaza.act is the reconstructed
; Action! source for the code between DliTitle and Main.

; ---- hardware, OS, Action! runtime
BRKKEY          = $0011
RTCLOK          = $0014
ATRACT          = $004D
rt_ptr          = $0082
rt_arg          = $0084
rt_res          = $0086
arg0            = $00A0
arg1            = $00A1
arg2            = $00A2
arg3            = $00A3
arg4            = $00A4
arg5            = $00A5
tmp0            = $00AA
tmp1            = $00AC
tmp2            = $00AE
VDSLST          = $0200
SRTIMR          = $022B
SDMCTL          = $022F
SDLSTL          = $0230
GPRIOR          = $026F
STRIG0          = $0284
PCOLR0          = $02C0
COLOR0          = $02C4
CH              = $02FC
dli_colpf0      = $03E8	; colours the game DLI writes to the playfield
dli_colpf1      = $03E9
dli_colpf2      = $03EA
dli_colbk       = $03EB
TITLE_PIC       = $1000	; title picture / fonts (data/title_pic.bin)
DIRS            = $5BA7	; CARD ARRAY dirs of BuildMaze (outside the program image)
MAZE            = $5C00	; maze bitmap 128x128 bytes, ANTIC mode 8, built at run time
GAME_DL         = $9C00	; game display list and PM graphics (PMBASE=$9C), built at run time
ACT_DIV         = $A090	; CARD A:X / rt_arg -> A:X
ACT_MOD         = $A0DE	; CARD A:X MOD rt_arg -> A:X
ACT_RSH         = $A0E6	; A:X RSH rt_arg
ACT_PARAMS      = $A0F5	; copy arg0.. to PROC locals; followed by .word dest, .byte n-1
ACT_MOVEBLOCK   = $A7B3	; MoveBlock(dest=A:X, src=arg2/3, size=arg4/5)
ACT_LSH         = $B5C0	; A:X LSH rt_arg
HPOSP0          = $D000
HPOSM0          = $D004
SIZEM           = $D00C
COLPF0          = $D016
COLPF1          = $D017
COLPF2          = $D018
COLBK           = $D01A
GRACTL          = $D01D
HITCLR          = $D01E
RANDOM          = $D20A
PORTB           = $D301
HSCROL          = $D404
VSCROL          = $D405
PMBASE          = $D407
WSYNC           = $D40A
VCOUNT          = $D40B
NMIEN           = $D40E

; ---- INIT during load: OS ROM on, BASIC off, so $A000-$BFFF is RAM
	opt h+
	org $0600
load_init	lda #$FF
	sta PORTB
	rts
	ini load_init

; ======================================================================
; $0FFE-$1FFF  title bitmap, 'MAZA PASSED!' banner, digit font
; ======================================================================
	org $0FFE
	ins 'data/title_pic.bin'

; ======================================================================
; $2000-$283F  crash picture (44 lines x 48 bytes)
; ======================================================================
	org $2000
	ins 'data/crash_pic.bin'

; ======================================================================
; $2840-$4365  Action! program: globals, then PROCs
; ======================================================================
	org $2840
titlePic
	dta a(TITLE_PIC)
dlTitle_data
	dta $10,$50,$70,$70,$CE,$00,$00,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E
	dta $0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E
	dta $0E,$0E,$0E,$70,$70,$70,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$70,$30
	dta $0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$70,$30,$0E,$0E,$0E,$0E,$0E,$0E
	dta $0E,$0E,$70,$30,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$70,$30,$0E,$0E
	dta $0E,$0E,$0E,$0E,$0E,$0E,$70,$70,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E
	dta $70,$10,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$41,$00,$00
dlTitle
	dta a(dlTitle_data)
dlCrash_data
	dta $70,$70,$70,$70,$70,$70,$70,$70,$70,$70,$7E,$00,$00,$3E,$3E,$3E
	dta $3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E
	dta $3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E
	dta $3E,$3E,$3E,$3E,$3E,$3E,$3E,$3E,$41,$00,$00
dlCrash
	dta a(dlCrash_data)
dlWin_data
	dta $70,$70,$70,$70,$70,$70,$70,$70,$70,$70,$70,$F0,$4E,$00,$00,$0E
	dta $0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$0E,$41,$00,$00
dlWin
	dta a(dlWin_data)
barTxt1_data
	dta $70,$88,$88,$88,$E8,$00,$88,$A8,$A8,$A8,$F8,$00,$88,$A8,$A8,$A8
	dta $F8,$00,$60,$90,$90,$90,$F8,$00,$90,$A8,$A8,$A8,$48
barTxt1
	dta a(barTxt1_data)
barTxt2_data
	dta $88,$A8,$A8,$A8,$F8,$00,$88,$88,$88,$70,$00,$F8,$10,$20,$40,$F8
	dta $00,$78,$A0,$A0,$A0,$78,$00,$80,$80,$F8,$80,$80,$00,$90,$A8,$A8
	dta $A8,$48,$00,$F8,$00,$70,$88,$88,$88,$E8,$00
barTxt2
	dta a(barTxt2_data)
hposp
	dta a(HPOSP0)
m0pf
	dta a(HPOSP0)
hposm
	dta a(HPOSM0)
p0pf
	dta a(HPOSM0)
color
	dta a(COLOR0)
pcolr
	dta a(PCOLR0)
strig
	dta a(STRIG0)
cx
	dta $00,$00
cy
	dta $00,$00
scrX
	dta $00,$00
scrY
	dta $00,$00
rowPhase
	dta $00,$00
rowAdr
	dta $00,$00
score
	dta $00,$00
best
	dta $00,$00
pathLen
	dta $00,$00
path_data
	dta $01,$04,$02,$02,$02,$02,$02,$02,$02,$02,$02,$04,$04,$04,$04,$01
	dta $01,$01,$04,$04,$04,$04,$02,$04,$04,$04,$04,$02,$03,$03,$02,$02
	dta $02,$02,$04,$04,$04,$04,$04,$04,$02,$02,$03,$02,$02,$02,$02,$02
	dta $02,$02,$02,$04,$01,$01,$04,$04,$01,$01,$04,$04,$02,$02,$02,$03
	dta $03,$03,$02,$02,$02,$02,$03,$03,$03,$01,$04,$04,$01,$03,$03,$03
	dta $02,$02,$02,$04,$04,$02,$02,$02,$02,$02,$02,$03,$02,$02,$02,$02
	dta $02,$02,$03,$02,$02,$02,$02,$02,$03,$01,$01,$01,$03,$03,$03,$03
	dta $01,$01,$01,$01,$01,$01,$04,$04,$01,$01,$01,$01,$01,$01,$01,$01
	dta $01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$01,$03,$03,$03
	dta $03,$03,$03,$03,$02,$02,$02,$02,$02,$03,$03,$03,$03,$02,$02,$04
	dta $04,$02,$02,$02,$02,$02,$02,$03,$03,$01,$03,$03,$03,$03,$03,$03
	dta $03,$01,$04,$01,$04,$04,$04,$01,$01,$04,$02,$04,$04,$01,$03,$01
	dta $01,$01,$01,$03,$03,$03,$03,$03,$03,$01,$01,$04,$04,$02,$04,$04
	dta $04,$04,$04,$02,$04,$04,$04,$01,$03,$03,$01,$04,$04,$01,$01,$01
	dta $01,$01,$03,$03,$02,$02,$02,$02,$03,$02,$03,$03,$03,$03,$01,$04
	dta $01,$01,$01,$01,$04,$01,$01,$01,$01,$01,$01,$01,$03,$01,$04,$04
	dta $04,$02,$02,$02,$02,$02,$03,$01,$01,$01,$01,$00
path
	dta a(path_data)
shapes_data
	dta $00,$04,$0E,$1F,$0E,$04,$00,$00,$00,$00,$0E,$0E,$0E,$00,$00,$00
	dta $00,$11,$0E,$0A,$0E,$11,$00,$00,$00,$00,$0E,$0A,$0E,$00,$00,$00
shapes
	dta a(shapes_data)
gi
	dta $00
gk
	dta $00,$00
g_unused1
	dta $00,$00
gp
	dta $00,$00
gq
	dta $00,$00
gr
	dta $00,$00
gofs
	dta $00,$00
dliCycle
	dta $0C
dliLine
	dta $00
g_unused2
	dta $00,$00,$00
dliCol
	dta $00
g_unused3
	dta $00,$00,$00,$00,$00,$00,$00

; ----------------------------------------------------------------------
; INTERRUPT: title screen DLI - rolling COLPF2 stripes, COLBK bands
; ----------------------------------------------------------------------
DliTitle
	jmp L2AC6
L2AC6
	pha
	tya
	pha
	lda VCOUNT
	cmp #$1C
	bcc L2AD3
	jmp L2B5E
L2AD3
	lda #$10
	sta dliLine
	ldy #$00
	sty ATRACT
	lda dliCycle
	sta dliCol
	clc
	lda dliCycle
	adc #$10
	sta dliCycle
L2AEB
	lda dliLine
	cmp #$80
	bcc L2AF5
	jmp L2B59
L2AF5
	inc dliCol
	lda dliCol
	and #$F0
	sta tmp2
	lda tmp2
	ora #$0C
	sta COLPF2
	lda dliLine
	cmp #$1E
	bcc L2B10
	jmp L2B1D
L2B10
	lda #$10
	sta COLBK
	ldy #$00
	sty WSYNC
	jmp L2B53
L2B1D
	lda dliLine
	cmp #$2F
	bcc L2B27
	jmp L2B32
L2B27
	ldy #$00
	sty WSYNC
	sty COLBK
	jmp L2B53
L2B32
	lda dliLine
	cmp #$70
	bcc L2B3C
	jmp L2B49
L2B3C
	ldy #$00
	sty WSYNC
	lda #$80
	sta COLBK
	jmp L2B53
L2B49
	ldy #$00
	sty WSYNC
	lda #$B0
	sta COLBK
L2B53
	inc dliLine
	jmp L2AEB
L2B59
	ldy #$00
	sty COLBK
L2B5E
	pla
	tay
	pla
	rti

; ----------------------------------------------------------------------
; INTERRUPT: game DLI - status bar colour bars, then maze colours
; ----------------------------------------------------------------------
DliGame
	jmp L2B65
L2B65
	pha
	tya
	pha
	lda VCOUNT
	cmp #$10
	bcc L2B72
	jmp L2C0F
L2B72
	ldy #$00
	sty dliLine
	sty ATRACT
	lda #$64
	sta dliCol
	clc
	lda dliCycle
	adc #$10
	sta dliCycle
L2B87
	lda dliLine
	cmp #$05
	bcc L2B91
	jmp L2BAE
L2B91
	clc
	lda dliCol
	adc #$02
	sta dliCol
	ldy #$00
	sty WSYNC
	sty WSYNC
	lda dliCol
	sta COLPF2
	inc dliLine
	jmp L2B87
L2BAE
	inc dliLine
	ldy #$00
	sty WSYNC
	sty WSYNC
	sty WSYNC
	sty WSYNC
	sty WSYNC
L2BC2
	lda #$00
	cmp dliLine
	bcc L2BCC
	jmp L2BEF
L2BCC
	sec
	lda dliCol
	sbc #$02
	sta dliCol
	ldy #$00
	sty WSYNC
	sty WSYNC
	lda dliCol
	sta COLPF2
	sec
	lda dliLine
	sbc #$01
	sta dliLine
	jmp L2BC2
L2BEF
	ldy #$00
	sty WSYNC
	lda dli_colpf1
	sta COLPF1
	lda dli_colpf2
	sta COLPF2
	lda dli_colpf0
	sta COLPF0
	sty WSYNC
	lda dli_colbk
	sta COLBK
L2C0F
	pla
	tay
	pla
	rti

; ----------------------------------------------------------------------
; INTERRUPT: 'maza passed' screen DLI - rolling COLPF2
; ----------------------------------------------------------------------
DliWin
	jmp L2C16
L2C16
	pha
	tya
	pha
	ldy #$00
	sty dliLine
	sty ATRACT
	lda dliCycle
	sta dliCol
	clc
	lda dliCycle
	adc #$10
	sta dliCycle
L2C2F
	lda dliLine
	cmp #$0C
	bcc L2C39
	jmp L2C55
L2C39
	inc dliCol
	lda dliCol
	and #$F0
	sta tmp2
	lda tmp2
	ora #$0C
	sta COLPF2
	ldy #$00
	sty WSYNC
	inc dliLine
	jmp L2C2F
L2C55
	pla
	tay
	pla
	rti
Wait_n
	dta $00

; ----------------------------------------------------------------------
; PROC Wait(BYTE n) - wait n frames (RTCLOK)
; ----------------------------------------------------------------------
Wait
	jmp L2C5D
L2C5D
	sta Wait_n
	clc
	lda Wait_n
	adc RTCLOK
	sta Wait_n
L2C69
	lda Wait_n
	eor RTCLOK
	beq L2C73
	jmp L2C69
L2C73
	rts
WaitLine_l
	dta $00

; ----------------------------------------------------------------------
; PROC WaitLine(BYTE l) - wait until VCOUNT>l (never called)
; ----------------------------------------------------------------------
WaitLine
	jmp L2C78
L2C78
	sta WaitLine_l
L2C7B
	lda WaitLine_l
	cmp VCOUNT
	bcc L2C86
	jmp L2C7B
L2C86
	rts
CarveH_o
	dta $00

; ----------------------------------------------------------------------
; PROC CarveH(BYTE o) - clear 2 words of maze at (cx+o,cy)
; ----------------------------------------------------------------------
CarveH
	jmp L2C8B
L2C8B
	sta CarveH_o
	lda #$06
	sta rt_arg
	lda cy+1
	tax
	lda cy
	jsr ACT_LSH	; A:X LSH rt_arg
	sta tmp2
	txa
	sta tmp2+1
	clc
	lda cx
	adc tmp2
	sta tmp1
	lda cx+1
	adc tmp2+1
	sta tmp1+1
	clc
	lda tmp1
	adc CarveH_o
	sta tmp2
	lda tmp1+1
	adc #$00
	sta tmp2+1
	lda #$01
	sta rt_arg
	lda tmp2+1
	tax
	lda tmp2
	jsr ACT_LSH	; A:X LSH rt_arg
	sta tmp1
	txa
	sta tmp1+1
	clc
	lda #$00
	adc tmp1
	sta gq
	lda #$5C
	adc tmp1+1
	sta gq+1
	lda gq
	sta tmp2
	lda gq+1
	sta tmp2+1
	lda #$00
	ldy #$01
	sta (tmp2),y
	lda #$00
	dey
	sta (tmp2),y
	clc
	lda gq
	adc #$02
	sta gq
	lda gq+1
	adc #$00
	sta gq+1
	lda gq
	sta tmp2
	lda gq+1
	sta tmp2+1
	lda #$00
	iny
	sta (tmp2),y
	lda #$00
	dey
	sta (tmp2),y
	rts

; ----------------------------------------------------------------------
; PROC CarveLeft() - cx==-2, carve
; ----------------------------------------------------------------------
CarveLeft
	jmp L2D1C
L2D1C
	sec
	lda cx
	sbc #$02
	sta cx
	lda cx+1
	sbc #$00
	sta cx+1
	lda #$00
	jsr CarveH
	rts

; ----------------------------------------------------------------------
; PROC CarveRight() - carve, cx==+2
; ----------------------------------------------------------------------
CarveRight
	jmp L2D36
L2D36
	lda #$01
	jsr CarveH
	clc
	lda cx
	adc #$02
	sta cx
	lda cx+1
	adc #$00
	sta cx+1
	rts
CarveV_o
	dta $00

; ----------------------------------------------------------------------
; PROC CarveV(BYTE o) - clear 2 rows of maze at (cx,cy+o)
; ----------------------------------------------------------------------
CarveV
	jmp L2D51
L2D51
	sta CarveV_o
	clc
	lda cy
	adc CarveV_o
	sta tmp2
	lda cy+1
	adc #$00
	sta tmp2+1
	lda #$06
	sta rt_arg
	lda tmp2+1
	tax
	lda tmp2
	jsr ACT_LSH	; A:X LSH rt_arg
	sta tmp1
	txa
	sta tmp1+1
	clc
	lda cx
	adc tmp1
	sta tmp2
	lda cx+1
	adc tmp1+1
	sta tmp2+1
	lda #$01
	sta rt_arg
	lda tmp2+1
	tax
	lda tmp2
	jsr ACT_LSH	; A:X LSH rt_arg
	sta tmp1
	txa
	sta tmp1+1
	clc
	lda #$00
	adc tmp1
	sta gq
	lda #$5C
	adc tmp1+1
	sta gq+1
	lda gq
	sta tmp2
	lda gq+1
	sta tmp2+1
	lda #$00
	ldy #$01
	sta (tmp2),y
	lda #$00
	dey
	sta (tmp2),y
	clc
	lda gq
	adc #$80
	sta gq
	lda gq+1
	adc #$00
	sta gq+1
	lda gq
	sta tmp2
	lda gq+1
	sta tmp2+1
	lda #$00
	iny
	sta (tmp2),y
	lda #$00
	dey
	sta (tmp2),y
	rts

; ----------------------------------------------------------------------
; PROC CarveUp() - cy==-2, carve
; ----------------------------------------------------------------------
CarveUp
	jmp L2DE2
L2DE2
	sec
	lda cy
	sbc #$02
	sta cy
	lda cy+1
	sbc #$00
	sta cy+1
	lda #$00
	jsr CarveV
	rts

; ----------------------------------------------------------------------
; PROC CarveDown() - carve, cy==+2
; ----------------------------------------------------------------------
CarveDown
	jmp L2DFC
L2DFC
	lda #$01
	jsr CarveV
	clc
	lda cy
	adc #$02
	sta cy
	lda cy+1
	adc #$00
	sta cy+1
	rts

; ----------------------------------------------------------------------
; PROC MarkCell() - put $5555 (colour 1 = start/exit) at (cx,cy)
; ----------------------------------------------------------------------
MarkCell
	jmp L2E16
L2E16
	lda #$06
	sta rt_arg
	lda cy+1
	tax
	lda cy
	jsr ACT_LSH	; A:X LSH rt_arg
	sta tmp2
	txa
	sta tmp2+1
	clc
	lda cx
	adc tmp2
	sta tmp1
	lda cx+1
	adc tmp2+1
	sta tmp1+1
	lda #$01
	sta rt_arg
	lda tmp1+1
	tax
	lda tmp1
	jsr ACT_LSH	; A:X LSH rt_arg
	sta tmp2
	txa
	sta tmp2+1
	clc
	lda #$00
	adc tmp2
	sta gk
	lda #$5C
	adc tmp2+1
	sta gk+1
	lda gk
	sta tmp2
	lda gk+1
	sta tmp2+1
	lda #$55
	ldy #$01
	sta (tmp2),y
	lda #$55
	dey
	sta (tmp2),y
	rts
CallAddr_a
	dta $00,$00

; ----------------------------------------------------------------------
; PROC CallAddr(CARD a) - JMP (a); used to call dirs(d)
; ----------------------------------------------------------------------
CallAddr
	jmp L2E73
L2E73
	stx CallAddr_a+1
	sta CallAddr_a
	jmp (CallAddr_a)
BuildMaze_p
	dta $00,$00
BuildMaze_q
	dta $00,$00
BuildMaze_i
	dta $00,$00
BuildMaze_dirs
	dta a(DIRS)
BuildMaze_x
	dta $0A,$00

; ----------------------------------------------------------------------
; PROC BuildMaze() - fill MAZE with walls, carve the fixed path
; ----------------------------------------------------------------------
BuildMaze
	jmp L2E89
L2E89
	lda #$5C
	sta BuildMaze_p+1
	lda #$00
	sta BuildMaze_p
L2E93
	lda #$FF
	cmp BuildMaze_p
	lda #$9B
	sbc BuildMaze_p+1
	bcs L2EA2
	jmp L2EBD
L2EA2
	lda BuildMaze_p
	sta tmp2
	lda BuildMaze_p+1
	sta tmp2+1
	lda #$FF
	ldy #$00
	sta (tmp2),y
	inc BuildMaze_p
	bne L2E93
	inc BuildMaze_p+1
	jmp L2E93
L2EBD
	ldy #$00
	sty cx+1
	lda #$2E
	sta cx
	sty cy+1
	lda #$05
	sta cy
	sty BuildMaze_i+1
	sty BuildMaze_i
	lda #$04
	asl @
	php
	clc
	adc BuildMaze_dirs
	sta tmp2
	lda #$00
	rol @
	plp
	adc BuildMaze_dirs+1
	sta tmp2+1
	lda CarveLeft+2
	iny
	sta (tmp2),y
	lda CarveLeft+1
	dey
	sta (tmp2),y
	lda #$02
	asl @
	php
	clc
	adc BuildMaze_dirs
	sta tmp2
	lda #$00
	rol @
	plp
	adc BuildMaze_dirs+1
	sta tmp2+1
	lda CarveDown+2
	iny
	sta (tmp2),y
	lda CarveDown+1
	dey
	sta (tmp2),y
	lda #$03
	asl @
	php
	clc
	adc BuildMaze_dirs
	sta tmp2
	lda #$00
	rol @
	plp
	adc BuildMaze_dirs+1
	sta tmp2+1
	lda CarveRight+2
	iny
	sta (tmp2),y
	lda CarveRight+1
	dey
	sta (tmp2),y
	lda #$01
	asl @
	php
	clc
	adc BuildMaze_dirs
	sta tmp2
	lda #$00
	rol @
	plp
	adc BuildMaze_dirs+1
	sta tmp2+1
	lda CarveUp+2
	iny
	sta (tmp2),y
	lda CarveUp+1
	dey
	sta (tmp2),y
	sty pathLen+1
	sty pathLen
	jsr MarkCell
L2F5A
	clc
	lda path
	adc BuildMaze_i
	sta tmp2
	lda path+1
	adc BuildMaze_i+1
	sta tmp2+1
	ldy #$00
	lda (tmp2),y
	bne L2F74
	jmp L2FD8
L2F74
	clc
	lda path
	adc BuildMaze_i
	sta tmp2
	lda path+1
	adc BuildMaze_i+1
	sta tmp2+1
	lda (tmp2),y
	asl @
	php
	clc
	adc BuildMaze_dirs
	sta tmp1
	lda #$00
	rol @
	plp
	adc BuildMaze_dirs+1
	sta tmp1+1
	iny
	lda (tmp1),y
	sta arg1
	dey
	lda (tmp1),y
	sta arg0
	ldx arg1
	lda arg0
	jsr CallAddr
	inc BuildMaze_i
	bne L2FB1
	inc BuildMaze_i+1
L2FB1
	clc
	lda path
	adc BuildMaze_i
	sta tmp2
	lda path+1
	adc BuildMaze_i+1
	sta tmp2+1
	clc
	lda pathLen
	ldy #$00
	adc (tmp2),y
	sta pathLen
	lda pathLen+1
	adc #$00
	sta pathLen+1
	jmp L2F5A
L2FD8
	jsr MarkCell
	lda #$5C
	sta BuildMaze_q+1
	lda #$00
	sta BuildMaze_q
L2FE5
	lda #$FF
	cmp BuildMaze_q
	lda #$9B
	sbc BuildMaze_q+1
	bcs L2FF4
	jmp L30A5
L2FF4
	ldy #$00
	sty BuildMaze_i+1
	sty BuildMaze_i
L2FFC
	lda #$09
	cmp BuildMaze_i
	lda #$00
	sbc BuildMaze_i+1
	bcs L300B
	jmp L3091
L300B
	lda #$01
	sta rt_arg
	lda BuildMaze_i+1
	tax
	lda BuildMaze_i
	jsr ACT_LSH	; A:X LSH rt_arg
	sta tmp2
	txa
	sta tmp2+1
	clc
	lda BuildMaze_q
	adc tmp2
	sta gq
	lda BuildMaze_q+1
	adc tmp2+1
	sta gq+1
	clc
	lda gq
	adc #$40
	sta tmp2
	lda gq+1
	adc #$00
	sta tmp2+1
	sec
	lda tmp2
	sbc #$0A
	sta gr
	lda tmp2+1
	sbc #$00
	sta gr+1
	lda gq
	sta tmp2
	lda gq+1
	sta tmp2+1
	ldy #$00
	lda (tmp2),y
	eor #$FF
	bne L3064
	iny
	ora (tmp2),y
	eor #$FF
L3064
	bne L3069
	jmp L3086
L3069
	lda gr
	sta tmp2
	lda gr+1
	sta tmp2+1
	lda gq
	sta tmp1
	lda gq+1
	sta tmp1+1
	lda (tmp1),y
	sta (tmp2),y
	dey
	lda (tmp1),y
	sta (tmp2),y
L3086
	inc BuildMaze_i
	bne L308E
	inc BuildMaze_i+1
L308E
	jmp L2FFC
L3091
	clc
	lda BuildMaze_q
	adc #$80
	sta BuildMaze_q
	lda BuildMaze_q+1
	adc #$00
	sta BuildMaze_q+1
	jmp L2FE5
L30A5
	rts

; ----------------------------------------------------------------------
; PROC HidePM() - players/missiles off screen, GRACTL=0
; ----------------------------------------------------------------------
HidePM
	jmp L30A9
L30A9
	lda hposp
	sta tmp2
	lda hposp+1
	sta tmp2+1
	lda #$00
	ldy #$00
	sta (tmp2),y
	clc
	lda hposp
	adc #$01
	sta tmp2
	lda hposp+1
	adc #$00
	sta tmp2+1
	lda #$00
	sta (tmp2),y
	clc
	lda hposp
	adc #$02
	sta tmp2
	lda hposp+1
	adc #$00
	sta tmp2+1
	lda #$00
	sta (tmp2),y
	clc
	lda hposp
	adc #$03
	sta tmp2
	lda hposp+1
	adc #$00
	sta tmp2+1
	lda #$00
	sta (tmp2),y
	lda hposm
	sta tmp2
	lda hposm+1
	sta tmp2+1
	lda #$00
	sta (tmp2),y
	clc
	lda hposm
	adc #$01
	sta tmp2
	lda hposm+1
	adc #$00
	sta tmp2+1
	lda #$00
	sta (tmp2),y
	clc
	lda hposm
	adc #$02
	sta tmp2
	lda hposm+1
	adc #$00
	sta tmp2+1
	lda #$00
	sta (tmp2),y
	clc
	lda hposm
	adc #$03
	sta tmp2
	lda hposm+1
	adc #$00
	sta tmp2+1
	lda #$00
	sta (tmp2),y
	sty GRACTL
	lda #$22
	sta SDMCTL
	rts
InitGameDL_i
	dta $00

; ----------------------------------------------------------------------
; PROC InitGameDL() - build display list at GAME_DL
; ----------------------------------------------------------------------
InitGameDL
	jmp L3146
L3146
	clc
	lda dlTitle
	adc #$04
	sta arg2
	lda dlTitle+1
	adc #$00
	sta arg3
	lda #$00
	sta arg5
	lda #$20
	sta arg4
	ldy arg2
	ldx #$9C
	lda #$00
	jsr ACT_MOVEBLOCK	; MoveBlock(dest=A:X, src=arg2/3, size=arg4/5)
	lda #$9C
	sta gp+1
	lda #$1F
	sta gp
	lda gp
	sta tmp2
	lda gp+1
	sta tmp2+1
	lda #$00
	ldy #$00
	sta (tmp2),y
	jsr HidePM
	lda #$22
	sta SDMCTL
	lda titlePic+1
	sta GAME_DL+2
	lda titlePic
	sta GAME_DL+1
	lda #$9C
	sta SDLSTL+1
	lda #$00
	sta SDLSTL
	lda #$9C
	sta gp+1
	lda #$20
	sta gp
	ldy #$00
	sty InitGameDL_i
L31AD
	lda #$4B
	cmp InitGameDL_i
	bcs L31B7
	jmp L31E4
L31B7
	lda gp
	sta tmp2
	lda gp+1
	sta tmp2+1
	lda #$78
	ldy #$00
	sta (tmp2),y
	clc
	lda gp
	adc #$03
	sta gp
	lda gp+1
	adc #$00
	sta gp+1
	clc
	lda InitGameDL_i
	adc #$03
	sta InitGameDL_i
	jmp L31AD
L31E4
	lda #$9C
	sta gp+1
	lda #$6E
	sta gp
	lda gp
	sta tmp2
	lda gp+1
	sta tmp2+1
	lda #$58
	ldy #$00
	sta (tmp2),y
	clc
	lda gp
	adc #$03
	sta gp
	lda gp+1
	adc #$00
	sta gp+1
	lda gp
	sta tmp2
	lda gp+1
	sta tmp2+1
	lda #$70
	sta (tmp2),y
	inc gp
	bne L3225
	inc gp+1
L3225
	lda gp
	sta tmp2
	lda gp+1
	sta tmp2+1
	lda #$41
	sta (tmp2),y
	lda #$9C
	sta gr+1
	lda #$CC
	sta gr
	lda gr
	sta tmp2
	lda gr+1
	sta tmp2+1
	lda #$9C
	iny
	sta (tmp2),y
	lda #$00
	dey
	sta (tmp2),y
	rts

; ----------------------------------------------------------------------
; PROC ScrollMaze() - set LMS/HSCROL/VSCROL from scrX,scrY
; ----------------------------------------------------------------------
ScrollMaze
	jmp L3255
L3255
	lda #$04
	sta rt_arg
	lda scrX+1
	tax
	lda scrX
	jsr ACT_RSH	; A:X RSH rt_arg
	sta tmp2
	txa
	sta tmp2+1
	lda #$06
	sta rt_arg
	lda scrY+1
	tax
	lda scrY
	jsr ACT_RSH	; A:X RSH rt_arg
	sta tmp1
	txa
	sta tmp1+1
	lda #$07
	sta rt_arg
	lda tmp1+1
	tax
	lda tmp1
	jsr ACT_LSH	; A:X LSH rt_arg
	sta tmp0
	txa
	sta tmp0+1
	clc
	lda tmp2
	adc tmp0
	sta gofs
	lda tmp2+1
	adc tmp0+1
	sta gofs+1
	lda #$03
	sta rt_arg
	lda scrY+1
	tax
	lda scrY
	jsr ACT_RSH	; A:X RSH rt_arg
	sta tmp2
	txa
	sta tmp2+1
	lda tmp2
	and #$07
	sta rowPhase
	lda tmp2+1
	and #$00
	sta rowPhase+1
	lda #$5C
	sta rowAdr+1
	lda #$00
	sta rowAdr
	lda #$01
	jsr Wait
	lda #$9C
	sta SDLSTL+1
	lda #$00
	sta SDLSTL
	lda scrX
	and #$0F
	sta tmp2
	lda scrX+1
	and #$00
	sta tmp2+1
	sec
	lda #$0F
	sbc tmp2
	sta HSCROL
	lda scrY
	and #$07
	sta VSCROL
	ldy #$01
	sty gi
L32F8
	lda #$4F
	cmp gi
	bcs L3302
	jmp L3381
L3302
	clc
	lda #$00
	adc gi
	sta tmp2
	lda #$9C
	adc #$00
	sta tmp2+1
	clc
	lda tmp2
	adc #$20
	sta gr
	lda tmp2+1
	adc #$00
	sta gr+1
	lda gr
	sta tmp2
	lda gr+1
	sta tmp2+1
	clc
	lda gofs
	adc rowAdr
	sta tmp1
	lda gofs+1
	adc rowAdr+1
	ldy #$01
	sta (tmp2),y
	lda tmp1
	dey
	sta (tmp2),y
	inc rowPhase
	bne L3349
	inc rowPhase+1
L3349
	lda rowPhase
	and #$07
	sta rowPhase
	lda rowPhase+1
	and #$00
	sta rowPhase+1
	lda rowPhase
	ora rowPhase+1
	beq L3364
	jmp L3375
L3364
	clc
	lda rowAdr
	adc #$80
	sta rowAdr
	lda rowAdr+1
	adc #$00
	sta rowAdr+1
L3375
	clc
	lda gi
	adc #$03
	sta gi
	jmp L32F8
L3381
	rts
DrawDigit_dst
	dta $00,$00
DrawDigit_d
	dta $00
DrawDigit_src
	dta $00,$00
DrawDigit_p
	dta $00,$00
DrawDigit_i
	dta $00

; ----------------------------------------------------------------------
; PROC DrawDigit(CARD dst, BYTE d) - 8x8 digit from title picture
; ----------------------------------------------------------------------
DrawDigit
	jmp L338D
L338D
	jsr ACT_PARAMS	; copy arg0.. to PROC locals; followed by .word dest, .byte n-1
	dta a(DrawDigit_dst),$02	; ACT_PARAMS: dest, count-1
	clc
	lda titlePic
	adc #$28
	sta tmp2
	lda titlePic+1
	adc #$0F
	sta tmp2+1
	lda DrawDigit_d
	asl @
	asl @
	asl @
	asl @
	sta tmp1
	clc
	lda tmp2
	adc tmp1
	sta DrawDigit_src
	lda tmp2+1
	adc #$00
	sta DrawDigit_src+1
	lda DrawDigit_dst+1
	sta DrawDigit_p+1
	lda DrawDigit_dst
	sta DrawDigit_p
	ldy #$00
	sty DrawDigit_i
L33CB
	lda #$07
	cmp DrawDigit_i
	bcs L33D5
	jmp L3438
L33D5
	lda DrawDigit_p
	sta tmp2
	lda DrawDigit_p+1
	sta tmp2+1
	lda #$00
	ldy #$01
	sta (tmp2),y
	lda #$00
	dey
	sta (tmp2),y
	inc DrawDigit_p
	bne L33F2
	inc DrawDigit_p+1
L33F2
	lda DrawDigit_p
	sta tmp2
	lda DrawDigit_p+1
	sta tmp2+1
	lda DrawDigit_src
	sta tmp1
	lda DrawDigit_src+1
	sta tmp1+1
	iny
	lda (tmp1),y
	sta (tmp2),y
	dey
	lda (tmp1),y
	sta (tmp2),y
	clc
	lda DrawDigit_src
	adc #$02
	sta DrawDigit_src
	lda DrawDigit_src+1
	adc #$00
	sta DrawDigit_src+1
	clc
	lda DrawDigit_p
	adc #$27
	sta DrawDigit_p
	lda DrawDigit_p+1
	adc #$00
	sta DrawDigit_p+1
	inc DrawDigit_i
	jmp L33CB
L3438
	rts
PrintNum_dst
	dta $00,$00
PrintNum_n
	dta $00,$00
PrintNum_i
	dta $00

; ----------------------------------------------------------------------
; PROC PrintNum(CARD dst, CARD n) - 5 digit number
; ----------------------------------------------------------------------
PrintNum
	jmp L3441
L3441
	jsr ACT_PARAMS	; copy arg0.. to PROC locals; followed by .word dest, .byte n-1
	dta a(PrintNum_dst),$03	; ACT_PARAMS: dest, count-1
	ldy #$00
	sty PrintNum_i
L344C
	lda #$0C
	cmp PrintNum_i
	bcs L3456
	jmp L34B5
L3456
	clc
	lda PrintNum_dst
	adc #$0C
	sta tmp2
	lda PrintNum_dst+1
	adc #$00
	sta tmp2+1
	sec
	lda tmp2
	sbc PrintNum_i
	sta arg0
	lda tmp2+1
	sbc #$00
	sta arg1
	lda #$00
	sta rt_arg+1
	lda #$0A
	sta rt_arg
	lda PrintNum_n+1
	tax
	lda PrintNum_n
	jsr ACT_MOD	; CARD A:X MOD rt_arg -> A:X
	sta arg2
	ldy arg2
	ldx arg1
	lda arg0
	jsr DrawDigit
	lda #$00
	sta rt_arg+1
	lda #$0A
	sta rt_arg
	lda PrintNum_n+1
	tax
	lda PrintNum_n
	jsr ACT_DIV	; CARD A:X / rt_arg -> A:X
	sta PrintNum_n
	txa
	sta PrintNum_n+1
	clc
	lda PrintNum_i
	adc #$03
	sta PrintNum_i
	jmp L344C
L34B5
	rts
DrawBars_a
	dta $00
DrawBars_b
	dta $00
DrawBars_init
	dta $00
DrawBars_t
	dta $00
DrawBars_topB
	dta $00
DrawBars_topA
	dta $00

; ----------------------------------------------------------------------
; PROC DrawBars(BYTE a, b, init) - speed/progress bars in P1/P2
; ----------------------------------------------------------------------
DrawBars
	jmp L34BF
L34BF
	jsr ACT_PARAMS	; copy arg0.. to PROC locals; followed by .word dest, .byte n-1
	dta a(DrawBars_a),$02	; ACT_PARAMS: dest, count-1
	clc
	lda hposp
	adc #$01
	sta tmp2
	lda hposp+1
	adc #$00
	sta tmp2+1
	lda #$30
	ldy #$00
	sta (tmp2),y
	clc
	lda hposp
	adc #$02
	sta tmp2
	lda hposp+1
	adc #$00
	sta tmp2+1
	lda #$C8
	sta (tmp2),y
	clc
	lda pcolr
	adc #$01
	sta tmp2
	lda pcolr+1
	adc #$00
	sta tmp2+1
	lda #$AA
	sta (tmp2),y
	clc
	lda pcolr
	adc #$02
	sta tmp2
	lda pcolr+1
	adc #$00
	sta tmp2+1
	lda #$5A
	sta (tmp2),y
	lda DrawBars_init
	bne L351B
	jmp L35FF
L351B
	lda #$9E
	sta gp+1
	lda #$80
	sta gp
L3525
	lda #$7F
	cmp gp
	lda #$9F
	sbc gp+1
	bcs L3534
	jmp L354F
L3534
	lda gp
	sta tmp2
	lda gp+1
	sta tmp2+1
	lda #$00
	ldy #$00
	sta (tmp2),y
	inc gp
	bne L3525
	inc gp+1
	jmp L3525
L354F
	lda #$9E
	sta gp+1
	lda #$C0
	sta gp
L3559
	lda #$DC
	cmp gp
	lda #$9E
	sbc gp+1
	bcs L3568
	jmp L35A2
L3568
	lda gp
	sta tmp2
	lda gp+1
	sta tmp2+1
	sec
	lda gp
	sbc #$C0
	sta tmp1
	lda gp+1
	sbc #$9E
	sta tmp1+1
	clc
	lda barTxt1
	adc tmp1
	sta tmp0
	lda barTxt1+1
	adc tmp1+1
	sta tmp0+1
	ldy #$00
	lda (tmp0),y
	lsr @
	sta (tmp2),y
	inc gp
	bne L3559
	inc gp+1
	jmp L3559
L35A2
	lda #$9F
	sta gp+1
	lda #$30
	sta gp
L35AC
	lda #$59
	cmp gp
	lda #$9F
	sbc gp+1
	bcs L35BB
	jmp L35F5
L35BB
	lda gp
	sta tmp2
	lda gp+1
	sta tmp2+1
	sec
	lda gp
	sbc #$30
	sta tmp1
	lda gp+1
	sbc #$9F
	sta tmp1+1
	clc
	lda barTxt2
	adc tmp1
	sta tmp0
	lda barTxt2+1
	adc tmp1+1
	sta tmp0+1
	ldy #$00
	lda (tmp0),y
	lsr @
	sta (tmp2),y
	inc gp
	bne L35AC
	inc gp+1
	jmp L35AC
L35F5
	lda #$7F
	sta DrawBars_topB
	lda #$7F
	sta DrawBars_topA
L35FF
	sec
	lda #$FF
	sbc DrawBars_a
	sta gp
	lda #$9E
	sbc #$00
	sta gp+1
	sec
	lda #$7F
	sbc DrawBars_a
	sta DrawBars_t
L3618
	lda DrawBars_t
	cmp DrawBars_topA
	bcc L3623
	jmp L3695
L3623
	lda DrawBars_topA
	cmp #$40
	bcs L362D
	jmp L3668
L362D
	lda #$5C
	cmp DrawBars_topA
	bcs L3637
	jmp L3668
L3637
	lda gp
	sta tmp2
	lda gp+1
	sta tmp2+1
	sec
	lda DrawBars_topA
	sbc #$40
	sta tmp1
	clc
	lda barTxt1
	adc tmp1
	sta tmp0
	lda barTxt1+1
	adc #$00
	sta tmp0+1
	ldy #$00
	lda (tmp0),y
	lsr @
	sta tmp1
	lda tmp1
	eor #$FE
	sta (tmp2),y
	jmp L3678
L3668
	lda gp
	sta tmp2
	lda gp+1
	sta tmp2+1
	lda #$FE
	ldy #$00
	sta (tmp2),y
L3678
	sec
	lda gp
	sbc #$01
	sta gp
	lda gp+1
	sbc #$00
	sta gp+1
	sec
	lda DrawBars_topA
	sbc #$01
	sta DrawBars_topA
	jmp L3618
L3695
	sec
	lda #$7F
	sbc DrawBars_b
	sta gp
	lda #$9F
	sbc #$00
	sta gp+1
	sec
	lda #$7F
	sbc DrawBars_b
	sta DrawBars_t
L36AE
	lda DrawBars_t
	cmp DrawBars_topB
	bcc L36B9
	jmp L372B
L36B9
	lda DrawBars_topB
	cmp #$30
	bcs L36C3
	jmp L36FE
L36C3
	lda #$5A
	cmp DrawBars_topB
	bcs L36CD
	jmp L36FE
L36CD
	lda gp
	sta tmp2
	lda gp+1
	sta tmp2+1
	sec
	lda DrawBars_topB
	sbc #$30
	sta tmp1
	clc
	lda barTxt2
	adc tmp1
	sta tmp0
	lda barTxt2+1
	adc #$00
	sta tmp0+1
	ldy #$00
	lda (tmp0),y
	lsr @
	sta tmp1
	lda tmp1
	eor #$FE
	sta (tmp2),y
	jmp L370E
L36FE
	lda gp
	sta tmp2
	lda gp+1
	sta tmp2+1
	lda #$FE
	ldy #$00
	sta (tmp2),y
L370E
	sec
	lda gp
	sbc #$01
	sta gp
	lda gp+1
	sbc #$00
	sta gp+1
	sec
	lda DrawBars_topB
	sbc #$01
	sta DrawBars_topB
	jmp L36AE
L372B
	rts
InitPM_p
	dta $00,$00

; ----------------------------------------------------------------------
; PROC InitPM() - player/missile graphics setup for the game
; ----------------------------------------------------------------------
InitPM
	jmp L3731
L3731
	lda #$9D
	sta InitPM_p+1
	lda #$80
	sta InitPM_p
L373B
	lda #$FF
	cmp InitPM_p
	lda #$9F
	sbc InitPM_p+1
	bcs L374A
	jmp L3765
L374A
	lda InitPM_p
	sta tmp2
	lda InitPM_p+1
	sta tmp2+1
	lda #$00
	ldy #$00
	sta (tmp2),y
	inc InitPM_p
	bne L373B
	inc InitPM_p+1
	jmp L373B
L3765
	lda #$FF
	sta SIZEM
	lda #$9C
	sta PMBASE
	clc
	lda color
	adc #$03
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$00
	ldy #$00
	sta (tmp2),y
	lda #$03
	sta GRACTL
	lda #$11
	sta GPRIOR
	lda shapes+1
	sta arg3
	lda #$00
	sta arg5
	lda #$08
	sta arg4
	ldy shapes
	ldx #$9E
	lda #$40
	jsr ACT_MOVEBLOCK	; MoveBlock(dest=A:X, src=arg2/3, size=arg4/5)
	lda #$9D
	sta InitPM_p+1
	lda #$93
	sta InitPM_p
L37AF
	lda #$FF
	cmp InitPM_p
	lda #$9D
	sbc InitPM_p+1
	bcs L37BE
	jmp L37D9
L37BE
	lda InitPM_p
	sta tmp2
	lda InitPM_p+1
	sta tmp2+1
	lda #$FF
	ldy #$00
	sta (tmp2),y
	inc InitPM_p
	bne L37AF
	inc InitPM_p+1
	jmp L37AF
L37D9
	lda #$01
	jsr Wait
	lda #$2E
	sta SDMCTL
	lda #$03
	jsr Wait
	lda hposp
	sta tmp2
	lda hposp+1
	sta tmp2+1
	lda #$79
	ldy #$00
	sta (tmp2),y
	lda hposm
	sta tmp2
	lda hposm+1
	sta tmp2+1
	lda #$30
	sta (tmp2),y
	clc
	lda hposm
	adc #$01
	sta tmp2
	lda hposm+1
	adc #$00
	sta tmp2+1
	lda #$38
	sta (tmp2),y
	clc
	lda hposm
	adc #$02
	sta tmp2
	lda hposm+1
	adc #$00
	sta tmp2+1
	lda #$C0
	sta (tmp2),y
	clc
	lda hposm
	adc #$03
	sta tmp2
	lda hposm+1
	adc #$00
	sta tmp2+1
	lda #$C8
	sta (tmp2),y
	lda pcolr
	sta tmp2
	lda pcolr+1
	sta tmp2+1
	lda #$0E
	sta (tmp2),y
	clc
	lda pcolr
	adc #$01
	sta tmp2
	lda pcolr+1
	adc #$00
	sta tmp2+1
	lda #$0E
	sta (tmp2),y
	clc
	lda pcolr
	adc #$02
	sta tmp2
	lda pcolr+1
	adc #$00
	sta tmp2+1
	lda #$0E
	sta (tmp2),y
	clc
	lda pcolr
	adc #$03
	sta tmp2
	lda pcolr+1
	adc #$00
	sta tmp2+1
	lda #$0E
	sta (tmp2),y
	rts
GetInput_key
	dta $00
GetInput_trig
	dta $00
GetInput_x
	dta $00
GetInput_delay
	dta $00

; ----------------------------------------------------------------------
; BYTE FUNC GetInput() - $21 on fire, key code, or $FF
; ----------------------------------------------------------------------
GetInput
	jmp L388E
L388E
	lda #$00
	cmp GetInput_delay
	bcc L3898
	jmp L38A1
L3898
	sec
	lda GetInput_delay
	sbc #$01
	sta GetInput_delay
L38A1
	lda GetInput_delay
	and #$0F
	sta GetInput_delay
	lda strig
	sta tmp2
	lda strig+1
	sta tmp2+1
	ldy #$00
	lda (tmp2),y
	beq L38BC
	jmp L38E0
L38BC
	lda GetInput_trig
	eor #$01
	beq L38C6
	jmp L38E0
L38C6
	lda GetInput_delay
	beq L38CE
	jmp L38E0
L38CE
	ldy #$00
	sty GetInput_trig
	lda #$10
	sta GetInput_delay
	lda #$21
	sta arg0
	rts
	dta $4C,$02,$39
L38E0
	lda strig
	sta tmp2
	lda strig+1
	sta tmp2+1
	ldy #$00
	lda (tmp2),y
	eor #$01
	beq L38F5
	jmp L3902
L38F5
	lda GetInput_trig
	beq L38FD
	jmp L3902
L38FD
	ldy #$01
	sty GetInput_trig
L3902
	lda CH
	eor #$FF
	bne L390C
	jmp L3925
L390C
	lda CH
	sta GetInput_key
	lda #$FF
	sta CH
	lda #$FA
	sta SRTIMR
	lda GetInput_key
	sta arg0
	rts
	dta $4C,$2A,$39
L3925
	lda #$FF
	sta GetInput_key
	lda #$FF
	sta arg0
	rts

; ----------------------------------------------------------------------
; BYTE FUNC AnyKey() - 1 if GetInput()#$FF
; ----------------------------------------------------------------------
AnyKey
	jmp L3932
L3932
	jsr GetInput
	lda arg0
	eor #$FF
	bne L393E
	jmp L3943
L393E
	lda #$01
	sta arg0
	rts
L3943
	lda #$00
	sta arg0
	rts

; ----------------------------------------------------------------------
; PROC StopAll() - DLI off, screen off, music off
; ----------------------------------------------------------------------
StopAll
	jmp L394B
L394B
	lda #$40
	sta NMIEN
	ldy #$00
	sty SDMCTL
	jsr RMT_SILENCE
	lda #$01
	jsr Wait
	rts
	dta $00,$00
Play_dir
	dta $00
Play_frame
	dta $00
Play_key
	dta $00
Play_speed
	dta $00,$00
Play_idx
	dta $00,$00
Play_spd10
	dta $00,$00
Play_accX
	dta $00,$00
Play_accY
	dta $00,$00
Play_stepX
	dta $00
Play_stepY
	dta $00
Play_dx_data
	dta $00,$00,$00,$01,$FF
Play_dx
	dta a(Play_dx_data)
Play_dy_data
	dta $00,$FF,$01,$00,$00
Play_dy
	dta a(Play_dy_data)
Play_tick
	dta $00,$00

; ----------------------------------------------------------------------
; BYTE FUNC PlayGame() - main game loop; 1=passed 2=crash $1C=ESC
; ----------------------------------------------------------------------
PlayGame
	jmp L3982
L3982
	lda #$04
	sta dli_colpf0
	lda #$08
	sta dli_colpf1
	lda #$14
	sta dli_colpf2
	ldy #$00
	sty dli_colbk
	jsr BuildMaze
	lda #$05
	sta scrX+1
	lda #$80
	sta scrX
	ldy #$01
	sty scrY+1
	dey
	sty scrY
	jsr InitGameDL
	jsr ScrollMaze
	jsr InitPM
	ldy #$01
	ldx #$00
	lda #$00
	jsr DrawBars
	lda DliGame+2
	sta VDSLST+1
	lda DliGame+1
	sta VDSLST
	lda #$01
	jsr Wait
	lda #$C0
	sta NMIEN
	lda #$10
	sta Play_speed+1
	lda #$00
	sta Play_speed
	ldy #$00
	sty Play_frame
	sty Play_dir
	sty Play_idx+1
	sty Play_idx
	sty Play_spd10+1
	sty Play_spd10
	sty Play_stepX
	sty Play_stepY
	sty score+1
	sty score
	lda #$0A
	sta rt_arg
	lda Play_speed+1
	tax
	lda Play_speed
	jsr ACT_RSH	; A:X RSH rt_arg
	sta Play_spd10
	txa
	sta Play_spd10+1
	ldy #$57
	ldx #$00
	lda #$00
	jsr RMT_INIT
	ldy #$00
	sty Play_tick+1
	sty Play_tick
L3A24
	lda pcolr
	sta tmp2
	lda pcolr+1
	sta tmp2+1
	clc
	ldy #$00
	lda (tmp2),y
	adc #$01
	sta (tmp2),y
	inc Play_frame
	lda Play_frame
	and #$10
	sta tmp2
	lda tmp2
	bne L3A48
	jmp L3A50
L3A48
	lda #$C4
	sta dli_colpf0
	jmp L3A55
L3A50
	lda #$C8
	sta dli_colpf0
L3A55
	lda Play_frame
	eor #$20
	beq L3A5F
	jmp L3A93
L3A5F
	lda #$00
	cmp Play_dir
	bcc L3A69
	jmp L3A93
L3A69
	inc score
	bne L3A71
	inc score+1
L3A71
	ldy #$00
	sty Play_frame
	lda best
	cmp score
	lda best+1
	sbc score+1
	bcc L3A87
	jmp L3A93
L3A87
	lda score+1
	sta best+1
	lda score
	sta best
L3A93
	clc
	lda titlePic
	adc #$60
	sta arg0
	lda titlePic+1
	adc #$03
	sta arg1
	lda score+1
	sta arg3
	ldy score
	ldx arg1
	lda arg0
	jsr PrintNum
	lda #$00
	cmp Play_dir
	bcc L3ABB
	jmp L3BCF
L3ABB
	lda Play_frame
	eor #$20
	beq L3AC5
	jmp L3AEF
L3AC5
	inc score
	bne L3ACD
	inc score+1
L3ACD
	lda best
	cmp score
	lda best+1
	sbc score+1
	bcc L3ADE
	jmp L3AEA
L3ADE
	lda score+1
	sta best+1
	lda score
	sta best
L3AEA
	ldy #$00
	sty Play_frame
L3AEF
	inc Play_speed
	bne L3AF7
	inc Play_speed+1
L3AF7
	sec
	lda Play_speed
	sbc #$00
	sta tmp2
	lda Play_speed+1
	sbc #$10
	sta tmp2+1
	lda #$06
	sta rt_arg
	lda tmp2+1
	tax
	lda tmp2
	jsr ACT_RSH	; A:X RSH rt_arg
	sta arg0
	lda #$05
	sta rt_arg
	lda Play_idx+1
	tax
	lda Play_idx
	jsr ACT_LSH	; A:X LSH rt_arg
	sta tmp2
	txa
	sta tmp2+1
	lda #$03
	sta rt_arg
	lda pathLen+1
	tax
	lda pathLen
	jsr ACT_RSH	; A:X RSH rt_arg
	sta tmp0
	txa
	sta tmp0+1
	lda tmp0+1
	sta rt_arg+1
	lda tmp0
	sta rt_arg
	lda tmp2+1
	tax
	lda tmp2
	jsr ACT_DIV	; CARD A:X / rt_arg -> A:X
	sta arg1
	ldy #$00
	ldx arg1
	lda arg0
	jsr DrawBars
	clc
	lda Play_accX
	adc Play_speed
	sta Play_accX
	lda Play_accX+1
	adc Play_speed+1
	sta Play_accX+1
	clc
	lda Play_accY
	adc Play_speed
	sta Play_accY
	lda Play_accY+1
	adc Play_speed+1
	sta Play_accY+1
	ldy #$00
	sty Play_stepX
	sty Play_stepY
L3B83
	lda #$00
	cmp Play_accY
	lda #$04
	sbc Play_accY+1
	bcc L3B92
	jmp L3BA9
L3B92
	inc Play_stepY
	sec
	lda Play_accY
	sbc #$00
	sta Play_accY
	lda Play_accY+1
	sbc #$04
	sta Play_accY+1
	jmp L3B83
L3BA9
	lda #$00
	cmp Play_accX
	lda #$08
	sbc Play_accX+1
	bcc L3BB8
	jmp L3BCF
L3BB8
	inc Play_stepX
	sec
	lda Play_accX
	sbc #$00
	sta Play_accX
	lda Play_accX+1
	sbc #$08
	sta Play_accX+1
	jmp L3BA9
L3BCF
	lda Play_frame
	and #$0C
	sta tmp2
	lda tmp2
	asl @
	sta tmp1
	clc
	lda shapes
	adc tmp1
	sta arg2
	lda shapes+1
	adc #$00
	sta arg3
	lda #$00
	sta arg5
	lda #$08
	sta arg4
	ldy arg2
	ldx #$9E
	lda #$40
	jsr ACT_MOVEBLOCK	; MoveBlock(dest=A:X, src=arg2/3, size=arg4/5)
	clc
	lda Play_dx
	adc Play_dir
	sta tmp2
	lda Play_dx+1
	adc #$00
	sta tmp2+1
	ldy #$00
	lda (tmp2),y
	eor #$01
	beq L3C16
	jmp L3C28
L3C16
	clc
	lda scrX
	adc Play_stepX
	sta scrX
	lda scrX+1
	adc #$00
	sta scrX+1
L3C28
	clc
	lda Play_dx
	adc Play_dir
	sta tmp2
	lda Play_dx+1
	adc #$00
	sta tmp2+1
	ldy #$00
	lda (tmp2),y
	eor #$FF
	beq L3C43
	jmp L3C55
L3C43
	sec
	lda scrX
	sbc Play_stepX
	sta scrX
	lda scrX+1
	sbc #$00
	sta scrX+1
L3C55
	clc
	lda Play_dy
	adc Play_dir
	sta tmp2
	lda Play_dy+1
	adc #$00
	sta tmp2+1
	ldy #$00
	lda (tmp2),y
	eor #$01
	beq L3C70
	jmp L3C82
L3C70
	clc
	lda scrY
	adc Play_stepY
	sta scrY
	lda scrY+1
	adc #$00
	sta scrY+1
L3C82
	clc
	lda Play_dy
	adc Play_dir
	sta tmp2
	lda Play_dy+1
	adc #$00
	sta tmp2+1
	ldy #$00
	lda (tmp2),y
	eor #$FF
	beq L3C9D
	jmp L3CAF
L3C9D
	sec
	lda scrY
	sbc Play_stepY
	sta scrY
	lda scrY+1
	sbc #$00
	sta scrY+1
L3CAF
	jsr GetInput
	lda arg0
	sta Play_key
	lda Play_key
	eor #$1C
	beq L3CC1
	jmp L3CCA
L3CC1
	jsr StopAll
	lda Play_key
	sta arg0
	rts
L3CCA
	lda Play_key
	eor #$21
	beq L3CD4
	jmp L3D71
L3CD4
	lda Play_dir
	beq L3CDC
	jmp L3CE1
L3CDC
	lda #$1F
	sta Play_frame
L3CE1
	clc
	lda path
	adc Play_idx
	sta tmp2
	lda path+1
	adc Play_idx+1
	sta tmp2+1
	ldy #$00
	lda (tmp2),y
	sta Play_dir
L3CF9
	clc
	lda path
	adc Play_idx
	sta tmp2
	lda path+1
	adc Play_idx+1
	sta tmp2+1
	lda Play_dir
	ldy #$00
	eor (tmp2),y
	beq L3D16
	jmp L3D6C
L3D16
	inc Play_idx
	bne L3D1E
	inc Play_idx+1
L3D1E
	sec
	lda Play_speed
	sbc #$00
	sta tmp2
	lda Play_speed+1
	sbc #$10
	sta tmp2+1
	lda #$06
	sta rt_arg
	lda tmp2+1
	tax
	lda tmp2
	jsr ACT_RSH	; A:X RSH rt_arg
	sta arg0
	lda #$06
	sta rt_arg
	lda Play_idx+1
	tax
	lda Play_idx
	jsr ACT_LSH	; A:X LSH rt_arg
	sta tmp2
	txa
	sta tmp2+1
	lda #$00
	sta rt_arg+1
	lda #$9C
	sta rt_arg
	lda tmp2+1
	tax
	lda tmp2
	jsr ACT_DIV	; CARD A:X / rt_arg -> A:X
	sta arg1
	ldy #$00
	ldx arg1
	lda arg0
	jsr DrawBars
	jmp L3CF9
L3D6C
	lda #$FF
	sta CH
L3D71
	lda #$00
	cmp Play_tick
	lda #$18
	sbc Play_tick+1
	bcc L3D80
	jmp L3DE7
L3D80
	lda RMT_VAR_494A
	and #$0F
	sta tmp2
	lda #$10
	ora tmp2
	sta dli_colpf2
	ldy #$00
	sty dli_colbk
	clc
	lda color
	adc #$03
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$00
	sta (tmp2),y
	lda Play_tick
	and #$06
	sta tmp2
	lda Play_tick+1
	and #$00
	sta tmp2+1
	lda #$00
	cmp tmp2
	lda #$00
	sbc tmp2+1
	bcc L3DC1
	jmp L3DE4
L3DC1
	lda #$00
	cmp RMT_VAR_494A
	bcc L3DCB
	jmp L3DE4
L3DCB
	lda #$6F
	sta dli_colbk
	clc
	lda color
	adc #$03
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda dli_colbk
	sta (tmp2),y
L3DE4
	jmp L3EDD
L3DE7
	lda #$00
	cmp Play_tick
	lda #$0C
	sbc Play_tick+1
	bcc L3DF6
	jmp L3E5F
L3DF6
	lda RMT_VAR_494A
	and #$0F
	sta tmp2
	lda #$10
	ora tmp2
	sta dli_colpf2
	ldy #$00
	sty dli_colbk
	clc
	lda color
	adc #$03
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$00
	sta (tmp2),y
	lda Play_tick
	and #$07
	sta tmp2
	lda Play_tick+1
	and #$00
	sta tmp2+1
	lda tmp2
	eor #$07
	bne L3E34
	ora tmp2+1
	eor #$00
L3E34
	beq L3E39
	jmp L3E5C
L3E39
	lda #$04
	cmp RMT_VAR_494A
	bcc L3E43
	jmp L3E5C
L3E43
	lda #$6F
	sta dli_colbk
	clc
	lda color
	adc #$03
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda dli_colbk
	sta (tmp2),y
L3E5C
	jmp L3EDD
L3E5F
	lda #$00
	cmp Play_tick
	lda #$06
	sbc Play_tick+1
	bcc L3E6E
	jmp L3E7F
L3E6E
	lda RMT_VAR_494A
	and #$0F
	sta tmp2
	lda #$10
	ora tmp2
	sta dli_colpf2
	jmp L3EDD
L3E7F
	lda #$80
	cmp Play_tick
	lda #$04
	sbc Play_tick+1
	bcc L3E8E
	jmp L3EAB
L3E8E
	lda RMT_VAR_494A
	and #$0F
	sta tmp2
	lda tmp2
	lsr @
	sta tmp1
	clc
	lda tmp1
	adc #$02
	sta tmp2
	lda #$10
	ora tmp2
	sta dli_colpf2
	jmp L3EDD
L3EAB
	lda #$00
	cmp Play_tick
	lda #$03
	sbc Play_tick+1
	bcc L3EBA
	jmp L3ED8
L3EBA
	lda RMT_VAR_494A
	and #$0F
	sta tmp2
	lda tmp2
	lsr @
	lsr @
	sta tmp1
	clc
	lda tmp1
	adc #$04
	sta tmp2
	lda #$10
	ora tmp2
	sta dli_colpf2
	jmp L3EDD
L3ED8
	lda #$14
	sta dli_colpf2
L3EDD
	jsr ScrollMaze
	jsr RMT_PLAY
	inc Play_tick
	bne L3EEB
	inc Play_tick+1
L3EEB
	lda p0pf
	sta tmp2
	lda p0pf+1
	sta tmp2+1
	ldy #$00
	lda (tmp2),y
	eor #$04
	beq L3F00
	jmp L3F08
L3F00
	jsr StopAll
	lda #$02
	sta arg0
	rts
L3F08
	lda #$14
	cmp Play_idx
	lda #$00
	sbc Play_idx+1
	bcc L3F17
	jmp L3F34
L3F17
	lda p0pf
	sta tmp2
	lda p0pf+1
	sta tmp2+1
	ldy #$00
	lda (tmp2),y
	eor #$01
	beq L3F2C
	jmp L3F34
L3F2C
	jsr StopAll
	lda #$01
	sta arg0
	rts
L3F34
	ldy #$01
	sty HITCLR
	jmp L3A24
Title_p
	dta $00,$00
Title_key
	dta $00

; ----------------------------------------------------------------------
; PROC TitleScreen() - title, hi-score, waits for a key
; ----------------------------------------------------------------------
TitleScreen
	jmp L3F42
L3F42
	lda DliTitle+2
	sta VDSLST+1
	lda DliTitle+1
	sta VDSLST
	lda #$C0
	sta NMIEN
	jsr HidePM
	lda #$22
	sta SDMCTL
	clc
	lda dlTitle
	adc #$05
	sta Title_p
	lda dlTitle+1
	adc #$00
	sta Title_p+1
	lda Title_p
	sta tmp2
	lda Title_p+1
	sta tmp2+1
	lda titlePic+1
	ldy #$01
	sta (tmp2),y
	lda titlePic
	dey
	sta (tmp2),y
	clc
	lda Title_p
	adc #$66
	sta Title_p
	lda Title_p+1
	adc #$00
	sta Title_p+1
	lda Title_p
	sta tmp2
	lda Title_p+1
	sta tmp2+1
	lda dlTitle+1
	iny
	sta (tmp2),y
	lda dlTitle
	dey
	sta (tmp2),y
	lda dlTitle+1
	sta SDLSTL+1
	lda dlTitle
	sta SDLSTL
	clc
	lda titlePic
	adc #$9F
	sta arg0
	lda titlePic+1
	adc #$09
	sta arg1
	lda best+1
	sta arg3
	ldy best
	ldx arg1
	lda arg0
	jsr PrintNum
	lda color
	sta tmp2
	lda color+1
	sta tmp2+1
	lda #$60
	ldy #$00
	sta (tmp2),y
	clc
	lda color
	adc #$01
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$62
	sta (tmp2),y
	clc
	lda color
	adc #$02
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$62
	sta (tmp2),y
	clc
	lda color
	adc #$04
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$00
	sta (tmp2),y
	ldy #$50
	ldx #$00
	lda #$00
	jsr RMT_INIT
L4026
	jsr GetInput
	lda arg0
	sta Title_key
	lda Title_key
	eor #$1C
	bne L4038
	jmp L4046
L4038
	lda Title_key
	eor #$FF
	bne L4042
	jmp L4046
L4042
	jsr StopAll
	rts
L4046
	jsr RMT_PLAY
	lda #$01
	jsr Wait
	jsr RMT_PLAY
	ldy #$00
	sty gk+1
	sty gk
L4059
	lda #$4B
	cmp gk
	lda #$00
	sbc gk+1
	bcs L4068
	jmp L4078
L4068
	ldy #$00
	sty WSYNC
	inc gk
	bne L4059
	inc gk+1
	jmp L4059
L4078
	jmp L4026
Win_p
	dta $00,$00

; ----------------------------------------------------------------------
; PROC WinScreen() - 'MAZA PASSED!' screen
; ----------------------------------------------------------------------
WinScreen
	jmp L4080
L4080
	lda DliWin+2
	sta VDSLST+1
	lda DliWin+1
	sta VDSLST
	lda #$C0
	sta NMIEN
	jsr HidePM
	lda #$22
	sta SDMCTL
	clc
	lda dlWin
	adc #$0D
	sta Win_p
	lda dlWin+1
	adc #$00
	sta Win_p+1
	lda Win_p
	sta tmp2
	lda Win_p+1
	sta tmp2+1
	clc
	lda titlePic
	adc #$48
	sta tmp1
	lda titlePic+1
	adc #$0D
	ldy #$01
	sta (tmp2),y
	lda tmp1
	dey
	sta (tmp2),y
	clc
	lda dlWin
	adc #$1B
	sta Win_p
	lda dlWin+1
	adc #$00
	sta Win_p+1
	lda Win_p
	sta tmp2
	lda Win_p+1
	sta tmp2+1
	lda dlWin+1
	iny
	sta (tmp2),y
	lda dlWin
	dey
	sta (tmp2),y
	lda dlWin+1
	sta SDLSTL+1
	lda dlWin
	sta SDLSTL
	lda color
	sta tmp2
	lda color+1
	sta tmp2+1
	lda #$06
	sta (tmp2),y
	clc
	lda color
	adc #$01
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$0A
	sta (tmp2),y
	clc
	lda color
	adc #$02
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$0E
	sta (tmp2),y
	clc
	lda color
	adc #$04
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$00
	sta (tmp2),y
	ldy #$57
	ldx #$00
	lda #$25
	jsr RMT_INIT
	jsr RMT_PLAY
L4150
	jsr RMT_PLAY
	lda #$01
	jsr Wait
	jsr AnyKey
	lda arg0
	bne L4162
	jmp L4166
L4162
	jsr StopAll
	rts
L4166
	jmp L4150
	dta $60
Crash_p
	dta $00,$00
Crash_n
	dta $00
Crash_c
	dta $00

; ----------------------------------------------------------------------
; PROC CrashScreen() - shaking crash picture
; ----------------------------------------------------------------------
CrashScreen
	jmp L4171
L4171
	jsr HidePM
	ldy #$57
	ldx #$00
	lda #$28
	jsr RMT_INIT
	ldy #$00
	sty Crash_n
	lda #$22
	sta SDMCTL
	clc
	lda dlCrash
	adc #$0B
	sta Crash_p
	lda dlCrash+1
	adc #$00
	sta Crash_p+1
	lda Crash_p
	sta tmp2
	lda Crash_p+1
	sta tmp2+1
	clc
	lda titlePic
	adc #$00
	sta tmp1
	lda titlePic+1
	adc #$10
	iny
	sta (tmp2),y
	lda tmp1
	dey
	sta (tmp2),y
	clc
	lda dlCrash
	adc #$39
	sta Crash_p
	lda dlCrash+1
	adc #$00
	sta Crash_p+1
	lda Crash_p
	sta tmp2
	lda Crash_p+1
	sta tmp2+1
	lda dlCrash+1
	iny
	sta (tmp2),y
	lda dlCrash
	dey
	sta (tmp2),y
	lda dlCrash+1
	sta SDLSTL+1
	lda dlCrash
	sta SDLSTL
	lda color
	sta tmp2
	lda color+1
	sta tmp2+1
	lda #$04
	sta (tmp2),y
	clc
	lda color
	adc #$01
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$08
	sta (tmp2),y
	clc
	lda color
	adc #$02
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$0C
	sta (tmp2),y
L421E
	inc Crash_n
	jsr RMT_PLAY
	lda #$01
	jsr Wait
	jsr RMT_PLAY
	lda #$01
	jsr Wait
	jsr RMT_PLAY
	lda #$01
	jsr Wait
	lda RANDOM
	and #$07
	sta VSCROL
	lda RANDOM
	and #$07
	sta HSCROL
	lda Crash_n
	asl @
	asl @
	asl @
	asl @
	sta tmp2
	lda tmp2
	and #$E0
	sta Crash_c
	lda Crash_n
	and #$02
	sta tmp2
	lda tmp2
	bne L4267
	jmp L42BC
L4267
	lda color
	sta tmp2
	lda color+1
	sta tmp2+1
	lda #$04
	ora Crash_c
	ldy #$00
	sta (tmp2),y
	clc
	lda color
	adc #$01
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$08
	ora Crash_c
	sta (tmp2),y
	clc
	lda color
	adc #$02
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$0E
	ora Crash_c
	sta (tmp2),y
	clc
	lda color
	adc #$04
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$00
	sta (tmp2),y
	jmp L430E
L42BC
	lda color
	sta tmp2
	lda color+1
	sta tmp2+1
	lda #$08
	ora Crash_c
	ldy #$00
	sta (tmp2),y
	clc
	lda color
	adc #$01
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$04
	ora Crash_c
	sta (tmp2),y
	clc
	lda color
	adc #$02
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$00
	sta (tmp2),y
	clc
	lda color
	adc #$04
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$0E
	ora Crash_c
	sta (tmp2),y
L430E
	lda #$1C
	cmp Crash_n
	bcc L4318
	jmp L4336
L4318
	jsr StopAll
	clc
	lda color
	adc #$04
	sta tmp2
	lda color+1
	adc #$00
	sta tmp2+1
	lda #$00
	ldy #$00
	sta (tmp2),y
	lda #$32
	jsr Wait
	rts
L4336
	jmp L421E
	dta $60
Main_r
	dta $00

; ----------------------------------------------------------------------
; PROC Main() - DO TitleScreen() r=PlayGame() ... OD
; ----------------------------------------------------------------------
Main
	jmp L433E
L433E
	jsr TitleScreen
	jsr PlayGame
	lda arg0
	sta Main_r
	lda Main_r
	eor #$01
	beq L4353
	jmp L4356
L4353
	jsr WinScreen
L4356
	lda Main_r
	eor #$02
	beq L4360
	jmp L4363
L4360
	jsr CrashScreen
L4363
	jmp L433E

; ======================================================================
; $4366-$4FFF  RMT player: variables, tables, code at $4C00
; ======================================================================
	org $4366
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00
D48DF
	dta $00
D48E0
	dta $00,$00,$00,$00
D48E4
	dta $00,$00,$00,$00
D48E8
	dta $00,$00,$00,$00
D48EC
	dta $00,$00,$00,$00
D48F0
	dta $00,$00,$00,$00
D48F4
	dta $00,$00,$00,$00,$00,$00,$00,$00
D48FC
	dta $00,$00,$00,$00
D4900
	dta $00,$00,$00,$00
D4904
	dta $00,$00,$00,$00
D4908
	dta $00,$00,$00,$00
D490C
	dta $00,$00,$00,$00
D4910
	dta $00,$00,$00,$00
D4914
	dta $00,$00,$00,$00
D4918
	dta $00,$00,$00,$00
D491C
	dta $00,$00,$00,$00
D4920
	dta $00,$00,$00,$00
D4924
	dta $00,$00,$00,$00
D4928
	dta $00,$00,$00,$00
D492C
	dta $00,$00,$00,$00
D4930
	dta $00,$00,$00,$00
D4934
	dta $00,$00,$00,$00
D4938
	dta $00,$00,$00,$00
D493C
	dta $00
D493D
	dta $00,$00,$00
D4940
	dta $00
D4941
	dta $00,$00,$00
D4944
	dta $00
D4945
	dta $00
D4946
	dta $00
D4947
	dta $00
D4948
	dta $00
D4949
	dta $00
RMT_VAR_494A
	dta $00,$00
D494C
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$60,$EA,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00
D4982
	dta $80
D4983
	dta $00,$80,$20,$80,$40,$00,$C0,$80,$80,$80,$A0,$00,$C0,$40,$C0,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$BF,$B6,$AA
	dta $A1,$98,$8F,$89,$80,$F2,$E6,$DA,$CE,$BF,$B6,$AA,$A1,$98,$8F,$89
	dta $80,$7A,$71,$6B,$65,$5F,$5C,$56,$50,$4D,$47,$44,$3E,$3C,$38,$35
	dta $32,$2F,$2D,$2A,$28,$25,$23,$21,$1F,$1D,$1C,$1A,$18,$17,$16,$14
	dta $13,$12,$11,$10,$0F,$0E,$0D,$0C,$0B,$0A,$09,$08,$07,$FF,$F1,$E4
	dta $D8,$CA,$C0,$B5,$AB,$A2,$99,$8E,$87,$7F,$79,$73,$70,$66,$61,$5A
	dta $55,$52,$4B,$48,$43,$3F,$3C,$39,$37,$33,$30,$2D,$2A,$28,$25,$24
	dta $21,$1F,$1E,$1C,$1B,$19,$17,$16,$15,$13,$12,$11,$10,$0F,$0E,$0D
	dta $0C,$0B,$0A,$09,$08,$07,$06,$05,$04,$03,$02,$01,$00,$F3,$E6,$D9
	dta $CC,$C1,$B5,$AD,$A2,$99,$90,$88,$80,$79,$72,$6C,$66,$60,$5B,$55
	dta $51,$4C,$48,$44,$40,$3C,$39,$35,$32,$2F,$2D,$2A,$28,$25,$23,$21
	dta $1F,$1D,$1C,$1A,$18,$17,$16,$14,$13,$12,$11,$10,$0F,$0E,$0D,$0C
	dta $0B,$0A,$09,$08,$07,$06,$05,$04,$03,$02,$01,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
D4B00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$01,$01,$01,$01,$01,$01,$01,$01
	dta $00,$00,$00,$00,$01,$01,$01,$01,$01,$01,$01,$01,$02,$02,$02,$02
	dta $00,$00,$00,$01,$01,$01,$01,$01,$02,$02,$02,$02,$02,$03,$03,$03
	dta $00,$00,$01,$01,$01,$01,$02,$02,$02,$02,$03,$03,$03,$03,$04,$04
	dta $00,$00,$01,$01,$01,$02,$02,$02,$03,$03,$03,$04,$04,$04,$05,$05
	dta $00,$00,$01,$01,$02,$02,$02,$03,$03,$04,$04,$04,$05,$05,$06,$06
	dta $00,$00,$01,$01,$02,$02,$03,$03,$04,$04,$05,$05,$06,$06,$07,$07
	dta $00,$01,$01,$02,$02,$03,$03,$04,$04,$05,$05,$06,$06,$07,$07,$08
	dta $00,$01,$01,$02,$02,$03,$04,$04,$05,$05,$06,$07,$07,$08,$08,$09
	dta $00,$01,$01,$02,$03,$03,$04,$05,$05,$06,$07,$07,$08,$09,$09,$0A
	dta $00,$01,$01,$02,$03,$04,$04,$05,$06,$07,$07,$08,$09,$0A,$0A,$0B
	dta $00,$01,$02,$02,$03,$04,$05,$06,$06,$07,$08,$09,$0A,$0A,$0B,$0C
	dta $00,$01,$02,$03,$03,$04,$05,$06,$07,$08,$09,$0A,$0A,$0B,$0C,$0D
	dta $00,$01,$02,$03,$04,$05,$06,$07,$07,$08,$09,$0A,$0B,$0C,$0D,$0E
	dta $00,$01,$02,$03,$04,$05,$06,$07,$08,$09,$0A,$0B,$0C,$0D,$0E,$0F
RMT_INIT
	jmp L4C0F
RMT_PLAY
	jmp L4DC6
RMT_P3
	jmp L4DEA
RMT_SILENCE
	jmp L4C58
RMT_SETPOKEY
	jmp L4F5D
L4C0F
	stx $73
	sty $74
	pha
	ldy #$6D
	lda #$00
L4C18
	sta D48DF,y
	dey
	bne L4C18
	ldy #$04
	lda ($73),y
	sta $4DDE
	iny
	lda ($73),y
	sta L4CBE+1
	iny
	lda ($73),y
	sta $4DCF
	sta $4F5B
	ldy #$08
L4C36
	lda ($73),y
	sta.a $0063,y
	iny
	cpy #$10
	bne L4C36
	pla
	pha
	asl @
	asl @
	clc
	adc $71
	sta $71
	pla
	php
	and #$C0
	asl @
	rol @
	rol @
	plp
	adc $72
	sta $72
	jsr L4C6E
L4C58
	lda #$00
	sta $D208
	ldy #$03
	sty $D20F
	ldy #$08
L4C64
	sta $D200,y
	dey
	bpl L4C64
	lda $4DCF
	rts
L4C6E
	ldx #$00
	stx $4DDC
L4C73
	txa
	tay
	lda ($71),y
	cmp #$FE
	bcs L4CA8
	tay
	lda ($6D),y
	sta D48E0,x
	lda ($6F),y
	sta D48E4,x
	lda #$00
	sta D48E8,x
	lda #$01
L4C8D
	sta D48EC,x
	lda #$80
	sta D4900,x
	inx
	cpx #$04
	bne L4C73
	lda $71
	clc
	adc #$04
	sta $71
	bcc L4CBE
	inc $72
	jmp L4CBE
L4CA8
	beq L4CAE
	lda #$00
	beq L4C8D
L4CAE
	ldy #$02
	lda ($71),y
	tax
	iny
	lda ($71),y
	sta $72
	stx $71
	ldx #$00
	beq L4C73
L4CBE
	lda #$FF
	sta $4D12
	ldx #$FF
L4CC5
	inx
	dec D48EC,x
	bne L4D0D
	lda D48E0,x
	sta $73
	lda D48E4,x
	sta $74
L4CD5
	ldy D48E8,x
	inc D48E8,x
	lda ($73),y
	sta $79
	and #$3F
	cmp #$3D
	beq L4CF3
	bcs L4D1C
	sta D48F0,x
	iny
	lda ($73),y
	lsr @
	and #$7E
	sta D4900,x
L4CF3
	lda #$01
	sta D48EC,x
	ldy D48E8,x
	inc D48E8,x
	lda ($73),y
	lsr @
	ror $79
	lsr @
	ror $79
	lda $79
	and #$F0
	sta D48F4,x
L4D0D
	cpx #$03
	bne L4CC5
	lda #$FF
	sta L4CBE+1
	sta D494C
	jmp L4D61
L4D1C
	cmp #$3F
	beq L4D3B
	lda $79
	and #$C0
	beq L4D2F
	asl @
	rol @
	rol @
	sta D48EC,x
	jmp L4D0D
L4D2F
	iny
	lda ($73),y
	sta D48EC,x
	inc D48E8,x
	jmp L4D0D
L4D3B
	lda $79
	bmi L4D4B
	iny
	lda ($73),y
	sta $4D12
	inc D48E8,x
	jmp L4CD5
L4D4B
	cmp #$FF
	beq L4D58
	iny
	lda ($73),y
	sta D48E8,x
	jmp L4CD5
L4D58
	jmp L4C6E
L4D5B
	jmp L4DEA
L4D5E
	dex
	bmi L4D5B
L4D61
	ldy D4900,x
	bmi L4D5E
	lda ($6B),y
	sta D4904,x
	sta $77
	iny
	lda ($6B),y
	sta D4908,x
	sta $78
	lda #$01
	sta D4940,x
	tay
	lda ($77),y
	sta D4934,x
	iny
	lda ($77),y
	sta D4910,x
	iny
	lda ($77),y
	sta D4914,x
	iny
	lda ($77),y
	sta D4924,x
	and #$3F
	sta D4938,x
	ldy #$06
	lda ($77),y
	sta D491C,x
	lda #$80
	sta D4920,x
	sta D4900,x
	asl @
	sta D4918,x
	sta D48FC,x
	tay
	lda ($77),y
	sta D4930,x
	adc #$00
	sta D490C,x
	lda #$0C
	sta D492C,x
	tay
	lda ($77),y
	sta D4928,x
	jmp L4D5E
L4DC6
	jsr L4F5D
	dec $4F5B
	bne L4DEA
	lda #$FF
	sta $4F5B
	dec D494C
	bne L4DEA
	inc $4DDC
	lda #$FF
	cmp #$FF
	beq L4DE4
	jmp L4CBE
L4DE4
	jmp L4C6E
L4DE7
	jmp L4F09
L4DEA
	lda #$4A
	sta $76
	ldx #$03
L4DF0
	lda D4908,x
	beq L4DE7
	sta $74
	lda D4904,x
	sta $73
	ldy D490C,x
	lda ($73),y
	sta $79
	iny
	lda ($73),y
	sta $7A
	iny
	lda ($73),y
	sta $7B
	iny
	tya
	cmp D4910,x
	bcc L4E1E
	beq L4E1E
	lda #$80
	sta D4918,x
	lda D4914,x
L4E1E
	sta D490C,x
	lda $79
	and #$0F
	ora D48F4,x
	tay
	lda D4B00,y
	sta $7C
	lda $7A
	and #$0E
	tay
	lda D4982,y
	sta $75
	lda $7C
	ora D4983,y
	sta D4948,x
	ldy D4930,x
	cpy #$0D
	bcc L4E7A
	lda D4938,x
	bpl L4E74
	tya
	cmp D492C,x
	bne L4E5A
	lda D4934,x
	sta D492C,x
	bne L4E5D
L4E5A
	inc D492C,x
L4E5D
	lda D4904,x
	sta $77
	lda D4908,x
	sta $78
	ldy D492C,x
	lda ($77),y
	sta D4928,x
	lda D4924,x
	and #$3F
L4E74
	sec
	sbc #$01
	sta D4938,x
L4E7A
	lda D4918,x
	bpl L4E97
	lda D48F4,x
	beq L4E97
	tay
	lda D4920,x
	clc
	adc D491C,x
	sta D4920,x
	bcc L4E97
	tya
	sbc #$10
	sta D48F4,x
L4E97
	lda $7A
	sta D493C,x
	and #$70
	lsr @
	lsr @
	sta L4EA3+1
L4EA3
	bcc L4EA3
	jmp L4ECC
	dta $EA,$4C,$B8,$4E,$EA,$4C,$BD,$4E,$EA,$4C,$BD,$4E,$EA,$4C,$BD,$4E
	dta $A5,$7B,$4C,$06,$4F,$BD,$FC,$48,$18,$65,$7B,$9D,$FC,$48,$BD,$F0
	dta $48,$4C,$D2,$4E
L4ECC
	lda D48F0,x
	clc
	adc $7B
	ldy D4924,x
	bmi L4EF0
	clc
	adc D4928,x
	cmp #$3D
	bcc L4EE6
	lda #$00
	sta D4948,x
	lda #$3F
L4EE6
	tay
	lda ($75),y
	clc
	adc D48FC,x
	jmp L4F06
L4EF0
	cmp #$3D
	bcc L4EFB
	lda #$00
	sta D4948,x
	lda #$3F
L4EFB
	tay
	lda D48FC,x
	clc
	adc D4928,x
	clc
	adc ($75),y
L4F06
	sta D4944,x
L4F09
	dex
	bmi L4F0F
	jmp L4DF0
L4F0F
	ldx #$00
	stx L4F5D+1
	lda D493C
	bpl L4F33
	lda D4948
	and #$0F
	beq L4F33
	lda D4944
	clc
	adc D4940
	sta D4946
	lda #$00
	sta RMT_VAR_494A
	txa
	ora #$04
	tax
L4F33
	lda D493D
	bpl L4F52
	lda D4949
	and #$0F
	beq L4F52
	lda D4945
	clc
	adc D4941
	sta D4947
	lda #$00
	sta RMT_VAR_494A+1
	txa
	ora #$02
	tax
L4F52
	cpx L4F5D+1
	bne L4F57
L4F57
	stx L4F5D+1
	lda #$FF
	rts
L4F5D
	ldy #$FF
	lda D4944
	ldx D4948
	sta $D200
	stx $D201
	lda D4945
	ldx D4949
	sta $D202
	stx $D203
	lda D4946
	ldx RMT_VAR_494A
	sta $D204
	stx $D205
	lda D4947
	ldx RMT_VAR_494A+1
	sta $D206
	stx $D207
	sty $D208
	rts
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	dta $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00

; ======================================================================
; $5000-$56FF  RMT module: title music
; ======================================================================
	org $5000
	ins 'data/music_title.bin'

; ======================================================================
; $5700-$5BA6  RMT module: game / win / crash music
; ======================================================================
	org $5700
	ins 'data/music_game.bin'

; ======================================================================
; $A000-$BBFF  Action! cartridge image (runtime library)
; ======================================================================
	org $A000
	ins 'data/action_runtime.bin'

; ---- RUN: what the original INIT stub + depacker did before Main
	org $0680
start	ldx #$FF
	stx CH
	inx
	stx SDMCTL
	lda RTCLOK
st_wait	cmp RTCLOK
	beq st_wait
	lda #$40
	sta NMIEN
	cli
	jmp Main
	run start
