#!/usr/bin/env python3
"""Build the data of The Lair VBXE port from the PICO-8 cartridge.

The cart is run in the Lua shim of tools/pico_ref.py, and the tables the
game builds (classes with their inheritance resolved, state handlers,
sprite layouts, hitboxes, palettes, difficulties, stages, waves) are read
from the live Lua state, so they are exactly the cart's values.

Writes:
  data/gfx.bin        8192 bytes   sprite sheet, 4 bpp (staged to VRAM)
  data/vr_*.bin                    VRAM images: font, XDLs, reflection rows,
                                   moons, shadows, outlined font, floor strips,
                                   map rows
  gen/load.asm                     XEX segments that stage the VRAM images
  gen/params.asm                   constants (class, state, bank numbers...)
  gen/tables.asm                   tables at $a000 (classes, sprite layouts,
                                   texts, waves, floor offsets...)
  gen/hi.asm                       tables under the OS ROM (sfx, music, sine,
                                   normalisation, palettes)
"""
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pico_ref import Pico, PAL          # noqa: E402
from font import FONT, GLYPHS           # noqa: E402

HERE = Path(__file__).resolve().parent.parent
(HERE / 'data').mkdir(exist_ok=True)
(HERE / 'gen').mkdir(exist_ok=True)

P = Pico(1)
L = P.lua
cart = bytes(P.cart)
L.execute('''
fname={}
for k,v in pairs(_G) do if type(v)=="function" then fname[v]=k end end
function rget(cls,key)
  local c=rl[cls]
  while c do
    local v=rawget(c,key)
    if v~=nil then return v end
    c=c.lm and rl[c.lm]
  end
  return nil
end
function fnof(cls,key) local v=rget(cls,key) if type(v)=="function" then return fname[v] or "anon" end return nil end
function ingroup(cls,g) local c=cls while c do if c==g then return true end c=rl[c].lm end return false end
''')

CLASSES = ['player', 'boss', 'crst', 'skel', 'capt', 'wrth', 'ston', 'eldr', 'blch', 'frsp',
           'felm', 'lz', 'ia', 'sb', 'qf', 'bh', 'em', 'fr', 'lq']
CID = {c: i + 1 for i, c in enumerate(CLASSES)}
STATES = ['jr', 'gf', 'jp', 'de', 'oo', 'hc', 'qi', 'co', 'dt', 'ln', 'lx', 'ok', 'sf', 'nx',
          'j_', 'ox', 'nd', 'jh', 'ib', 'mi', 'idle']
SID = {s: i for i, s in enumerate(STATES)}
CBS = ['hit_player', 'hit_monster', 'hit_proj', 'hit_radar', 'ec', 'ra', 'du', 'kc']


def rget(cls, key):
    v = L.eval(f'rget("{cls}","{key}")')
    return v


def num(v, default=0):
    if v is None or v is False:
        return default
    if v is True:
        return 1
    return v


def b(v):
    return int(v) & 255


def fx88(v):
    """signed 8.8"""
    n = int(round(num(v) * 256))
    return n & 0xffff


def frac(v):
    """fraction byte, 1.0 -> 0 (meaning 'unchanged')"""
    v = num(v)
    if v >= 1:
        return 0
    return max(1, min(255, int(round(v * 256))))


out = []        # tables.asm
hi = []         # hi.asm
prm = ['; generated by tools/make_data.py - do not edit']


def dta(name, values, width=16):
    lines = [f'{name}']
    for i in range(0, len(values), width):
        lines.append('        dta ' + ','.join(str(v & 255) for v in values[i:i + width]))
    if not values:
        lines.append('        ; (empty)')
    return '\n'.join(lines) + '\n'


def words(name, labels):
    return (f'{name}_lo\n' + ''.join(f'        dta <{x}\n' for x in labels) +
            f'{name}_hi\n' + ''.join(f'        dta >{x}\n' for x in labels))


# ---------------------------------------------------------------- constants
for c, i in CID.items():
    prm.append(f'C_{c.upper()} = {i}')
prm.append(f'NCLS = {len(CLASSES) + 1}')
for s, i in SID.items():
    prm.append(f'S_{s.upper()} = {i}')
prm.append(f'NST = {len(STATES)}')
GROUPS = [('kj', 1), ('ks', 2), ('monster', 4), ('proj', 8), ('player', 16), ('crst', 32), ('oj', 64)]
for g, bit in GROUPS:
    prm.append(f'G_{g.upper()} = {bit}')

# ---------------------------------------------------------------- handlers
handlers = set()
# state handlers: one row per state, indexed by class (rows hnd_<lo|hi>_<s>)
rows_lo, rows_hi = [], []
for si, st in enumerate(STATES):
    labs = []
    for c in [None] + CLASSES:
        name = L.eval(f'fnof("{c}","{st}")') if c else None
        lab = f'h_{name}' if name else 'h_none'
        handlers.add(lab)
        labs.append(lab)
    out.append(f'hnl_{si}\n' + ''.join(f'        dta <{x}\n' for x in labs))
    out.append(f'hnh_{si}\n' + ''.join(f'        dta >{x}\n' for x in labs))
out.append(words('hrl', [f'hnl_{i}' for i in range(len(STATES))]))
out.append(words('hrh', [f'hnh_{i}' for i in range(len(STATES))]))
for cb in CBS:
    labs = []
    for c in [None] + CLASSES:
        name = L.eval(f'fnof("{c}","{cb}")') if c else None
        lab = f'h_{name}' if name else 'h_none'
        handlers.add(lab)
        labs.append(lab)
    out.append(words(f'cb_{cb}', labs))

# ---------------------------------------------------------------- classes
def cval(c, key, conv=lambda v: b(num(v))):
    return conv(rget(c, key)) if c else 0


def ctab(name, key, conv=lambda v: b(num(v)), clist=None):
    vals = [0] + [cval(c, key, conv) for c in CLASSES]
    return dta(name, vals, 20)


def ctab16(name, key, scale=256):
    vals = [0] + [int(round(num(rget(c, key)) * scale)) & 0xffff for c in CLASSES]
    return dta(name + '_lo', [v & 255 for v in vals], 20) + dta(name + '_hi', [v >> 8 for v in vals], 20)


for key in ['sm', 'en', 'qg', 'te', 's_', 'ht', 'bv', 'hw', 'ez', 'jv', 'ow', 'ro', 'nq', 'cj',
            'mh', 'li', 'rn', 'mj', 'qa', 'dq', 'll', 'bd', 'fm', 'ce', 'ix', 'oe', 'es', 'dg', 'om']:
    out.append(ctab(f'c_{key}', key))
out.append(ctab('c_ms', 'ms', lambda v: b(num(v))))
out.append(ctab('c_dy', 'dy', lambda v: b(num(v))))
out.append(ctab('c_mon', 'monster', lambda v: 1 if v not in (None, False) else 0))
out.append(ctab('c_d_', 'd_', lambda v: min(255, int(num(v, 10)))))
out.append(ctab('c_ml', 'ml', lambda v: frac(num(v, 1))))
out.append(ctab('c_ir', 'ir', lambda v: frac(num(v)) if num(v) else 0))
out.append(ctab('c_jw', 'jw', lambda v: int(round(num(v) * 256))))
out.append(ctab('c_mz', 'mz', lambda v: frac(num(v))))
out.append(ctab('c_cr', 'cr', lambda v: int(num(v, 0))))
out.append(ctab('c_cq', 'cq', lambda v: CID.get(v, 0) if v else 0))
out.append(ctab16('c_sw', 'sw'))
out.append(ctab16('c_bf', 'bf'))
out.append(ctab16('c_nk', 'nk'))
la = [0] + [int(num(rget(c, 'gv')) or num(rget(c, 'en'))) for c in CLASSES]
out.append(dta('c_la', la, 20))
grp = [0]
for c in CLASSES:
    g = 0
    for name, bit in GROUPS:
        if L.eval(f'ingroup("{c}","{name}")'):
            g |= bit
    grp.append(g)
out.append(dta('c_grp', grp, 20))
# explosion parameters: lu of lz/ia and the kx calls of mb, cm, cc
KX = [('lz', dict(s_=6, om=9, oe=12, kw=4.5, w=10)), ('ia', dict(s_=0, om=2, oe=8, kw=1.5, w=4)),
      ('mb', dict(om=17, s_=10, oe=12, kw=9, w=18)), ('cm', dict(om=0, s_=0, oe=7, kw=6, w=9)),
      ('cc', dict(om=10, s_=5, oe=8, kw=4, w=9))]
for c in ('lz', 'ia'):
    lu = L.eval(f'rget("{c}","lu")')
    assert dict(lu) == dict(KX[0 if c == 'lz' else 1][1]), (c, dict(lu))
for i, (n, _) in enumerate(KX):
    prm.append(f'KX_{n.upper()} = {i}')
out.append(dta('kx_s_', [k['s_'] for _, k in KX]))
out.append(dta('kx_om', [k['om'] for _, k in KX]))
out.append(dta('kx_oe', [k['oe'] for _, k in KX]))
out.append(dta('kx_kwf', [fx88(k['kw']) & 255 for _, k in KX]))
out.append(dta('kx_kwi', [fx88(k['kw']) >> 8 for _, k in KX]))
out.append(dta('kx_wf', [fx88(k['w']) & 255 for _, k in KX]))
out.append(dta('kx_wi', [fx88(k['w']) >> 8 for _, k in KX]))
lu = [0] + [{'lz': 0, 'ia': 1}.get(c, 0) for c in CLASSES]
out.append(dta('c_lu', lu, 20))

# ---------------------------------------------------------------- sprites
# et[class][state] -> layout (jy).  Layout bytes: jg, jk, number of clip
# entries, each (flag, x, y, w, h), number of overlays, each (n, dx, dy, w, h)
jys = []
jyidx = {}


def layout_bytes(jy):
    bs = [b(num(jy['jg'] if 'jg' in jy else None)), b(num(jy['jk'] if 'jk' in jy else None))]
    qe = jy['qe']
    qel = [qe[i] for i in range(1, len(qe) + 1)] if qe is not None else []
    bs.append(len(qel))
    for q in qel:
        if q is False or q is None:
            bs += [0, 0, 0, 0, 0]
        else:
            bs += [1, b(q[1]), b(q[2]), b(q[3]), b(q[4])]
    gi = jy['gi']
    gil = [gi[i] for i in range(1, len(gi) + 1)] if gi is not None else []
    bs.append(len(gil))
    for g in gil:
        bs += [b(g[1]), b(g[2]), b(g[3]), b(g[4]), b(g[5])]
    return bs


L.execute('''
function jyof(cls,st)
  local fd=et[cls]
  if not fd then return nil end
  local jy=fd[st] or fd.lw or lf
  while type(jy)=="string" do jy=fd[jy] end
  return jy
end
''')
spr_rows = {st: [] for st in STATES}
po_tab = [0]
rb_tab = [0]
mp_tab = [0]
for c in [None] + CLASSES:
    for s_ in STATES:
        jy = L.eval(f'jyof("{c}","{s_}")') if c else None
        if jy is None:
            spr_rows[s_].append(0)
            continue
        key = tuple(layout_bytes(jy))
        if key not in jyidx:
            jyidx[key] = len(jys)
            jys.append(key)
        spr_rows[s_].append(jyidx[key] + 1)
    if c:
        po_tab.append(num(L.eval(f'et["{c}"] and et["{c}"].po')))
        rb_tab.append(1 if L.eval(f'et["{c}"] and et["{c}"].rb') else 0)
        mp_tab.append({'capt': 1, 'frsp': 2}.get(c, 0))
for i, s_ in enumerate(STATES):
    out.append(dta(f'spr_{i}', spr_rows[s_], 20))
out.append(words('sprr', [f'spr_{i}' for i in range(len(STATES))]))
out.append(dta('c_po', po_tab, 20))
out.append(dta('c_rb', rb_tab, 20))
out.append(dta('c_mp', mp_tab, 20))
labs = ['jy_0'] + [f'jy_{i + 1}' for i in range(len(jys))]
out.append(words('jy', labs))
out.append('jy_0    dta 0,0,0,0')
for i, k in enumerate(jys):
    out.append(dta(f'jy_{i + 1}', list(k)))
# animation layouts jt: frame offsets 1..3, kz, cu, ff
jt = L.eval('jt')
rows = []
for i in range(1, 7):
    e = jt[i]
    rows.append([num(e[1]), num(e[2]), num(e[3]), num(e['kz']), num(e['cu']), num(e['ff'])])
for k, name in enumerate(['jt_f1', 'jt_f2', 'jt_f3', 'jt_kz', 'jt_cu', 'jt_ff']):
    out.append(dta(name, [0] + [r[k] for r in rows]))
# hitboxes
of = L.eval('of')
for k in ('x1', 'y1', 'x2', 'y2'):
    out.append(dta(f'of_{k}', [0] + [b(of[i][k]) for i in range(1, 16)]))
# walk cycles na
out.append(dta('na_1', [1, 2, 1, 3]))
out.append(dta('na_2', [1, 2]))
# go-tutorial / misc lists checked against the cart
assert [L.eval(f'na[1][{i}]') for i in range(1, 5)] == [1, 2, 1, 3]

# ---------------------------------------------------------------- palettes
def lua_tab(expr, n=16):
    t = L.eval(expr)
    return [int(t[i]) for i in range(1, n + 1)]


banks = [list(range(16))]
banks += [lua_tab(f'hf[{i}]') for i in range(1, 5)]
banks += [lua_tab(f'sz[{i}]') for i in range(1, 4)]
banks += [lua_tab(f'lg[{i}]') for i in range(1, 5)]
banks += [lua_tab(f'pg[{i}]') for i in range(1, 4)]
banks += [list(range(16))]
assert len(banks) == 16
prm += ['BK_HF = 0      ; hf level n -> bank n', 'BK_SZ = 4', 'BK_LG = 7', 'BK_PG = 11']
# index (k << 4) | n: sprites and images use banks 0..14, where nibble 3
# stands for PICO-8 colour 0 (3 is transparent in sprites); primitives use
# bank 15 with the final colour as the nibble (so colour 3 can be drawn)
idx_pico = []
for k in range(16):
    for n in range(16):
        pc = 0 if (n == 3 and k < 15) else n
        idx_pico.append(banks[k][pc])
scr_pico = [banks[k][c] for k in range(16) for c in range(16)]
hi.append(dta('idx_pico', idx_pico))
hi.append(dta('scr_pico', scr_pico))
bank_tab = scr_pico                            # bank_tab[k*16 + c]: PICO colour c in bank k
hi.append(dta('pal_r', [int(c[0]) for c in PAL]))
hi.append(dta('pal_g', [int(c[1]) for c in PAL]))
hi.append(dta('pal_b', [int(c[2]) for c in PAL]))
hk = lua_tab('hk[1]')
hi.append(dta('hk_tab', hk))
prm.append('bank_tab = scr_pico')
prm.append('idx_pc = idx_pico')

# ---------------------------------------------------------------- math tables
sin = [round(-math.sin(2 * math.pi * i / 256) * 256) & 0xffff for i in range(256)]
hi.append(dta('sin_lo', [v & 255 for v in sin]))
hi.append(dta('sin_hi', [v >> 8 for v in sin]))
maj, mnr, ln = [], [], []
for r in range(256):
    q = r / 256
    f = math.sqrt(1 + q * q)
    maj.append(round(256 / f))
    mnr.append(min(255, round(256 * q / f)))
    ln.append(min(255, round((f - 1) * 256)))
hi.append(dta('nrm_maj_lo', [v & 255 for v in maj]))
hi.append(dta('nrm_maj_hi', [v >> 8 for v in maj]))
hi.append(dta('nrm_min', mnr))
hi.append(dta('nrm_len', ln))
sq1 = []
for u in range(256):
    v = math.sqrt(max(0.0, 1 - (u / 256) ** 2))
    sq1.append(0 if v >= 1 else min(255, int(v * 256)))
hi.append(dta('sqrt1_tab', sq1))
sqrt_t = [min(255, round(math.sqrt(i) * 16)) for i in range(256)]     # 4.4
hi.append(dta('sqrt44', sqrt_t))

# ---------------------------------------------------------------- texts
GLIST = list(FONT.keys())
asc = []
for ch in range(128):
    c = chr(ch).lower()
    asc.append(GLIST.index(c) if c in FONT else GLIST.index(' '))
out.append(dta('asc_glyph', asc))
TEXTS = {}


def text(label, s):
    TEXTS[label] = s
    return label


def emit_texts():
    for lab, s in TEXTS.items():
        out.append(f"{lab} dta c'{s}',0" if "'" not in s else
                   f"{lab} dta {','.join(str(ord(ch)) for ch in s)},0")


text('t_press', 'press [z]to start')
text('t_cred1', 'gfx,code,design        @krajzeg')
text('t_cred2', 'music,sfx         @gruber_music')
text('t_diff', ' difficulty')
text('t_best', '       best')
text('t_the', 'the')
text('t_scomp', 'stage complete')
text('t_qcomp', 'quest complete')
text('t_far', 'this will be far enough.')
text('t_tut1', 'stab:          [z]')
text('t_tut2', 'shield:   hold [x]')
text('t_tut3', 'charge:   hold [z]')
text('t_tut4', 'dash:     2X arrow')
text('t_go', 'go!')
text('t_fight', 'fight!')
text('t_ffight', 'final fight!')
text('t_total', 'total score')
text('t_rank', 'rank')
text('t_perish', 'you perished')
text('t_hit', ' HIT')
text('t_slash', '/')
text('t_plus', '+')
text('t_zero', '0')
qd = L.eval('qd')
for i in range(1, 6):
    text(f't_dn{i}', qd[i]['le'])
nc = L.eval('nc')
for i in range(1, 4):
    text(f't_ik{i}', nc[i]['ik'])
    text(f't_le{i}', nc[i]['le'])
pc = L.eval('pc')
for i in range(1, 4):
    text(f't_pc{i}', pc[i]['q_'])
text('t_health', '+health')
text('t_strength', '+strength')
assert rget('sb', 'hh') == '+health' and rget('qf', 'hh') == '+strength'
out.append(words('t_dn', ['0'] + [f't_dn{i}' for i in range(1, 6)]))

# ---------------------------------------------------------------- difficulty
def qdv(i, k, d=0):
    return num(qd[i][k] if k in qd[i] else None, d)


for k in ('po', 'jn', 'mw', 'fc', 'nw'):
    vals = [0] + [fx88(qdv(i, k)) for i in range(1, 6)]
    out.append(dta(f'qd_{k}_lo', [v & 255 for v in vals]))
    out.append(dta(f'qd_{k}_hi', [v >> 8 for v in vals]))
for k in ('kg', 'p_', 'da', 'oz'):
    out.append(dta(f'qd_{k}', [0] + [int(qdv(i, k)) for i in range(1, 6)]))
for m in ('mini1', 'mini2'):
    labs = ['0']
    for i in range(1, 6):
        labs.append(text(f't_{m}_{i}', qd[i][m]))
    out.append(words(f'qd_{m}', labs))

# ---------------------------------------------------------------- waves
def cart_str(a):
    sh = 'abcdefghijklmnopqrstuvwxyz0123456789 ,="\n'
    s = ''
    while cart[a]:
        s += sh[cart[a] - 1]
        a += 1
    return s


def parse_lists(s):
    rows = []
    for line in s.split('\n')[:-1] if s.endswith('\n') else s.split('\n'):
        items = [x.strip().strip('"') for x in line.split(',') if x.strip()]
        rows.append(items)
    return rows


pi = L.eval('pi')
qp = L.eval('qp')
bk = L.eval('bk')
BK = {k: CID[v] for k, v in dict(bk).items()}
wave_rows = []
for i in range(1, len(pi) + 1):
    wave_rows.append([pi[i][j] for j in range(1, len(pi[i]) + 1)])
assert len(wave_rows) == 16, len(wave_rows)
labs = []
for i, row in enumerate(wave_rows):
    out.append(f'pi_{i + 1}  dta {len(row)}')
    for j, w in enumerate(row):
        lab = f'pis_{i + 1}_{j}'
        out.append(f'        dta a({lab})')
    for j, w in enumerate(row):
        out.append(f"pis_{i + 1}_{j} dta {','.join(str(BK[ch]) for ch in w) + (',' if w else '')}0")
    labs.append(f'pi_{i + 1}')
out.append(words('pi', ['0'] + labs))
labs = []
for i in range(1, len(qp) + 1):
    row = [qp[i][j] for j in range(1, len(qp[i]) + 1)]
    out.append(f'qp_{i}  dta {len(row)}')
    for j, w in enumerate(row):
        out.append(f'        dta a(qps_{i}_{j})')
    for j, w in enumerate(row):
        out.append(f"qps_{i}_{j} dta {','.join(str(BK[ch]) for ch in w)},0")
    labs.append(f'qp_{i}')
out.append(words('qp', ['0'] + labs))
# mini bosses as class strings
for m in ('mini1', 'mini2'):
    for i in range(1, 6):
        out.append(f"cs_{m}_{i} dta {','.join(str(BK[ch]) for ch in qd[i][m])},0")
    out.append(words(f'cs_{m}', ['0'] + [f'cs_{m}_{i}' for i in range(1, 6)]))
prm.append(f'BK_BOSS = {BK["x"]}')
prm.append(f'BK_CRST = {BK["y"]}')

# ---------------------------------------------------------------- stages
for k, d in (('fl', 0), ('cl', 0), ('bm', 0), ('ta', 0), ('bv', 2)):
    out.append(dta(f'nc_{k}', [0] + [int(num(nc[i][k] if k in nc[i] else None, d)) for i in range(1, 4)]))
out.append(dta('nc_rk', [0] + [frac(num(nc[i]['rk'])) for i in range(1, 4)]))
out.append(dta('nc_qy', [0] + [1 if 'qy' in nc[i] and nc[i]['qy'] else 0 for i in range(1, 4)]))
out.append(dta('nc_qh', [0] + [1 if 'qh' in nc[i] and nc[i]['qh'] else 0 for i in range(1, 4)]))
out.append(words('nc_ik', ['0'] + [f't_ik{i}' for i in range(1, 4)]))
out.append(words('nc_le', ['0'] + [f't_le{i}' for i in range(1, 4)]))
# map layers: speed (8.8), y, map column, map row, rows
layers = []
for i in range(1, 4):
    lj = nc[i]['lj']
    for j in range(1, len(lj) + 1):
        l = lj[j]
        layers.append((i, num(l[1]), int(l[2]), int(l[3]), int(l[4]), int(l[5])))
prm.append(f'NLAYER = {len(layers)}')
out.append(dta('ly_stage', [l[0] for l in layers]))
out.append(dta('ly_spd_lo', [fx88(l[1]) & 255 for l in layers]))
out.append(dta('ly_spd_hi', [fx88(l[1]) >> 8 for l in layers]))
out.append(dta('ly_y', [l[2] for l in layers]))
out.append(dta('ly_col', [l[3] for l in layers]))
out.append(dta('ly_row', [l[4] for l in layers]))
out.append(dta('ly_h', [l[5] for l in layers]))
# VRAM strips of the layers (stride 1024), from $50000 per stage
STRIP0 = 0x50000
ly_vr = []
cur = {}
for (st, spd, y, col, row, h) in layers:
    a = cur.get(st, STRIP0)
    ly_vr.append(a)
    cur[st] = a + h * 8 * 1024
    assert cur[st] <= 0x80000
out.append(dta('ly_vr1', [(a >> 8) & 255 for a in ly_vr]))
out.append(dta('ly_vr2', [a >> 16 for a in ly_vr]))
# results table pc: base (ju), linear (hv), quadratic (ea), cap (ng)
for k in ('ju', 'hv', 'ng'):
    vals = [int(num(pc[i][k])) & 0xffff for i in range(1, 4)]
    out.append(dta(f'pc_{k}_lo', [v & 255 for v in vals]))
    out.append(dta(f'pc_{k}_hi', [v >> 8 for v in vals]))
out.append(dta('pc_ea', [fx88(num(pc[i]['ea'])) & 255 for i in range(1, 4)]))
out.append(dta('pc_eah', [fx88(num(pc[i]['ea'])) >> 8 for i in range(1, 4)]))
mt = L.eval('mt')
mtv = [int(mt[i]) & 0xffff for i in range(1, 6)]
out.append(dta('mt_lo', [v & 255 for v in mtv]))
out.append(dta('mt_hi', [v >> 8 for v in mtv]))
# sfx priorities: qz[n + 2] for sfx n (index 0: nothing playing)
qz = L.eval('qz')
out.append(dta('qz', [int(qz[i]) for i in range(1, len(qz) + 1)]))
# reflection: noise per row = peek(y + 0x29ee) % 26 / 26 for y = 1..17
mu = [(cart[0x29ee + y] % 26) / 26 for y in range(1, 18)]
# phase speed per frame in 1/65536 turns: t*(0.008+0.0037*mu) with t += 0.5
out.append(dta('jl_spd_lo', [int(round((0.008 + 0.0037 * m) * 0.5 * 65536)) & 255 for m in mu]))
out.append(dta('jl_spd_hi', [int(round((0.008 + 0.0037 * m) * 0.5 * 65536)) >> 8 for m in mu]))
out.append(dta('jl_ph0_lo', [int(round(m * 65536)) & 255 for m in mu]))
out.append(dta('jl_ph0_hi', [int(round(m * 65536)) >> 8 for m in mu]))
out.append(dta('jl_amp', [int(round((1 - y * 0.055) * 256)) for y in range(1, 18)]))
# sprite flags
out.append(dta('spr_flags', list(cart[0x3000:0x3100])))

# ---------------------------------------------------------------- VRAM images
vr = {}            # address -> bytes


def sheet_px(x, y):
    v = cart[y * 64 + x // 2]
    return v >> 4 if x & 1 else v & 15


def stored(c):
    return 0 if c == 3 else (0xf3 if c == 0 else 0xf0 | c)


# font masks at $0c000: glyph g at g*4, stride 512, rows 0..5
font = bytearray(0x2000)
for g, ch in enumerate(GLIST):
    for y, row in enumerate(GLYPHS[ch]):
        for x, p in enumerate(row):
            if p == '#':
                font[y * 512 + g * 4 + x] = 0xff


def xdl(base):
    o = bytearray([0x24, 0x08, 23, 0x10, 0xff])   # OVOFF|RPTL, ATT narrow
    for r in range(128):
        addr = base + r * 128
        if r % 2 == 0:
            o += bytes([0x62, 0x20, 1])
        else:
            o += bytes([0x42, 0x20 | (0x80 if r == 127 else 0)])
        o += bytes([addr & 255, (addr >> 8) & 255, addr >> 16, 0, 0])
    return o


for i, base in enumerate((0x00000, 0x04000, 0x08000)):
    x = xdl(base)
    font[0x1000 + i * 0x400:0x1000 + i * 0x400 + len(x)] = x
vr[0x0c000] = bytes(font)

# reflection rows at $1c000: row i shows the cart's four nested spans for
# a half width of i/2 pixels, centred on column 48 (stride 128)
HN = [(1.0, 1), (0.6, 5), (0.35, 13), (0.2, 15)]
refl = bytearray(97 * 128)
for i in range(97):
    w = i / 2
    for sw, col in HN:
        a = w * sw
        x0, x1 = -math.ceil(a - 1e-9), math.floor(a + 1e-9)
        for x in range(x0, x1 + 1):
            if 0 <= 48 + x < 97:
                refl[i * 128 + 48 + x] = stored(col)
vr[0x1c000] = bytes(refl)


def circfill(img, stride, cx, cy, r, c):
    # PICO-8 style circle spans (as tools/pico_ref.py)
    x, y = r, 0
    d = 1 - r
    pts = []
    while x >= y:
        pts.append((x, y))
        y += 1
        if d < 0:
            d += 2 * y + 1
        else:
            x -= 1
            d += 2 * (y - x) + 1
    for px, py in pts:
        for (a, bb) in ((px, py), (py, px)):
            for yy in (cy - bb, cy + bb):
                for xx in range(cx - a, cx + a + 1):
                    img[yy * stride + xx] = c


def moon(r):
    size = 2 * (r + 4) + 3
    img = bytearray(size * 128)
    c = r + 5
    circfill(img, 128, c, c, r + 4, stored(0))
    circfill(img, 128, c - 1, c, r, stored(15))
    circfill(img, 128, c + 1, c, r, stored(15))
    circfill(img, 128, c, c - 1, r - 1, stored(7))
    return img, c


MISC = 0x40000
m1, c1 = moon(25)
m2, c2 = moon(17)
prm.append(f'MOON1_C = {c1}\nMOON1_S = {len(m1) // 128}\nMOON2_C = {c2}\nMOON2_S = {len(m2) // 128}')
vr[MISC] = bytes(m1)
vr[MISC + 0x2000] = bytes(m2)
# shadows (masks $ff): is(x-1, y, rx, 2.97, 2rx+2, 0) for rx = 3, 7, 11, 15 and
# the projectile shadow is(x, y, 4, 1.2, 4)


def ell_rows(rx, ry, w):
    rowsd = []
    dx = rx
    dy = 0
    while dy <= ry:
        while dx * dx / rx / rx + dy * dy / ry / ry > 1:
            dx -= 1
        k = min(dx, w)
        rowsd.append((dy, dx, k))
        dy += 1
    return rowsd


shad = bytearray(6 * 8 * 64)
SH = []
for n, (rx, ry, w) in enumerate(((3, 2.97, 6), (7, 2.97, 14), (11, 2.97, 22), (15, 2.97, 30),
                                 (4, 1.2, 4))):
    base = n * 8 * 64
    for dy, dx, k in ell_rows(rx, ry, w):
        for my in (-1, 1):
            yy = 3 + my * dy
            for mx in (-1, 1):
                xa, xb = sorted((mx * dx, mx * (dx - k)))
                for xx in range(math.floor(xa), math.floor(xb) + 1):
                    shad[base + yy * 64 + 16 + xx] = 0xff
    SH.append(base)
# puddles (gt on the floor): rows 40..41 (fg 11, bg 3) and 44..45 (fg 3, bg 1),
# bank 15 bytes (colour 3 is drawn), 5 wide
for v, (fg, bg) in enumerate(((11, 3), (3, 1))):
    r = 40 + v * 4
    for x in range(5):
        shad[r * 64 + x] = 0xf0 | (fg if 1 <= x <= 3 else bg)
        shad[(r + 1) * 64 + x] = 0xf0 | bg
vr[MISC + 0x3800] = bytes(shad)
prm.append('SHADOW = $43800    ; 5 masks (stride 64), 8 rows apart, centre column 16, row 3')
# outlined font at $44800: glyph g outline mask at g*8 (stride 512, 7 rows),
# offset (-1,-1) from the glyph
ofont = bytearray(512 * 8)
OFF = [(1, 0), (1, 1), (0, 1), (-1, 1), (-1, 0), (0, -1)]
for g, ch in enumerate(GLIST[:64]):
    for y, row in enumerate(GLYPHS[ch]):
        for x, p in enumerate(row):
            if p == '#':
                for ox, oy in OFF:
                    ofont[(y + 1 + oy) * 512 + g * 8 + x + 1 + ox] = 0xff
assert len(GLIST) <= 64
vr[MISC + 0x4800] = bytes(ofont)

# floor strips at $46000 + stage*$2000 (stride 256): the cart's ki() rows
# drawn with segments starting at floor(k*dx), width floor(dx+1), sampled
# as sspr does.  floor_off[stage][row][ovq]: source column for ov = ovq/2.
FLOOR = 0x46000
off_rows = []
fl_info = []
for st in range(1, 4):
    fl = int(nc[st]['fl'])
    cl = int(num(nc[st]['cl'] if 'cl' in nc[st] else None))
    img = bytearray(32 * 256)
    rows_spec = [(fl, 24, 1, 80)] + ([(cl, 6, -1, 37)] if cl else [])
    r_i = 0
    info = []
    for (qs, h, pp, y0) in rows_spec:
        for oy in range(h):
            ka = 1 + oy / h
            dx = 16 * ka
            W = math.floor(dx + 1)
            row = [0] * 256
            k = 0
            while math.floor(k * dx) < 256:
                X = math.floor(k * dx)
                for i in range(W):
                    if X + i < 256:
                        row[X + i] = stored(sheet_px((i * 16) // W, qs + oy))
                k += 1
            img[r_i * 256:(r_i + 1) * 256] = bytes(row)
            offs = []
            for ovq in range(32):
                ov = ovq / 2
                sx0 = 64 - ka * (80 - ov)
                o = (-sx0) % dx
                offs.append(int(math.floor(o)))
            off_rows.append(offs)
            info.append((y0 + pp * oy))
            r_i += 1
    vr[FLOOR + (st - 1) * 0x2000] = bytes(img)
    fl_info.append(info)
    out.append(dta(f'fl_y_{st}', info))
out.append(words('fl_y', ['0'] + [f'fl_y_{i}' for i in (1, 2, 3)]))
out.append(dta('fl_n', [0] + [len(i) for i in fl_info]))
flat = [v for r in off_rows for v in r]
vr[0x4e000] = bytes(flat)          # copied to RAM (fl_buf) when a stage starts
first = [0]
acc = 0
for i in fl_info:
    first.append(acc)
    acc += len(i)
out.append(dta('fl_first', first))
# the map rows at $4c000 (128x32)
vr[0x4c000] = bytes(cart[0x2000:0x3000])

# ---------------------------------------------------------------- sound
sfxd = bytearray()
for sid in range(64):
    base = 0x3200 + sid * 68
    for n in range(32):
        lo_, hi2 = cart[base + n * 2], cart[base + n * 2 + 1]
        pitch = lo_ & 0x3f
        wave = ((lo_ >> 6) & 3) | ((hi2 & 1) << 2)
        vol = (hi2 >> 1) & 7
        eff = (hi2 >> 4) & 7
        sfxd += bytes([pitch | (0x40 if wave == 6 else 0), vol | (eff << 4)])
    sfxd += bytes([max(1, cart[base + 65]), cart[base + 66], cart[base + 67], 0])
hi.insert(0, 'SFXDATA\n' + dta('', list(sfxd)).split('\n', 1)[1])
hi.insert(1, 'MUSDATA\n' + dta('', list(cart[0x3100:0x3200])).split('\n', 1)[1])
out.append('sfx_lo\n' + ''.join(f'        dta <(SFXDATA+{i * 68})\n' for i in range(64)))
out.append('sfx_hi\n' + ''.join(f'        dta >(SFXDATA+{i * 68})\n' for i in range(64)))
audf = []
for p in range(64):
    f = 65.406 * 2 ** (p / 12)
    while 63921 / (2 * f) - 1 > 255:
        f *= 2
    audf.append(max(1, min(255, round(63921 / (2 * f) - 1))))
hi.append(dta('pitch_audf', audf))

# ---------------------------------------------------------------- write
emit_texts()
(HERE / 'gen' / 'tables.asm').write_text('; generated by tools/make_data.py - do not edit\n' +
                                          '\n'.join(out) + '\n')
(HERE / 'gen' / 'hi.asm').write_text('; generated by tools/make_data.py - do not edit\n' +
                                      'HI_START\n' + '\n'.join(hi) + 'HI_END\n')
(HERE / 'gen' / 'params.asm').write_text('\n'.join(prm) + '\n')
(HERE / 'data' / 'gfx.bin').write_bytes(cart[:0x2000])
load = ['; generated by tools/make_data.py - do not edit',
        '; VRAM images: each 8K piece is loaded at $a000 and copied by stage_vr']
for addr in sorted(vr):
    data = vr[addr]
    for o in range(0, len(data), 0x2000):
        piece = data[o:o + 0x2000]
        name = f'vr_{addr + o:05x}.bin'
        (HERE / 'data' / name).write_bytes(piece)
        a = addr + o
        pages = (len(piece) + 255) // 256
        load += [f'        org stage_arg', f'        dta {a >> 12},{(a >> 8) & 15},{pages}',
                 f'        org $a000', f"        ins 'data/{name}'", '        ini stage_vr']
(HERE / 'gen' / 'load.asm').write_text('\n'.join(load) + '\n')
missing = sorted(handlers)
(HERE / 'gen' / 'handlers.txt').write_text('\n'.join(missing) + '\n')
print(f'{len(CLASSES)} classes, {len(jys)} sprite layouts, {len(handlers)} handlers, '
      f'{len(vr)} VRAM images, hi tables {sum(1 for _ in hi)} blocks')
