; Generated by generate_assets.js from player.png
        dta 16,255,255,255      ; hero unused by the two-colour art
        dta 17,255,255,255      ; hero body
        dta 18,255,255,255      ; hero body
        dta 20,255,0,0      ; hero hair
