(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.SulkaFormat = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  const WIDTH = 24;
  const HEIGHT = 14;
  const LEVEL_COUNT = 24;
  const ALLOWED = ".#PKDdN^v><s=F";
  const BEGIN_MARKER = "; BEGIN SULKA EDITOR LEVEL DATA";
  const END_MARKER = "; END SULKA EDITOR LEVEL DATA";

  function cloneLevels(levels) {
    return levels.map((level) => ({
      name: level.name,
      note: level.note || "",
      rows: level.rows.slice(),
      flies: (level.flies || []).map((fly) => ({ endX: fly.endX, endY: fly.endY }))
    }));
  }

  function flyStarts(level) {
    const starts = [];
    level.rows.forEach((row, y) => {
      [...row].forEach((tile, x) => {
        if (tile === "F") starts.push({ x: x * 10, y: y * 10 });
      });
    });
    return starts;
  }

  function validateLevels(levels) {
    const errors = [];
    const warnings = [];
    if (!Array.isArray(levels) || levels.length !== LEVEL_COUNT) {
      errors.push(`Expected exactly ${LEVEL_COUNT} level slots; found ${Array.isArray(levels) ? levels.length : 0}.`);
      return { errors, warnings };
    }

    levels.forEach((level, index) => {
      const label = `Level ${index + 1} (${level.name || "unnamed"})`;
      if (!Array.isArray(level.rows) || level.rows.length !== HEIGHT) {
        errors.push(`${label} must contain ${HEIGHT} rows.`);
        return;
      }
      level.rows.forEach((row, y) => {
        if (row.length !== WIDTH) errors.push(`${label}, row ${y + 1} is ${row.length} cells wide (expected ${WIDTH}).`);
        for (const tile of row) {
          if (!ALLOWED.includes(tile)) errors.push(`${label} contains unsupported tile ${JSON.stringify(tile)}.`);
        }
      });
      const flat = level.rows.join("");
      const players = [...flat].filter((tile) => tile === "P").length;
      const flyCount = flyStarts(level).length;
      if (index !== 12 && players !== 1) warnings.push(`${label} has ${players} player starts; the game uses the last one scanned.`);
      if (index === 12 && flat !== ".".repeat(WIDTH * HEIGHT)) warnings.push(`${label} is skipped by init_level in the current VBXE code.`);
      if (flyCount > 2) errors.push(`${label} has ${flyCount} fly-spikes; the VBXE runtime supports at most 2.`);
      if ((level.flies || []).length !== flyCount) errors.push(`${label} has ${flyCount} F tiles but ${(level.flies || []).length} path records.`);
      level.rows.forEach((row, y) => {
        for (const spike of "^vs") {
          let runLength = 0;
          for (let x = 0; x <= row.length; x += 1) {
            if (row[x] === spike) runLength += 1;
            else {
              if (runLength % 2 !== 0) warnings.push(`${label}, row ${y + 1} contains an unpaired ${spike} spike cell.`);
              runLength = 0;
            }
          }
        }
      });
      (level.flies || []).forEach((fly, flyIndex) => {
        for (const [axis, value, max] of [["X", fly.endX, 230], ["Y", fly.endY, 130]]) {
          if (!Number.isInteger(value) || value < 0 || value > max) {
            errors.push(`${label}, fly ${flyIndex + 1} endpoint ${axis} must be an integer from 0 to ${max}.`);
          }
        }
      });
      if (index === LEVEL_COUNT - 1 && !flat.includes("N")) warnings.push(`${label} has no nest; the final-level completion trigger is missing.`);
    });
    return { errors: [...new Set(errors)], warnings: [...new Set(warnings)] };
  }

  function pointerRows(prefix) {
    const rows = [];
    for (let start = 1; start <= LEVEL_COUNT; start += 8) {
      rows.push(" dta " + Array.from({ length: Math.min(8, LEVEL_COUNT - start + 1) }, (_, offset) => `${prefix}level${start + offset}`).join(","));
    }
    return rows;
  }

  function exportAssembly(levels) {
    const validation = validateLevels(levels);
    if (validation.errors.length) throw new Error(validation.errors.join("\n"));
    const lines = [
      BEGIN_MARKER,
      "; Generated by the Sulka VBXE Map Editor. Replace the marked block in",
      "; atari/sulka-vbxe.asm, then assemble normally with MADS.",
      "levels_lo",
      ...pointerRows("<"),
      "levels_hi",
      ...pointerRows(">"),
      "",
      "fly_config_lo",
      ...pointerRows("<fly_"),
      "fly_config_hi",
      ...pointerRows(">fly_"),
      "",
      "; count, then start-x/start-y/end-x/end-y in local board pixels."
    ];

    levels.forEach((level, index) => {
      const starts = flyStarts(level);
      const values = [starts.length];
      starts.forEach((start, flyIndex) => {
        const endpoint = level.flies[flyIndex];
        values.push(start.x, start.y, endpoint.endX, endpoint.endY);
      });
      lines.push(`fly_level${index + 1} dta ${values.join(",")}`);
    });

    lines.push("", "; 24 x 14 VBXE tile maps. One cell is one 10 x 10 VBXE tile.");
    levels.forEach((level, index) => {
      lines.push("", `level${index + 1}`, ` ; ${level.name}${level.note ? ` -- ${level.note}` : ""}`);
      level.rows.forEach((row) => lines.push(` dta c'${row}'`));
    });
    lines.push("", END_MARKER, "");
    return lines.join("\n");
  }

  function exportJson(levels) {
    return JSON.stringify({ format: "sulka-vbxe-levels", version: 1, width: WIDTH, height: HEIGHT, levels }, null, 2) + "\n";
  }

  function exportJavaScript(levels) {
    const validation = validateLevels(levels);
    if (validation.errors.length) throw new Error(validation.errors.join("\n"));
    const rows = levels.map((level) => `    ${JSON.stringify(level)}`);
    return [
      "(function (root, factory) {",
      "  const data = factory();",
      "  if (typeof module === \"object\" && module.exports) module.exports = data;",
      "  else root.SULKA_VBXE_LEVELS = data;",
      "})(typeof globalThis !== \"undefined\" ? globalThis : this, function () {",
      "  \"use strict\";",
      "",
      "  // Generated from the level block applied to atari/sulka-vbxe.asm.",
      "  return [",
      rows.join(",\n"),
      "  ];",
      "});",
      ""
    ].join("\n");
  }

  function levelsSignature(levels) {
    const text = JSON.stringify(cloneLevels(levels));
    let hash = 0x811c9dc5;
    for (let index = 0; index < text.length; index += 1) {
      hash ^= text.charCodeAt(index);
      hash = Math.imul(hash, 0x01000193);
    }
    return (hash >>> 0).toString(16).padStart(8, "0");
  }

  function parseJson(text) {
    const parsed = JSON.parse(text);
    const levels = Array.isArray(parsed) ? parsed : parsed.levels;
    if (!Array.isArray(levels)) throw new Error("JSON does not contain a levels array.");
    return cloneLevels(levels);
  }

  function parseAssembly(text) {
    const levels = [];
    const levelPattern = /^level(\d+)\s*\r?\n\s*;\s*([^\r\n]*)\r?\n((?:\s*dta\s+c'[^']*'\s*\r?\n?){14})/gm;
    let match;
    while ((match = levelPattern.exec(text))) {
      const number = Number(match[1]);
      if (number < 1 || number > LEVEL_COUNT) continue;
      const rows = [...match[3].matchAll(/dta\s+c'([^']*)'/g)].map((rowMatch) => rowMatch[1]);
      const commentParts = match[2].split(/\s+--\s+/, 2);
      levels[number - 1] = { name: commentParts[0].trim(), note: commentParts[1] || "", rows, flies: [] };
    }
    if (levels.filter(Boolean).length !== LEVEL_COUNT) throw new Error(`Assembly contains ${levels.filter(Boolean).length} recognizable maps; expected ${LEVEL_COUNT}.`);

    const pointerSection = text.match(/^fly_config_lo\s*\r?\n([\s\S]*?)^fly_config_hi/m);
    const pointerLabels = pointerSection ? [...pointerSection[1].matchAll(/<([A-Za-z_][A-Za-z0-9_]*)/g)].map((item) => item[1]) : [];
    levels.forEach((level, index) => {
      const label = pointerLabels[index] || `fly_level${index + 1}`;
      const flyMatch = text.match(new RegExp(`^${label}\\s+dta\\s+([^;\\r\\n]+)`, "m"));
      const starts = flyStarts(level);
      if (!flyMatch) {
        level.flies = starts.map((start) => ({ endX: start.x, endY: start.y }));
        return;
      }
      const values = flyMatch[1].split(",").map((value) => Number(value.trim()));
      const count = values[0];
      level.flies = [];
      for (let flyIndex = 0; flyIndex < count; flyIndex += 1) {
        level.flies.push({ endX: values[flyIndex * 4 + 3], endY: values[flyIndex * 4 + 4] });
      }
    });
    return levels;
  }

  return {
    WIDTH, HEIGHT, LEVEL_COUNT, ALLOWED, BEGIN_MARKER, END_MARKER,
    cloneLevels, flyStarts, validateLevels, exportAssembly, exportJson, exportJavaScript,
    levelsSignature, parseJson, parseAssembly
  };
});
