#!/usr/bin/env python3
"""Convert the Curse of the Lich King cartridge into data for the VBXE port.

Reads ../pico/cart.bin (written by tools/convert_cart.py) and writes:

  data/gfx.bin     8192 bytes  sprite sheet, 4 bpp (low nibble = left pixel)
  data/stage.bin              font masks and both XDLs (VRAM $0C000)
  data/sfx.bin                sound effects (see src/sound.asm)
  gen/tables.asm              game tables, palettes, glyph widths
  gen/strings.asm             every text of the game as glyph strings

Text is stored as glyph numbers (the cart's own proportional font, in
the order of its fdat string), one byte per glyph, terminated by $ff.
"""
from pathlib import Path
import math
import re

HERE = Path(__file__).resolve().parent.parent
cart = (HERE / 'pico' / 'cart.bin').read_bytes()
lua = (HERE / 'pico' / 'lich.lua').read_bytes().decode('latin-1')
(HERE / 'data').mkdir(exist_ok=True)
(HERE / 'gen').mkdir(exist_ok=True)


def dta(name, values, width=16):
    lines = [f'{name}']
    for i in range(0, len(values), width):
        lines.append('        dta ' + ','.join(str(v & 255) for v in values[i:i + width]))
    return '\n'.join(lines) + '\n'


def explodeval(s):
    return [int(v) for v in s.split(',')]


# ---------------------------------------------------------------- font
fdat = re.search(r'fdat=.*?\[\[(.*?)\]\]', lua, re.S).group(1)
GLYPHS = []          # (key, pixels[18], width)
for i in range(0, len(fdat) // 11 + 1):
    chunk = fdat[i * 11:i * 11 + 11]
    if len(chunk) < 11:
        break
    key, hexv = chunk[:2], chunk[2:].replace('.', '')
    v = int(hexv, 16)
    k = 4
    v >>= 1
    if v & 1:
        k -= 1
    v >>= 1
    if v & 1:
        k -= 2
    px = []
    for _ in range(18):
        v >>= 1
        px.append(v & 1)
    GLYPHS.append((key, px, k))
GIDX = {key: i for i, (key, _, _) in enumerate(GLYPHS)}
assert len(GLYPHS) < 128


def enc(s):
    """PICO text (with ^ escapes) -> glyph bytes."""
    out = []
    i = 0
    while i < len(s):
        ch = s[i]
        if ch == '^':
            key = s[i:i + 2]
            i += 1
        else:
            key = ch + ' '
        out.append(GIDX[key])
        i += 1
    return out


def width(s):
    return sum(GLYPHS[g][2] for g in enc(s))


# ---------------------------------------------------------------- graphics
(HERE / 'data' / 'gfx.bin').write_bytes(cart[0:0x2000])


def sget(x, y):
    b = cart[y * 64 + x // 2]
    return b >> 4 if x & 1 else b & 15


stage = bytearray(0x1000)       # VRAM $0C000: font masks, glyph g at g*4, stride 512
for g, (key, px, k) in enumerate(GLYPHS):
    for y in range(6):
        for x in range(3):
            if px[y * 3 + x]:
                stage[y * 512 + g * 4 + x] = 0xff


# XDL: 24 blank lines, then 128 rows in LR/narrow mode.  Even rows are
# shown on two TV lines and odd rows on one (192 lines in total).
def xdl(base):
    out = bytearray([0x24, 0x08, 23, 0x10, 0xff])   # OVOFF|RPTL, ATT narrow
    for r in range(128):
        addr = base + r * 128
        last = r == 127
        if r % 2 == 0:
            out += bytes([0x62, 0x20, 1])           # GMON|RPTL|OVADR, LR
        else:
            out += bytes([0x42, 0x20 | (0x80 if last else 0)])
        out += bytes([addr & 255, (addr >> 8) & 255, addr >> 16, 0, 0])
    return out


for base in (0x00000, 0x04000, 0x30000):    # three framebuffers
    x = xdl(base)
    assert len(x) <= 0x400
    stage += x + bytes(0x400 - len(x))
(HERE / 'data' / 'stage.bin').write_bytes(stage)     # VRAM $0C000..$0DBFF

# ---------------------------------------------------------------- tables
out = ['; generated by tools/make_data.py - do not edit\n']
out.append(dta('tile_flags', list(cart[0x3000:0x3100])))

# entity tables (index 1..25, entry 0 unused)
m = re.search(r'm_name, m_anim.*?= explode\("(.*?)"\),(.*)', lua)
names = m.group(1).split(',')
vals = re.findall(r'explodeval\("([^"]*)"\)', m.group(2))
cols = ['m_anim', 'm_col', 'm_prop', 'm_hp', 'm_atk', 'm_range', 'm_sight', 'm_depth', 'm_itemchance']
M = {c: [0] + explodeval(v) for c, v in zip(cols, vals)}
for c in cols:
    out.append(dta(c, M[c]))
# hasitem = chance(itemchance/10): 16-bit thresholds (0 = never, $ffff+ = always)
out.append(dta('m_item_lo', [min(65535, round(v / 10 * 65536)) & 255 for v in M['m_itemchance']]))
out.append(dta('m_item_hi', [min(65535, round(v / 10 * 65536)) >> 8 for v in M['m_itemchance']]))
# sprite -> entity id (for make_entities), 0 = none
anim_id = [0] * 256
for i in range(25, 0, -1):          # indexof returns the first match
    anim_id[M['m_anim'][i]] = i
out.append(dta('anim_id', anim_id))

m = re.search(r'i_name, i_type.*?= explode\("(.*?)"\),(.*)', lua)
inames = m.group(1).split(',')
ivals = re.findall(r'explodeval\("([^"]*)"\)', m.group(2))
icols = ['i_type', 'i_spr', 'i_atk', 'i_heal', 'i_hpmax', 'i_depth']
I = {c: [0] + explodeval(v) for c, v in zip(icols, ivals)}
for c in icols:
    out.append(dta(c, I[c]))

# flr(atk*0.7) with PICO-8's 16.16 constant 0.7 = $0.b333
out.append(dta('mul07', [(a * 0xb333) >> 16 for a in range(64)]))
# xp_req(lvl), 16 bit
xr = []
for lvl in range(64):
    xr.append(min(65535, sum((i + 1) ** 2 - 4 for i in range(1, lvl + 1))))
out.append(dta('xpreq_lo', [v & 255 for v in xr]))
out.append(dta('xpreq_hi', [v >> 8 for v in xr]))

# map pieces: sget(p*3+x, 64+y), 28 pieces of 3x3 (x-major like the loop)
pieces = []
for p in range(30):
    for x in range(3):
        for y in range(3):
            pieces.append(sget(p * 3 + x, 64 + y))
out.append(dta('pieces', pieces, 9))

# title background: map(112,0) tiles
title_map = [cart[0x2000 + y * 128 + 112 + x] for y in range(16) for x in range(16)]
out.append(dta('title_map', title_map))

# palettes
dpal = explodeval("0,0,1,5,1,1,13,6,4,4,9,3,13,5,1,1")
lpal = explodeval("1,5,4,11,9,13,7,7,14,10,7,7,7,6,15,7")
fade = explodeval("0,0,1,5,1,1,13,6,4,4,9,3,13,5,4,4")
lit = list(range(16))
lit[14] = 1
# sheet variants: pixel 0 stays transparent; colours mapped to 0 become 16
sheet_maps = []
for p in (list(range(16)), lit, dpal, lpal):
    sheet_maps += [0] + [c if c else 16 for c in p[1:]]
out.append(dta('sheet_maps', sheet_maps))
# fade: colour after k steps, k = 0..6
fk = []
for k in range(7):
    for c in range(16):
        v = c
        for _ in range(k):
            v = fade[v]
        fk.append(v)
out.append(dta('fade_tab', fk))
PAL = [(0, 0, 0), (29, 43, 83), (126, 37, 83), (0, 135, 81), (171, 82, 54),
       (95, 87, 79), (194, 195, 199), (255, 241, 232), (255, 0, 77),
       (255, 163, 0), (255, 255, 39), (0, 231, 88), (41, 173, 255),
       (131, 118, 156), (255, 119, 168), (255, 204, 170), (0, 0, 0)]
out.append(dta('pal_r', [p[0] for p in PAL]))
out.append(dta('pal_g', [p[1] for p in PAL]))
out.append(dta('pal_b', [p[2] for p in PAL]))

# capital letter glyph for a lowercase one ("^"..name)
cap = list(range(128))
for g, (key, _, _) in enumerate(GLYPHS):
    if key[1] == ' ' and key[0].isalpha() and ('^' + key[0]) in GIDX:
        cap[g] = GIDX['^' + key[0]]
out.append(dta('cap_glyph', cap))

# glyph widths (kerning)
out.append(dta('glyph_k', [k for _, _, k in GLYPHS] + [4] * (128 - len(GLYPHS))))


# PICO-8 sin (inverted, 1 turn = 256 steps) in 8.8
def psin(t):
    return -math.sin(2 * math.pi * t)


s88 = [int(math.floor(psin(i / 256) * 256 + 0.5)) for i in range(256)]
out.append(dta('sin_lo', [v & 255 for v in s88]))
out.append(dta('sin_hi', [(v >> 8) & 255 for v in s88]))
# inventory-full bob: flr(6+sin(t)+1) for t = 0..29 ticks (one second)
out.append(dta('bob_tab', [int(math.floor(7 + psin(t / 30))) for t in range(30)]))

# glyph constants for code that builds text
consts = {
    'G_SPACE': ' ', 'G_0': '0', 'G_PLUS': '+', 'G_MINUS': '-', 'G_SLASH': '/',
    'G_LPAR': '(', 'G_RPAR': ')', 'G_DOT': '.', 'G_QUEST': '?', 'G_EXCL': '!',
}
for k, v in consts.items():
    out.insert(1, f'{k} = {GIDX[v + " "]}')

# ---------------------------------------------------------------- strings
S = {}           # label -> text
L = {}           # label -> list of texts (window lines)

for i, n in enumerate(names):
    S[f'mn_{i + 1}'] = n
for i, n in enumerate(inames):
    S[f'itn_{i + 1}'] = n
S.update(tr_1='', tr_2='cursed ', tr_3='holy ',
         st_1='', st_2=' of blight', st_3=' of confusion', st_4=' of the basilisk', st_5=' of the leech')


def modal(label, text, sep=','):
    L[label] = text.split(sep)


modal('ml_intro', "^chills run down your spine as,you enter the ^lich ^king's lair.,,^you have travelled light but,hopefully you will find more,supplies hidden down here.,,^rumor has it ^raq'zul resides on,the 8th floor. ^descend his lair,and destroy him!")
modal('ml_anvil', "^a mighty anvil...,,^spend a turn on this,hefty piece to bestow,a wepaon with special,powers - if you have,the right items.")
modal('ml_well', "^a shallow pool...,,^the strangely clear water,has the power to free,a weapon from its curse.,^it only costs a turn")
modal('ml_altar', "^a holy altar...,,^the book on the table has,the answers you need.,^spend a turn here to,identify a mysterious item.")
modal('ml_win', "^as the ^lich king lets out a final;scream, something shifts in the;air. ^you feel lighter, as if an;invisible burden has lifted.;;^raq'zul is defeated and you;return to the surface knowing;that the world has become;a better place.", ';')
story = ("  ^to become immortal, the lich\n king ^raq'zul casts a powerful\n   spell. ^draining the world\n     of life and happiness.\n\n"
         "  ^brave souls descend into his\n     lair, but none return.\n\n  ^now it is your turn. ^defeat\n ^raq'zul, break the curse, and\n       end the suffering!")
L['ml_story'] = story.split('\n')
L['ml_submenu'] = ['use', 'discard']

S.update(
    s_embark='(*) ^embark',
    s_credit1='^created by @^johan^peitz',
    s_credit2='^audio by @^gruber_^music      v1.2',
    s_btn='[*]',
    s_close='^close (c)',
    s_backpack='^b^a^c^k^p^a^c^k',
    s_empty='###',
    s_equipmark='$ ',
    s_mysterious='mysterious ',
    s_use='use', s_discard='discard', s_equip='equip', s_unequip='unequip',
    s_space=' ', s_none='',
    s_quest='?', s_excl='!', s_dots='...',
    s_floor='^floor ',
    s_killedby='^killed by ',
    s_onfloor='on floor ',
    s_poison='poison',
    s_lvlup='^level up', s_atkup='^a^t^k +1', s_hpup='^max ^h^p &+3', s_refill='^h^p refilled!',
    s_heartplus='&+',
    s_a_equip='^equip weapon to alter...',
    s_a_untampered='^weapon must be untampered...',
    s_a_food='^cursed food required...',
    s_a_shattererd=' shattererd!',
    s_a_shattered=' shattered!',
    s_a_dip='^dip a cursed weapon in the pool...',
    s_a_nocurse=' is no longer cursed!',
    s_a_noident='^nothing to identify...',
    s_a_carry="^can't carry any more...",
    s_a_poison='^b^l^e^h! ^poisonous!',
    s_a_dizzy='^feeling dizzy...',
    s_a_glup="^g^l^u^p! ^can't move!",
    s_a_rotten="^ouf... ^it's rotten!",
    s_a_stuck=' is stuck!',
)

so = ['; generated by tools/make_data.py - do not edit\n']
strings = {}


def emit(label, text):
    g = enc(text)
    assert len(g) <= 46, (label, text)
    so.append(f'{label} dta ' + ','.join(str(v) for v in g + [255]))


for label, text in S.items():
    emit(label, text)
for label, lines in L.items():
    for i, t in enumerate(lines):
        emit(f'{label}_{i}', t)
    so.append(f'{label} dta {len(lines)}')
    so.append('        dta a(' + ','.join(f'{label}_{i}' for i in range(len(lines))) + ')')
# name pointer tables
so.append('mname_lo dta 0,' + ','.join(f'<mn_{i}' for i in range(1, 26)))
so.append('mname_hi dta 0,' + ','.join(f'>mn_{i}' for i in range(1, 26)))
so.append('iname_lo dta 0,' + ','.join(f'<itn_{i}' for i in range(1, 16)))
so.append('iname_hi dta 0,' + ','.join(f'>itn_{i}' for i in range(1, 16)))
so.append('trait_lo dta 0,' + ','.join(f'<tr_{i}' for i in range(1, 4)))
so.append('trait_hi dta 0,' + ','.join(f'>tr_{i}' for i in range(1, 4)))
so.append('status_lo dta 0,' + ','.join(f'<st_{i}' for i in range(1, 6)))
so.append('status_hi dta 0,' + ','.join(f'>st_{i}' for i in range(1, 6)))
# pixel widths of window texts are computed at run time (tlen)
(HERE / 'gen' / 'strings.asm').write_text('\n'.join(so) + '\n')

# ---------------------------------------------------------------- sound
# Each sfx: 32 notes x 2 bytes, then speed, loop start, loop end, 0.
# note byte 0: pitch (0..63) | $40 if the noise waveform is used
# note byte 1: volume (0..7) | effect << 4
# Only the sound effects (6, 32..63) are kept: the music is not played.
SFX_USED = [6] + list(range(32, 64))
snd = bytearray()
for sid in SFX_USED:
    b = 0x3200 + sid * 68
    for n in range(32):
        lo, hi = cart[b + n * 2], cart[b + n * 2 + 1]
        pitch = lo & 0x3f
        wave = ((lo >> 6) & 3) | ((hi & 1) << 2)
        vol = (hi >> 1) & 7
        eff = (hi >> 4) & 7
        snd += bytes([pitch | (0x40 if wave == 6 else 0), vol | (eff << 4)])
    snd += bytes([max(1, cart[b + 65]), cart[b + 66], cart[b + 67], 0])
(HERE / 'data' / 'sfx.bin').write_bytes(snd)
pos = {sid: i for i, sid in enumerate(SFX_USED)}
out.append('sfx_ptr_lo\n' + '\n'.join(f'        dta <(sfx_data+{pos.get(i, 0) * 68})' for i in range(64)) + '\n')
out.append('sfx_ptr_hi\n' + '\n'.join(f'        dta >(sfx_data+{pos.get(i, 0) * 68})' for i in range(64)) + '\n')
out.append(dta('music_data', [0x40] * 4))     # (music is not played)

# POKEY AUDF for PICO-8 pitch p (64 kHz clock); notes below the 8-bit range
# are raised by octaves.
audf = []
for p in range(64):
    f = 65.406 * 2 ** (p / 12)
    while 63921 / (2 * f) - 1 > 255:
        f *= 2
    audf.append(max(1, min(255, round(63921 / (2 * f) - 1))))
out.append(dta('pitch_audf', audf))

(HERE / 'gen' / 'tables.asm').write_text('\n'.join(out))
print('glyphs:', len(GLYPHS), 'strings:', len(S) + sum(len(v) for v in L.values()),
      'sfx bytes:', len(snd))
