#!/usr/bin/env python3
"""Write editor/assets.js: the default game (built from the cartridge), the
glyphs the font can draw, and the bundled library of .p8 carts (games built
on the Lazy Devs roguelike engine, whose monsters and maps convert well).

    python3 tools/make_editor_assets.py
"""
import json
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import lichdata as LD

HERE = LD.HERE
ROOT = HERE.parent.parent
LIBRARY = ['Porklike', 'BulbaRogue', 'Crocolike', 'The Demon Within (v1.0.0b)']

game = LD.default_game()
glyphs = [k for k, _, _ in LD.parse_font(LD.lua_source())]
lib = []
for name in LIBRARY:
    p = ROOT / 'allgames' / '[RPG]' / f'{name}.p8'
    lib.append({'name': name, 'p8': p.read_bytes().decode('latin-1')})
meta = {
    'params': [{'key': k, 'default': d, 'kind': kind, 'desc': desc} for k, d, kind, desc in LD.PARAMS],
    'abilities': LD.ABILITIES, 'abilityDesc': LD.ABILITY_DESC,
    'maxEntities': LD.MAXENT_IDS, 'maxItems': LD.MAXITEMS, 'maxFloors': LD.MAXFLOORS,
    'floorBytes': LD.FLOOR_BYTES, 'propRoles': {str(k): v for k, v in LD.PROP_ROLES.items()},
}
js = ('// generated by tools/make_editor_assets.py - do not edit\n'
      f'const DEFAULT_GAME = {json.dumps(game)};\n'
      f'const GLYPH_KEYS = {json.dumps(glyphs)};\n'
      f'const META = {json.dumps(meta)};\n'
      f'const LIBRARY = {json.dumps(lib)};\n')
(HERE / 'editor' / 'assets.js').write_text(js)
print(f'editor/assets.js: {len(js) // 1024} KB, {len(lib)} library carts')
