#!/usr/bin/env python3
"""Build the data of the Lich King VBXE port from a game description.

The game description is data/game.json (the editor's export format, see
tools/lichdata.py).  When it is missing, the default is built from the
cartridge (pico/cart.bin, pico/lich.lua) and written there first; that
default produces exactly the original game.

Writes:
  data/gfx.bin      8192 bytes  sprite sheet (sprites 0..255), 4 bpp
  data/gfx2.bin     4096 bytes  second sprite page (sprites 256..383), 4 bpp
  data/stage.bin              font masks and the three XDLs (VRAM $0C000)
  data/floors.bin             hand-made floors, RLE (VRAM $3E000)
  data/sfx.bin                sound effects (see src/sound.asm)
  gen/params.asm              rule constants (P_...)
  gen/tables.asm              game tables, palettes, glyph widths
  gen/strings.asm             every text, as glyph strings

    python3 tools/make_data.py [game.json]
"""
from pathlib import Path
import math
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent))
import lichdata as LD

HERE = LD.HERE
cart = LD.cart_bytes()
lua = LD.lua_source()
game = LD.load_game(sys.argv[1] if len(sys.argv) > 1 else None)
P = game['params']
(HERE / 'data').mkdir(exist_ok=True)
(HERE / 'gen').mkdir(exist_ok=True)


def dta(name, values, width=16):
    lines = [f'{name}']
    for i in range(0, len(values), width):
        lines.append('        dta ' + ','.join(str(v & 255) for v in values[i:i + width]))
    return '\n'.join(lines) + '\n'


def fail(msg):
    raise SystemExit('game.json: ' + msg)


# ---------------------------------------------------------------- font
GLYPHS = LD.parse_font(lua)
GIDX = {key: i for i, (key, _, _) in enumerate(GLYPHS)}


def enc(s, what=''):
    out = []
    i = 0
    while i < len(s):
        ch = s[i]
        if ch == '^':
            key = s[i:i + 2]
            i += 1
        else:
            key = ch + ' '
        if key not in GIDX:
            fail(f'character {key.strip()!r} has no glyph ({what}: {s!r})')
        out.append(GIDX[key])
        i += 1
    return out


# ---------------------------------------------------------------- graphics
sheet = game['sheet']
sheet2 = game['sheet2']
if len(sheet) != 128 or len(sheet2) != LD.SHEET2_ROWS:
    fail('sheet must have 128 rows, sheet2 64 rows')
(HERE / 'data' / 'gfx.bin').write_bytes(LD.rows_to_packed(sheet))
(HERE / 'data' / 'gfx2.bin').write_bytes(LD.rows_to_packed(sheet2))

stage = bytearray(0x1000)       # VRAM $0C000: font masks, glyph g at g*4, stride 512
for g, (key, px, k) in enumerate(GLYPHS):
    for y in range(6):
        for x in range(3):
            if px[y * 3 + x]:
                stage[y * 512 + g * 4 + x] = 0xff


# XDL: 24 blank lines, then 128 rows in LR/narrow mode.  Even rows are
# shown on two TV lines and odd rows on one (192 lines in total).
def xdl(base):
    out = bytearray([0x24, 0x08, 23, 0x10, 0xff])   # OVOFF|RPTL, ATT narrow
    for r in range(128):
        addr = base + r * 128
        last = r == 127
        if r % 2 == 0:
            out += bytes([0x62, 0x20, 1])           # GMON|RPTL|OVADR, LR
        else:
            out += bytes([0x42, 0x20 | (0x80 if last else 0)])
        out += bytes([addr & 255, (addr >> 8) & 255, addr >> 16, 0, 0])
    return out


for base in (0x00000, 0x04000, 0x30000):    # three framebuffers
    x = xdl(base)
    stage += x + bytes(0x400 - len(x))
(HERE / 'data' / 'stage.bin').write_bytes(stage)     # VRAM $0C000..$0DBFF

# ---------------------------------------------------------------- params
mons = game['monsters']
items = game['items']
NENT = len(mons)
NITEM = len(items)
if not 25 <= NENT <= LD.MAXENT_IDS:
    fail(f'{NENT} entity types (25..{LD.MAXENT_IDS})')
if not 1 <= NITEM <= LD.MAXITEMS:
    fail(f'{NITEM} items (1..{LD.MAXITEMS})')
if not 1 <= P['last_floor'] <= LD.MAXFLOORS:
    fail(f'last_floor must be 1..{LD.MAXFLOORS}')
prm = ['; generated by tools/make_data.py - do not edit\n']
for key, default, kind, desc in LD.PARAMS:
    v = P[key]
    name = 'P_' + key.upper()
    if kind == 'chance':
        prm.append(f'{name} = {LD.chance16(v)}        ; {desc} ({v})')
    else:
        prm.append(f'{name} = {int(v)}        ; {desc}')
prm.append(f'NENT = {NENT}')
prm.append(f'NITEM = {NITEM}')
# room drift: rnd_hi thresholds for left / right / up / down
mw = game['move_weights']
tot = sum(mw)
cum = 0
thr = []
for w in mw[:3]:
    cum += w
    thr.append(min(255, round(256 * cum / tot)))
prm += [f'P_MOVE_T1 = {thr[0]}', f'P_MOVE_T2 = {thr[1]}', f'P_MOVE_T3 = {thr[2]}']
prm.append(f'P_NPIECES = {len(game["pieces"])}')
prm.append(f'P_NFLOORW = {len(game["floor_weights"])}')
(HERE / 'gen' / 'params.asm').write_text('\n'.join(prm) + '\n')

# ---------------------------------------------------------------- tables
out = ['; generated by tools/make_data.py - do not edit\n']
out.append(dta('tile_flags', game['flags']))

AB = {a: 1 << i for i, a in enumerate(LD.ABILITIES)}


def col(key, f=lambda v: v):
    return [0] + [f(m[key]) for m in mons]


anim = col('anim')
for i, a in enumerate(anim[1:], 1):
    if not 0 <= a < 256 + 128:
        fail(f'monster {i}: sprite {a} out of range')
    if a >= 256 and (a & 255) > 124:
        fail(f'monster {i}: second-page sprite {a} leaves no room for 4 frames')
out.append(dta('m_anim', [a & 255 for a in anim]))
out.append(dta('m_page', [a >> 8 for a in anim]))
out.append(dta('m_col', col('col')))
out.append(dta('m_prop', col('prop', int)))
out.append(dta('m_hp', col('hp')))
out.append(dta('m_atk', col('atk')))
out.append(dta('m_range', col('range')))
out.append(dta('m_sight', col('sight')))
out.append(dta('m_depth', col('depth')))
out.append(dta('m_itemchance', col('itemchance')))
abil = col('abilities', lambda l: sum(AB[a] for a in l))
for k, lab in enumerate(('m_abil', 'm_abil2', 'm_abil3')):
    out.append(dta(lab, [(v >> (8 * k)) & 255 for v in abil]))
ic = col('itemchance')
out.append(dta('m_item_lo', [min(65535, round(v / 10 * 65536)) & 255 for v in ic]))
out.append(dta('m_item_hi', [min(65535, round(v / 10 * 65536)) >> 8 for v in ic]))
codes = col('code')
out.append(dta('m_code', codes))
anim_id = [0] * 256                      # map code -> entity id, the first match wins
for i in range(NENT, 0, -1):
    anim_id[codes[i] & 255] = i
out.append(dta('anim_id', anim_id))

for k in ('type', 'spr', 'atk', 'heal', 'hpmax', 'depth'):
    out.append(dta('i_' + k, [0] + [it[k] for it in items]))
for src, lab in (('chest', 'list_weapons'), ('shelves', 'list_drinks'), ('pot', 'list_food')):
    ids = [i + 1 for i, it in enumerate(items) if it['found'] == src]
    out.append(f'{lab}_n = {len(ids)}')
    out.append(dta(lab, ids or [0]))
out.append(dta('start_items', list(game['start_items']) + [0]))

out.append(dta('mul07', [(a * 0xb333) >> 16 for a in range(64)]))
xr = list(game['xp_req'])[:64] + [65535] * max(0, 64 - len(game['xp_req']))
out.append(dta('xpreq_lo', [v & 255 for v in xr]))
out.append(dta('xpreq_hi', [v >> 8 for v in xr]))


def per_floor(key):
    v = list(game[key])[:LD.MAXFLOORS]
    return [0] + v + [0] * (LD.MAXFLOORS - len(v))


out.append(dta('fl_budget', per_floor('budget')))
out.append(dta('fl_mimic', per_floor('mimic_offset')))
out.append(dta('fl_treasure', per_floor('treasure_rooms')))
out.append(dta('floor_weights', game['floor_weights']))
out.append(dta('pieces', [v for p in game['pieces'] for v in p], 9))

title_map = [cart[0x2000 + y * 128 + 112 + x] for y in range(16) for x in range(16)]
out.append(dta('title_map', title_map))

dpal = LD.explodeval("0,0,1,5,1,1,13,6,4,4,9,3,13,5,1,1")
lpal = LD.explodeval("1,5,4,11,9,13,7,7,14,10,7,7,7,6,15,7")
fade = LD.explodeval("0,0,1,5,1,1,13,6,4,4,9,3,13,5,4,4")
lit = list(range(16))
lit[14] = 1
sheet_maps = []
for p in (list(range(16)), lit, dpal, lpal):
    sheet_maps += [0] + [c if c else 16 for c in p[1:]]
out.append(dta('sheet_maps', sheet_maps))
fk = []
for k in range(7):
    for c in range(16):
        v = c
        for _ in range(k):
            v = fade[v]
        fk.append(v)
out.append(dta('fade_tab', fk))
PAL = [(0, 0, 0), (29, 43, 83), (126, 37, 83), (0, 135, 81), (171, 82, 54),
       (95, 87, 79), (194, 195, 199), (255, 241, 232), (255, 0, 77),
       (255, 163, 0), (255, 255, 39), (0, 231, 88), (41, 173, 255),
       (131, 118, 156), (255, 119, 168), (255, 204, 170), (0, 0, 0)]
out.append(dta('pal_r', [p[0] for p in PAL]))
out.append(dta('pal_g', [p[1] for p in PAL]))
out.append(dta('pal_b', [p[2] for p in PAL]))

cap = list(range(128))
for g, (key, _, _) in enumerate(GLYPHS):
    if key[1] == ' ' and key[0].isalpha() and ('^' + key[0]) in GIDX:
        cap[g] = GIDX['^' + key[0]]
out.append(dta('cap_glyph', cap))
out.append(dta('glyph_k', [k for _, _, k in GLYPHS] + [4] * (128 - len(GLYPHS))))


def psin(t):
    return -math.sin(2 * math.pi * t)


s88 = [int(math.floor(psin(i / 256) * 256 + 0.5)) for i in range(256)]
out.append(dta('sin_lo', [v & 255 for v in s88]))
out.append(dta('sin_hi', [(v >> 8) & 255 for v in s88]))
out.append(dta('bob_tab', [int(math.floor(7 + psin(t / 30))) for t in range(30)]))

consts = {
    'G_SPACE': ' ', 'G_0': '0', 'G_PLUS': '+', 'G_MINUS': '-', 'G_SLASH': '/',
    'G_LPAR': '(', 'G_RPAR': ')', 'G_DOT': '.', 'G_QUEST': '?', 'G_EXCL': '!',
}
for k, v in consts.items():
    out.insert(1, f'{k} = {GIDX[v + " "]}')

# ---------------------------------------------------------------- floors
# Hand-made floors: 128x32 map codes, RLE ($fe count value), VRAM $3E000.
fl = bytearray()
offs = []
for f in game['floors']:
    rows = f['tiles']
    if len(rows) != 32 or any(len(r) != 256 for r in rows):
        fail(f'floor {f.get("name")}: 32 rows of 128 tiles expected')
    raw = bytes(int(r[i:i + 2], 16) for r in rows for i in range(0, 256, 2))
    offs.append(len(fl))
    i = 0
    while i < len(raw):
        v = raw[i]
        n = 1
        while i + n < len(raw) and raw[i + n] == v and n < 255:
            n += 1
        if n >= 4 or v == 0xfe:
            fl += bytes([0xfe, n, v])
        else:
            fl += bytes([v] * n)
        i += n
if len(fl) > LD.FLOOR_BYTES:
    fail(f'hand-made floors use {len(fl)} bytes after compression (max {LD.FLOOR_BYTES})')
(HERE / 'data' / 'floors.bin').write_bytes(bytes(fl) + bytes(LD.FLOOR_BYTES - len(fl)))
out.append(dta('floor_lo', [o & 255 for o in offs] or [0]))
out.append(dta('floor_hi', [o >> 8 for o in offs] or [0]))
plan = list(game['floor_plan'])[:LD.MAXFLOORS]
plan += [-1] * (LD.MAXFLOORS - len(plan))
for i, v in enumerate(plan):
    if v >= len(game['floors']):
        fail(f'floor {i + 1} uses map {v}, which does not exist')
out.append(dta('floor_plan', [0xff] + [v if v >= 0 else 0xff for v in plan]))

# ---------------------------------------------------------------- strings
so = ['; generated by tools/make_data.py - do not edit\n']


def emit(label, text):
    g = enc(text, label)
    if len(g) > 46:
        fail(f'text too long ({len(g)} glyphs, max 46): {text!r}')
    so.append(f'{label} dta ' + ','.join(str(v) for v in g + [255]))


for i, m in enumerate(mons):
    emit(f'mn_{i + 1}', m['name'])
for i, it in enumerate(items):
    emit(f'itn_{i + 1}', it['name'])
for label, text in game['texts'].items():
    emit(label, text)
for label, lines in game['windows'].items():
    if len(lines) > 12:
        fail(f'window {label}: at most 12 lines')
    for i, t in enumerate(lines):
        emit(f'{label}_{i}', t)
    so.append(f'{label} dta {len(lines)}')
    so.append('        dta a(' + ','.join(f'{label}_{i}' for i in range(len(lines))) + ')')
so.append('mname_lo dta 0,' + ','.join(f'<mn_{i}' for i in range(1, NENT + 1)))
so.append('mname_hi dta 0,' + ','.join(f'>mn_{i}' for i in range(1, NENT + 1)))
so.append('iname_lo dta 0,' + ','.join(f'<itn_{i}' for i in range(1, NITEM + 1)))
so.append('iname_hi dta 0,' + ','.join(f'>itn_{i}' for i in range(1, NITEM + 1)))
so.append('trait_lo dta 0,' + ','.join(f'<tr_{i}' for i in range(1, 4)))
so.append('trait_hi dta 0,' + ','.join(f'>tr_{i}' for i in range(1, 4)))
so.append('status_lo dta 0,' + ','.join(f'<st_{i}' for i in range(1, 6)))
so.append('status_hi dta 0,' + ','.join(f'>st_{i}' for i in range(1, 6)))
(HERE / 'gen' / 'strings.asm').write_text('\n'.join(so) + '\n')

# ---------------------------------------------------------------- sound
SFX_USED = [6] + list(range(32, 64))
snd = bytearray()
for sid in SFX_USED:
    b = 0x3200 + sid * 68
    for n in range(32):
        lo, hi = cart[b + n * 2], cart[b + n * 2 + 1]
        pitch = lo & 0x3f
        wave = ((lo >> 6) & 3) | ((hi & 1) << 2)
        vol = (hi >> 1) & 7
        eff = (hi >> 4) & 7
        snd += bytes([pitch | (0x40 if wave == 6 else 0), vol | (eff << 4)])
    snd += bytes([max(1, cart[b + 65]), cart[b + 66], cart[b + 67], 0])
# The effects live in RAM under the OS ROM (copied there while loading):
# $c900-$cfff and $fd00-$fff9, 68 bytes each.
REGIONS = [(0xc900, 0xd000), (0xfd00, 0xfff8)]
addr = {}
reg = 0
cur = REGIONS[0][0]
for i, sid in enumerate(SFX_USED):
    if cur + 68 > REGIONS[reg][1]:
        reg += 1
        if reg == len(REGIONS):
            fail('sound effects do not fit')
        cur = REGIONS[reg][0]
    addr[sid] = cur
    cur += 68
(HERE / 'data' / 'sfx.bin').write_bytes(snd)
n1 = sum(1 for a in addr.values() if a < 0xd000)
out.insert(1, f'SFX_LEN1 = {n1 * 68}\nSFX_LEN2 = {(len(SFX_USED) - n1) * 68}')
out.append('sfx_ptr_lo\n' + '\n'.join(f'        dta <${addr.get(i, addr[6]):04x}' for i in range(64)) + '\n')
out.append('sfx_ptr_hi\n' + '\n'.join(f'        dta >${addr.get(i, addr[6]):04x}' for i in range(64)) + '\n')
out.append(dta('music_data', [0x40] * 4))     # (music is not played)
audf = []
for p in range(64):
    f = 65.406 * 2 ** (p / 12)
    while 63921 / (2 * f) - 1 > 255:
        f *= 2
    audf.append(max(1, min(255, round(63921 / (2 * f) - 1))))
out.append(dta('pitch_audf', audf))

(HERE / 'gen' / 'tables.asm').write_text('\n'.join(out))
print(f'{game["name"]}: {NENT} entity types, {NITEM} items, {len(game["floors"])} hand-made floors '
      f'({len(fl)} bytes)')
