#!/usr/bin/env python3
"""Compile Polish story pauses into ANTIC 2 pages and an 8x8 character set."""

import gzip
import json
import struct
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parent
FONT_SOURCE = Path("/usr/share/consolefonts/Uni2-VGA8.psf.gz")
WIDTH = 36
BODY_ROWS = 20
SCREEN_COLS = 40
SCREEN_ROWS = 24
EXTRA = "ĄĆĘŁŃÓŚŹŻąćęłńóśźż–"
EXTRA_CODES = {char: 96 + index for index, char in enumerate(EXTRA)}


def encode(char):
    if " " <= char <= "~":
        return ord(char) - 32
    if char in EXTRA_CODES:
        return EXTRA_CODES[char]
    raise ValueError(f"Character {char!r} is not in the story font")


def wrap_story(text):
    lines = []
    for paragraph in text.split("\n\n"):
        if lines:
            lines.append("")
        line = ""
        for word in paragraph.split():
            if len(word) > WIDTH:
                raise ValueError(f"Story word exceeds {WIDTH} columns")
            if line and len(line) + 1 + len(word) > WIDTH:
                lines.append(line)
                line = ""
            if line:
                line += " "
            line += word
        if line:
            lines.append(line)
    return [lines[i : i + BODY_ROWS] for i in range(0, len(lines), BODY_ROWS)]


def make_font():
    source = gzip.decompress(FONT_SOURCE.read_bytes())
    if source[:2] != b"\x36\x04" or source[3] != 8 or not source[2] & 2:
        raise ValueError("Expected a Unicode-mapped 8x8 PSF1 font")
    glyph_count = 512 if source[2] & 1 else 256
    glyphs = source[4 : 4 + glyph_count * 8]
    unicode_data = source[4 + glyph_count * 8 :]
    codepoints = {}
    glyph_index = 0
    for (codepoint,) in struct.iter_unpack("<H", unicode_data[: len(unicode_data) & ~1]):
        if codepoint == 0xFFFF:
            glyph_index += 1
        elif codepoint != 0xFFFE:
            codepoints.setdefault(codepoint, glyph_index)

    data = bytearray(1024)
    chars = {code: chr(code + 32) for code in range(95)}
    chars.update({code: char for char, code in EXTRA_CODES.items()})
    for code, char in chars.items():
        if ord(char) not in codepoints:
            raise ValueError(f"Missing glyph for {char!r} in {FONT_SOURCE}")
        offset = codepoints[ord(char)] * 8
        data[code * 8 : code * 8 + 8] = glyphs[offset : offset + 8]
    return data


def page_records(lines, after_level, page_index, page_count):
    records = []

    def add(row, col, content):
        payload = [encode(char) for char in content]
        if payload:
            assert 0 <= row < SCREEN_ROWS and col + len(payload) <= SCREEN_COLS
            records.append((row, col, payload))

    for line_number, line in enumerate(lines):
        add(2 + line_number, 2, line)
    footer = f"FIRE / SPACE / START  -  DALEJ  {page_index + 1}/{page_count}"
    add(23, 2, footer)
    return records


def format_bytes(values):
    return ",".join(f"${value:02X}" for value in values)


def main():
    pauses = json.loads((ROOT / "story_pauses.json").read_text(encoding="utf-8"))
    if not pauses:
        raise ValueError("At least one story pause is required")
    grouped = {}
    for pause in pauses:
        level = pause["after_level"]
        if not 1 <= level < 56:
            raise ValueError(f"Invalid after_level: {level}")
        grouped.setdefault(level, []).extend(wrap_story(pause["text"]))

    after_levels = list(grouped)
    first_pages = []
    page_counts = []
    pages = []
    for level, wrapped in grouped.items():
        first_pages.append(len(pages))
        page_counts.append(len(wrapped))
        for index, lines in enumerate(wrapped):
            pages.append(page_records(lines, level, index, len(wrapped)))
    if len(pages) > 255:
        raise ValueError("Too many story pages")

    font = make_font()
    (ROOT / "story-font.bin").write_bytes(font)
    result = [
        "; Generated by generate_story.py from story_pauses.json.",
        f"STORY_BREAK_TOTAL = {len(grouped)}",
        f"STORY_PAGE_COUNT = {len(pages)}",
        "story_break_level dta " + format_bytes(after_levels),
        "story_break_first dta " + format_bytes(first_pages),
        "story_break_pages dta " + format_bytes(page_counts),
        "story_page_lo dta " + ",".join(f"<story_page_{i}" for i in range(len(pages))),
        "story_page_hi dta " + ",".join(f">story_page_{i}" for i in range(len(pages))),
    ]
    for index, records in enumerate(pages):
        result.append(f"story_page_{index}")
        for row, col, payload in records:
            result.append("        dta " + format_bytes([row, col, len(payload), *payload]))
        result.append("        dta $FF")
    (ROOT / "story-pages.inc").write_text("\n".join(result) + "\n", encoding="ascii")

    # Exact font and page layout preview, at a visible scale for proofreading.
    preview = Image.new("RGB", (SCREEN_COLS * 8, SCREEN_ROWS * 8 * len(pages)), (5, 7, 12))
    for page_index, records in enumerate(pages):
        for row, col, payload in records:
            for offset, code in enumerate(payload):
                glyph = font[(code & 0x7F) * 8 : (code & 0x7F) * 8 + 8]
                for y, bits in enumerate(glyph):
                    for x in range(8):
                        lit = bool(bits & (0x80 >> x))
                        color = (235, 229, 203) if lit else (5, 7, 12)
                        preview.putpixel(((col + offset) * 8 + x, (page_index * SCREEN_ROWS + row) * 8 + y), color)
    preview.resize((preview.width * 3, preview.height * 3), Image.Resampling.NEAREST).save(
        ROOT / "story-preview.png"
    )
    print(f"Wrote {len(grouped)} story break(s), {len(pages)} page(s)")


if __name__ == "__main__":
    main()
