#!/usr/bin/env node
'use strict';

// Converts the level data extracted from orggame.js into a compact MADS include.
const fs = require('fs');
const path = require('path');

const sourcePath = path.join(__dirname, '..', 'orggame', 'extracted', 'all_levels.json');
const outputPath = path.join(__dirname, 'levels.inc');
const source = JSON.parse(fs.readFileSync(sourcePath, 'utf8'));
const groups = ['Basics', 'Force', 'Trials', 'Dual', 'Scale'];
const tiles = {
    '.': 0, '@': 1, 'E': 2, '#': 3, 'P': 4, 'R': 5, 'X': 6,
    '%': 7, '^': 8, '>': 9, 'v': 10, '<': 11, 'L': 12, 'K': 13,
};

const levels = [];
for (const group of groups) {
    for (const text of source[group]) {
        const rows = text.split('\n');
        const width = rows[0].length;
        if (!rows.every(row => row.length === width)) {
            throw new Error(`Non-rectangular level in ${group}`);
        }
        if (width < 1 || width > 20 || rows.length > 20 || width * rows.length > 254) {
            throw new Error(`Level exceeds the Atari board/index limits in ${group}`);
        }
        const symbols = rows.join('');
        if ([...symbols].some(c => tiles[c] === undefined)) throw new Error(`Unknown tile in ${group}`);
        const starts = [...symbols].filter(c => c === '@').length;
        const portals = [...symbols].filter(c => c === '%').length;
        if (starts < 1 || starts > 2 || ![0, 2].includes(portals)) {
            throw new Error(`Expected 1-2 starts and paired portals in ${group}`);
        }
        levels.push({ group, width, height: rows.length, cells: rows.join('').split('').map(c => tiles[c]) });
    }
}

function writeInclude(file, entries, description) {
    const out = [];
    out.push(`; Generated by generate_levels.js from ${description}.`);
    out.push('; Cell values match CT_* constants in streamline-vbxe.asm.');
    out.push(`LEVEL_COUNT = ${entries.length}`);
    out.push('');
    out.push('level_ptr_lo');
    out.push('        dta ' + entries.map((_, i) => `<level_${String(i).padStart(2, '0')}`).join(','));
    out.push('level_ptr_hi');
    out.push('        dta ' + entries.map((_, i) => `>level_${String(i).padStart(2, '0')}`).join(','));
    out.push('level_group_start');
    out.push('        dta ' + groups.map(group => entries.findIndex(level => level.group === group))
        .concat(entries.length).join(','));
    out.push('');

    entries.forEach((level, index) => {
        const label = `level_${String(index).padStart(2, '0')}`;
        out.push(`${label} ; ${level.label || level.group + ' ' + (index + 1)}`);
        out.push(`        dta ${level.width},${level.height}`);
        for (let y = 0; y < level.height; y++) {
            const row = level.cells.slice(y * level.width, (y + 1) * level.width);
            out.push('        dta ' + row.join(','));
        }
        out.push('');
    });
    fs.writeFileSync(file, out.join('\n'));
    console.log(`Wrote ${entries.length} levels to ${file}`);
}

writeInclude(outputPath, levels, 'orggame/extracted/all_levels.json');

// The standard XL/XE story presents the elephant's own upside-down-cross board
// after the twelfth original level. The VBXE include above stays at 56 levels.
const bonusRows = [
    '........E',
    '....#....',
    '....#....',
    '....#....',
    '....#....',
    '....#....',
    '..#####..',
    '....#....',
    '@........',
];
const bonus = {
    group: 'Basics', label: 'Elephant bonus: upside-down cross',
    width: bonusRows[0].length, height: bonusRows.length,
    cells: bonusRows.join('').split('').map(char => tiles[char]),
};
const standardLevels = [...levels.slice(0, 12), bonus, ...levels.slice(12)];
writeInclude(path.join(__dirname, 'levels-standard.inc'), standardLevels,
    'orggame/extracted/all_levels.json plus the Atari elephant bonus');
