#!/usr/bin/env node
'use strict';

// Converts the level data extracted from orggame.js into a compact MADS include.
const fs = require('fs');
const path = require('path');

const sourcePath = path.join(__dirname, '..', 'orggame', 'extracted', 'all_levels.json');
const outputPath = path.join(__dirname, 'levels.inc');
const source = JSON.parse(fs.readFileSync(sourcePath, 'utf8'));
const groups = ['Basics', 'Force', 'Trials', 'Dual', 'Scale'];
const tiles = {
    '.': 0, '@': 1, 'E': 2, '#': 3, 'P': 4, 'R': 5, 'X': 6,
    '%': 7, '^': 8, '>': 9, 'v': 10, '<': 11, 'L': 12, 'K': 13,
};

const levels = [];
for (const group of groups) {
    for (const text of source[group]) {
        const rows = text.split('\n');
        const width = rows[0].length;
        if (!rows.every(row => row.length === width)) {
            throw new Error(`Non-rectangular level in ${group}`);
        }
        levels.push({ group, width, height: rows.length, cells: rows.join('').split('').map(c => tiles[c]) });
    }
}

const out = [];
out.push('; Generated by generate_levels.js from orggame/extracted/all_levels.json.');
out.push('; Cell values match CT_* constants in streamline-vbxe.asm.');
out.push(`LEVEL_COUNT = ${levels.length}`);
out.push('');
out.push('level_ptr_lo');
out.push('        dta ' + levels.map((_, i) => `<level_${String(i).padStart(2, '0')}`).join(','));
out.push('level_ptr_hi');
out.push('        dta ' + levels.map((_, i) => `>level_${String(i).padStart(2, '0')}`).join(','));
out.push('level_group_start');
let start = 0;
out.push('        dta ' + groups.map(group => {
    const value = start;
    start += source[group].length;
    return value;
}).concat(levels.length).join(','));
out.push('');

levels.forEach((level, index) => {
    const label = `level_${String(index).padStart(2, '0')}`;
    out.push(`${label} ; ${level.group} ${index + 1}`);
    out.push(`        dta ${level.width},${level.height}`);
    for (let y = 0; y < level.height; y++) {
        const row = level.cells.slice(y * level.width, (y + 1) * level.width);
        out.push('        dta ' + row.join(','));
    }
    out.push('');
});

fs.writeFileSync(outputPath, out.join('\n'));
console.log(`Wrote ${levels.length} levels to ${outputPath}`);
