#!/usr/bin/env python3
"""Relocate original terrain queries and their typed tables to Atari RAM.

No guessed collision rectangles, tile classifications or opcode substitutions.
The routines retain the original engine RAM ABI and require OS takeover before
native integration. This component is not the playable adaptation's terrain.
"""
import hashlib
import json
from py65.devices.mpu6502 import MPU
from py65.disassembler import Disassembler
from build_source_engine import OUT

START, END = 0xb000, 0xb861
BASE = 0x4000
COUNTS = (2, 1, 4, 4)
CODE = ((0xb000, 0xb0f4), (0xb3ec, 0xb48e), (0xb6fd, 0xb78e))


def relocate(bank, base=BASE):
    if len(bank) != 0x4000:
        raise ValueError('expected a complete assembled bank 5')
    if base & 255 or not 0x1000 <= base <= 0xa000 - (END-START):
        raise ValueError('terrain needs page-aligned RAM below Atari ROM and hardware')
    data = bytearray(bank[START-0x8000:END-0x8000])
    memory = bytearray(65536)
    memory[0x8000:0xc000] = bank
    cpu = MPU(memory=memory)
    dis = Disassembler(cpu)
    patches = {}
    instructions, branches = set(), []

    def word(address):
        return memory[address] | memory[address+1] << 8

    def pointer(address, kind):
        value = word(address)
        if address in patches:
            return value
        if not START <= value < END:
            raise ValueError(f'{kind} pointer ${value:04x} at ${address:04x} escapes terrain')
        adjusted = base + value - START
        data[address-START:address-START+2] = adjusted.to_bytes(2, 'little')
        patches[address] = {'at': address, 'target': value, 'kind': kind}
        return value

    # Code and data are explicitly distinguished. Never scan data for opcodes
    # or for arbitrary byte pairs that happen to look like ROM addresses.
    for start, end in CODE:
        pc = start
        while pc < end:
            length, _ = dis.instruction_at(pc)
            mnemonic, mode = cpu.disassemble[memory[pc]]
            if mnemonic in ('???', 'BRK') or pc + length > end:
                raise ValueError(f'unsupported code at ${pc:04x}')
            instructions.add(pc)
            if mnemonic in ('JSR', 'JMP') and mode == 'abs':
                branches.append(word(pc+1))
                pointer(pc+1, 'instruction')
            elif mode in ('abs', 'abx', 'aby') and word(pc+1) >= 0x8000:
                pointer(pc+1, 'instruction')
            elif mode == 'ind':
                raise ValueError('computed jump needs an explicit relocation rule')
            elif mode == 'rel':
                branches.append(pc+2+((memory[pc+1]+128) % 256)-128)
            pc += length
    if any(target not in instructions for target in branches):
        raise ValueError('control transfer escapes the declared terrain instructions')

    # Boundary table: stage/layer -> section -> 12-byte boundary records.
    # The other word in each section descriptor is a height, NOT a pointer.
    for stage, count in enumerate(COUNTS):
        for layer in range(2):
            root = pointer(0xb0f4 + stage*4 + layer*2, 'boundary root')
            for section in range(count):
                field = root + section*4
                if word(field):
                    pointer(field, 'boundary records')

    # Support table: stage -> section(depth, page mask pointer, surface pointer).
    # $ff depth disables a section. Section 3 of mission 4 has RAM pointers;
    # preserve those literally, just as the original query does.
    for stage, count in enumerate(COUNTS):
        root = pointer(0xb48e + stage*2, 'support root')
        for section in range(count):
            record = root + section*5
            if memory[record] == 0xff:
                continue
            for field in (record+1, record+3):
                if word(field) >= 0x8000:
                    pointer(field, 'support records')
    # Vertical faces: stage -> section(depth, pointer) -> 9-byte rectangles.
    for stage, count in enumerate(COUNTS):
        field = 0xb78e + stage*2
        if not word(field):
            continue
        root = pointer(field, 'wall root')
        for section in range(count):
            record = root + section*3
            if memory[record] != 0xff:
                pointer(record+1, 'wall records')
    return bytes(data), sorted(patches.values(), key=lambda entry: entry['at'])


def build():
    bank = (OUT / 'bank5.bin').read_bytes()
    data, patches = relocate(bank)
    (OUT / 'terrain.bin').write_bytes(data)
    # An include, not a standalone XEX: the complete engine will own this RAM.
    lines = ['; Generated by tools/build_source_terrain.py; do not edit.',
             '; Original source-engine RAM ABI; Atari OS must be suspended.',
             '        opt h-', f'        org ${BASE:04x}']
    entries = ((0, 'source_terrain_bounds'), (0xb3ec-START, 'source_terrain_support'),
               (0xb6fd-START, 'source_terrain_wall'), (len(data), 'source_terrain_end'))
    for (start, label), (end, _) in zip(entries, entries[1:]):
        lines.append(label)
        for offset in range(start, end, 16):
            lines.append('        dta ' + ','.join(f'${value:02x}' for value in data[offset:min(offset+16,end)]))
    lines.append('source_terrain_end')
    (OUT / 'terrain.asm').write_text('\n'.join(lines) + '\n')
    manifest = {
        'status': 'native component; not connected to the playable XEX',
        'source_bank': 5, 'source_start': START, 'source_end': END,
        'load_address': BASE, 'bytes': len(data),
        'entry_points': {'bounds': BASE, 'support': BASE+0xb3ec-START,
                         'wall': BASE+0xb6fd-START},
        'bank_sha256': hashlib.sha256(bank).hexdigest(),
        'sha256': hashlib.sha256(data).hexdigest(), 'relocations': patches,
    }
    (OUT / 'terrain.json').write_text(json.dumps(manifest, indent=2) + '\n')
    print(f'Relocated three source terrain queries: {len(data)} bytes, {len(patches)} typed relocations.')


if __name__ == '__main__':
    build()
