#!/usr/bin/env python3
"""Build a separate, explicitly experimental full-source execution XEX.

The normal game/launcher is not replaced. The instruction bridge preserves
source semantics but is much slower than native source code; this executable
exists to exercise the native memory/video integration, not to claim parity.
"""
import hashlib
import json
import os
import subprocess
from build_source_engine import ROOT, OUT
from make_assets import raw
from pack_source_chr import sets


def assemble(source, output, symbols):
    subprocess.run([os.environ.get('MADS','mads'),str(source),f'-o:{output}',f'-t:{symbols}'],check=True)


def build():
    subprocess.run([os.environ.get('MADS','mads'),str(ROOT/'source-engine/cpu.asm'),
                    '-d:SOURCE_PLATFORM=1','-d:CPU_BASE=12288',f'-o:{OUT}/runtime.bin',
                    f'-t:{OUT}/runtime.lab'],check=True)
    symbols = [p for line in (OUT/'runtime.lab').read_text().splitlines() if len(p:=line.split())==3]
    (OUT/'runtime-symbols.asm').write_text('\n'.join(f'{p[2]} = ${p[1]}' for p in symbols)+'\n')
    palette = raw('palette_lookup.asm')
    colors = [palette[i*2] | palette[i*2+1]<<8 for i in range(64)]
    (OUT/'video-palette.asm').write_text('\n'.join('video_'+name+'\n        dta '+
        ','.join(str(((color>>shift)&31)*255//31) for color in colors)
        for name,shift in (('red',0),('green',5),('blue',10)))+'\n')
    assemble(ROOT/'source-engine/video.asm',OUT/'video.bin',OUT/'video.lab')
    renderer = (OUT/'video.bin').read_bytes()
    if len(renderer)>4096:
        raise ValueError('renderer exceeds its post-loader RAM region')
    chunks = []
    for bank in range(8):
        data = (OUT/f'bank{bank}.bin').read_bytes()
        chunks.extend((bank*4+part,data[part*4096:(part+1)*4096]) for part in range(4))
    chunks.extend((32+index,data) for index,data in enumerate(sets()))
    chunks.append((112,renderer+bytes(4096-len(renderer))))
    assets = []
    for page,data in chunks:
        if len(data)!=4096:
            raise ValueError('asset upload must be exactly 4 KB')
        name = f'preview-page-{page:03d}.bin'
        (OUT/name).write_bytes(data)
        assets += ['        org upload_index',f'        dta {page}',
                   '        org $8000', f"        ins '../generated/source-engine/{name}'",
                   '        ini upload_bank']
    (OUT/'preview-assets.asm').write_text('\n'.join(assets)+'\n')
    # Reuse the already checked loader protocol (INIT state preservation,
    # D6/D7 detection, BASIC/extended-RAM handling); do not fork a second copy.
    loader = (ROOT/'double-dragon-vbxe.asm').read_text().split("        icl 'generated/assets.asm'",1)[0]
    loader += "        icl '../generated/source-engine/preview-assets.asm'\n        ini prepare_runtime\n"
    loader += """
        org $9200
save_preview_page
        lda detected_page
        sta $90fe
        rts
        ini save_preview_page
        org $3000
        ins '../generated/source-engine/runtime.bin'
        org $4000
        ins '../generated/source-engine/bank7.bin'
        org $9000
preview_boot
        lda $90fe
        cmp #$d6
        beq preview_hardware
        cmp #$d7
        beq preview_hardware
        lda #$46
        sta $d01a
preview_missing
        jmp preview_missing
preview_hardware
        sta reg+1
        sei
        cld
        ldx #255
        txs
        lda #0
        sta reg
        sta $d40e
        sta $d20e
        sta $d400
        sta $d01d
        sta $d01a
        lda #$fe
        sta $d301
        lda #$b8
        ldy #$5e
        sta (reg),y
        iny
        lda #$f0
        sta (reg),y
        mwa #$b000 src
        mwa #$2000 dst
        ldy #0
        ldx #16
preview_copy
        lda (src),y
        sta (dst),y
        iny
        bne preview_copy
        inc src+1
        inc dst+1
        dex
        bne preview_copy
        mwa #$1000 dst
        jsr preview_clear
        mwa #$c000 dst
        jsr preview_clear
        lda #0
        ldy #0
preview_clear_palette
        sta $d800,y
        iny
        bne preview_clear_palette
        jmp $2000
preview_clear
        lda #0
        ldx #16
        ldy #0
preview_clear_page
        sta (dst),y
        iny
        bne preview_clear_page
        inc dst+1
        dex
        bne preview_clear_page
        rts
        ert * > $90fe
        run preview_boot
"""
    path = ROOT/'source-engine/preview-generated.asm'
    path.write_text('; Generated by tools/build_source_preview.py.\n'+loader)
    xex = ROOT/'double-dragon-source-preview.xex'
    assemble(path,xex,OUT/'preview.lab')
    manifest = {'status':'experimental source execution preview; not complete parity or real-time gameplay',
                'xex_sha256':hashlib.sha256(xex.read_bytes()).hexdigest(),
                'renderer_bytes':len(renderer), 'runtime_bytes':len((OUT/'runtime.bin').read_bytes()),
                'asset_pages':[page for page,_ in chunks]}
    (OUT/'preview.json').write_text(json.dumps(manifest,indent=2)+'\n')
    print(f'Built separate source preview: {xex.name} ({xex.stat().st_size} bytes).')


if __name__ == '__main__':
    build()
