; Generated by tools/build_source_preview.py.
; Double Dragon Atari adaptation. MADS, 6502, Atari XL/XE + VBXE FX 1.2x.
; CPU: loader $9000, runtime $3000-$7FFF, upload staging $8000,
;      MEMAC window $B000 (BASIC disabled while mapped). OS VBI retained, BASIC disabled.
; VRAM: framebuffers $00000/$10000; tile atlases $20000..$2ffff;
; panorama $30000..$61fff; fighters $62000..$7dfff;
; font $7e000 plus framebuffer padding; XDL/BCB $7f000/$7f100.
reg = $cb
src = $cd
dst = $cf
str = $d1
TITLE = 0
PLAY = 1
PAUSE = 2
OVER = 3
WIN = 4
MEMAC_WINDOW = $b000
MEMAC_CONFIG = $b8           ; 4K, CPU only, base $B000
        org $9000
upload_bank
        ; INIT returns to a disk/XEX loader. Preserve its scratch pointers and
        ; registers; never leave a MEMAC window over its buffers after returning.
        php
        pha
        txa
        pha
        tya
        pha
        ldx #5
upload_save_zp
        lda reg,x
        pha
        dex
        bpl upload_save_zp
        lda $d301
        pha
        cld
        jsr detect_vbxe
        bcc upload_restore
        lda $d301
        ora #2               ; BASIC ROM has priority over MEMAC at $B000
        sta $d301
        jsr disable_windows
        ; Quiesce an overlay/blitter left by a previous program.
        ldy #$40
        lda #0
        sta (reg),y
        ldy #$53
        sta (reg),y
        iny
        sta (reg),y
        ldy #$5e
        lda #MEMAC_CONFIG
        sta (reg),y
        iny
        lda upload_index
        ora #$80
        sta (reg),y
        mwa #$8000 src
        mwa #MEMAC_WINDOW dst
        ldx #16
        ldy #0
upload_page
        lda (src),y
        sta (dst),y
        iny
        bne upload_page
        inc src+1
        inc dst+1
        dex
        bne upload_page
        inc upload_index
        jsr disable_windows
upload_restore
        pla
        sta $d301            ; restore the loader's ROM/extended-RAM selection
        ldx #0
upload_restore_zp
        pla
        sta reg,x
        inx
        cpx #6
        bne upload_restore_zp
        pla
        tay
        pla
        tax
        pla
        plp
upload_done
        rts
upload_index dta 32
detected_page dta 0

; The FX manual defines compatible cores by CORE_VERSION=$10 and
; MINOR_REVISION bits 6..4=$20. Bit 7 denotes RAMBO, not a newer revision.
; Do not mistake a GTIA-only/old core at D600 for a compatible FX at D700.
detect_vbxe
        lda #0
        sta reg
        sta detected_page
        lda #$d6
        sta reg+1
        jsr check_fx_core
        bcs detected
        inc reg+1
        jsr check_fx_core
        bcc detection_done
detected
        lda reg+1
        sta detected_page
        sec
detection_done
        rts
check_fx_core
        ldy #$40
        lda (reg),y
        cmp #$10
        bne incompatible_core
        iny
        lda (reg),y
        and #$70
        cmp #$20
        beq compatible_core
incompatible_core
        clc
        rts
compatible_core
        sec
        rts

disable_windows
        lda #0
        ldy #$5f
        sta (reg),y          ; global MEMAC-A enable off before moving it
        dey
        sta (reg),y
        dey
        sta (reg),y          ; MEMAC-B must not shadow runtime $4000-$7fff
        rts

; Runs before the runtime segments are loaded, not after they have already
; been written into an inherited extended-RAM bank. The game owns all VRAM.
prepare_runtime
        php
        pha
        txa
        pha
        tya
        pha
        lda reg
        pha
        lda reg+1
        pha
        cld
        jsr detect_vbxe
        bcc prepare_ram
        jsr disable_windows
prepare_ram
        lda #$ff             ; OS on, BASIC/self-test/CPU+ANTIC expansion off
        sta $d301
        pla
        sta reg+1
        pla
        sta reg
        pla
        tay
        pla
        tax
        pla
        plp
        rts
        ert * > $9100
        icl '../generated/source-engine/preview-assets.asm'
        ini prepare_runtime

        org $9200
save_preview_page
        lda detected_page
        sta $90fe
        rts
        ini save_preview_page
        org $3000
        ins '../generated/source-engine/runtime.bin'
        org $4000
        ins '../generated/source-engine/bank7.bin'
        org $9000
preview_boot
        lda $90fe
        cmp #$d6
        beq preview_hardware
        cmp #$d7
        beq preview_hardware
        lda #$46
        sta $d01a
preview_missing
        jmp preview_missing
preview_hardware
        sta reg+1
        sei
        cld
        ldx #255
        txs
        lda #0
        sta reg
        sta $d40e
        sta $d20e
        sta $d400
        sta $d01d
        sta $d01a
        lda #$fe
        sta $d301
        lda #$b8
        ldy #$5e
        sta (reg),y
        iny
        lda #$f0
        sta (reg),y
        mwa #$b000 src
        mwa #$2000 dst
        ldy #0
        ldx #16
preview_copy
        lda (src),y
        sta (dst),y
        iny
        bne preview_copy
        inc src+1
        inc dst+1
        dex
        bne preview_copy
        mwa #$1000 dst
        jsr preview_clear
        mwa #$c000 dst
        jsr preview_clear
        lda #0
        ldy #0
preview_clear_palette
        sta $d800,y
        iny
        bne preview_clear_palette
        jmp $2000
preview_clear
        lda #0
        ldx #16
        ldy #0
preview_clear_page
        sta (dst),y
        iny
        bne preview_clear_page
        inc dst+1
        dex
        bne preview_clear_page
        rts
        ert * > $90fe
        run preview_boot
