; Generated by generate_assets.js from player-pixelv1.png
        dta 16,255,180,153      ; hero skin
        dta 17,226,226,226      ; hero top
        dta 18,64,82,48      ; hero trousers
        dta 20,72,148,255      ; hero hair
