"use strict";

var fs = require("fs");
var path = require("path");
var zlib = require("zlib");
var COLS = 7;
var ROWS = 6;
var CELL_COUNT = COLS * ROWS;
var out = [];

function cell(col, row) {
  return col < 0 || col >= COLS || row < 0 || row >= ROWS ?
    255 : row * COLS + col;
}

function hexDistance(a, b) {
  var ar = (a / COLS) | 0;
  var br = (b / COLS) | 0;
  var aq = (a % COLS) - ((ar - (ar & 1)) >> 1);
  var bq = (b % COLS) - ((br - (br & 1)) >> 1);
  var ax = aq;
  var az = ar;
  var ay = -ax - az;
  var bx = bq;
  var bz = br;
  var by = -bx - bz;
  return Math.max(Math.abs(ax - bx), Math.abs(ay - by),
    Math.abs(az - bz));
}

function bytes(label, values, perLine) {
  var i;
  out.push(label);
  for (i = 0; i < values.length; i += perLine) {
    out.push("        dta " + values.slice(i, i + perLine).join(","));
  }
  out.push("");
}

var neighbours = [];
var distance = [];
var cols = [];
var rows = [];
var xsLo = [];
var xsHi = [];
var ys = [];
var evenDx = [1, 0, -1, -1, -1, 0];
var oddDx = [1, 1, 0, -1, 0, 1];
var dy = [0, 1, 1, 0, -1, -1];
var a;
var b;
var d;
var row;
var col;
var x;

out.push("; Generated by generate_data.js. Do not edit by hand.");
out.push("");
for (a = 0; a < CELL_COUNT; a += 1) {
  row = (a / COLS) | 0;
  col = a % COLS;
  cols.push(col);
  rows.push(row);
  x = 55 + col * 30 + (row & 1) * 15;
  xsLo.push(x & 255);
  xsHi.push(x >> 8);
  ys.push(31 + row * 24);
  for (d = 0; d < 6; d += 1) {
    neighbours.push(cell(col + ((row & 1) ? oddDx[d] : evenDx[d]),
      row + dy[d]));
  }
}
for (a = 0; a < CELL_COUNT; a += 1) {
  for (b = 0; b < CELL_COUNT; b += 1) {
    distance.push(hexDistance(a, b));
  }
}

bytes("cell_col", cols, 14);
bytes("cell_row", rows, 14);
bytes("cell_x_lo", xsLo, 14);
bytes("cell_x_hi", xsHi, 14);
bytes("cell_y", ys, 14);
bytes("neighbour_table", neighbours, 12);
out.push("neighbour_row_lo");
out.push("        dta " + Array.from({length: CELL_COUNT}, function (_, i) {
  return "<[neighbour_table+" + (i * 6) + "]";
}).join(","));
out.push("neighbour_row_hi");
out.push("        dta " + Array.from({length: CELL_COUNT}, function (_, i) {
  return ">[neighbour_table+" + (i * 6) + "]";
}).join(","));
out.push("");
out.push("distance_row_lo");
out.push("        dta " + Array.from({length: CELL_COUNT}, function (_, i) {
  return "<[distance_table+" + (i * CELL_COUNT) + "]";
}).join(","));
out.push("distance_row_hi");
out.push("        dta " + Array.from({length: CELL_COUNT}, function (_, i) {
  return ">[distance_table+" + (i * CELL_COUNT) + "]";
}).join(","));
out.push("");
bytes("distance_table", distance, 21);

/* terrain cell lists terminated by 255 */
bytes("battle1_trees", [cell(3, 1), cell(2, 3), cell(5, 4), 255], 16);
bytes("battle2_trees", [cell(3, 1), cell(3, 4), 255], 16);
bytes("battle3_trees", [cell(3, 0), cell(2, 3), cell(4, 4), 255], 16);
bytes("battle4_trees", [cell(3, 1), cell(3, 4), 255], 16);

/* enemy type/cell pairs terminated by 255 */
bytes("battle1_units", [2, cell(5, 1), 2, cell(6, 3), 4, cell(4, 4), 255], 16);
bytes("battle2_units", [3, cell(5, 0), 8, cell(6, 2), 8, cell(5, 5), 255], 16);
bytes("battle3_units", [5, cell(5, 0), 5, cell(6, 3), 4, cell(5, 5),
  2, cell(4, 2), 255], 16);
bytes("battle4_units", [8, cell(5, 0), 6, cell(6, 2), 8, cell(5, 5), 255], 16);

fs.writeFileSync(path.join(__dirname, "battle-data.inc"),
  out.join("\n") + "\n");

function decodeIndexedPng(filename) {
  var png = fs.readFileSync(filename);
  var offset = 8;
  var width;
  var height;
  var palette = [];
  var alpha = [];
  var idat = [];
  var type;
  var length;
  var chunk;
  var raw;
  var pixels;
  var rowSize;
  var source;
  var previous;
  var row;
  var x;
  var filter;
  var value;
  var left;
  var up;
  var upperLeft;

  if (png.toString("ascii", 1, 4) !== "PNG") {
    throw new Error("Not a PNG: " + filename);
  }
  while (offset < png.length) {
    length = png.readUInt32BE(offset);
    type = png.toString("ascii", offset + 4, offset + 8);
    chunk = png.subarray(offset + 8, offset + 8 + length);
    offset += 12 + length;
    if (type === "IHDR") {
      width = chunk.readUInt32BE(0);
      height = chunk.readUInt32BE(4);
      if (chunk[8] !== 8 || chunk[9] !== 3 || chunk[12] !== 0) {
        throw new Error("Expected an 8-bit, indexed, non-interlaced PNG");
      }
    } else if (type === "PLTE") {
      for (x = 0; x < chunk.length; x += 3) {
        palette.push([chunk[x], chunk[x + 1], chunk[x + 2]]);
      }
    } else if (type === "tRNS") {
      alpha = Array.prototype.slice.call(chunk);
    } else if (type === "IDAT") {
      idat.push(chunk);
    }
  }
  raw = zlib.inflateSync(Buffer.concat(idat));
  pixels = Buffer.alloc(width * height);
  rowSize = width;
  source = 0;
  previous = Buffer.alloc(rowSize);
  for (row = 0; row < height; row += 1) {
    filter = raw[source];
    source += 1;
    for (x = 0; x < rowSize; x += 1) {
      value = raw[source];
      source += 1;
      left = x ? pixels[row * rowSize + x - 1] : 0;
      up = previous[x];
      upperLeft = x ? previous[x - 1] : 0;
      if (filter === 1) {
        value = (value + left) & 255;
      } else if (filter === 2) {
        value = (value + up) & 255;
      } else if (filter === 3) {
        value = (value + ((left + up) >> 1)) & 255;
      } else if (filter === 4) {
        var p = left + up - upperLeft;
        var pa = Math.abs(p - left);
        var pb = Math.abs(p - up);
        var pc = Math.abs(p - upperLeft);
        value = (value + (pa <= pb && pa <= pc ? left :
          (pb <= pc ? up : upperLeft))) & 255;
      } else if (filter !== 0) {
        throw new Error("Unsupported PNG filter " + filter);
      }
      pixels[row * rowSize + x] = value;
    }
    previous = Buffer.from(pixels.subarray(row * rowSize,
      (row + 1) * rowSize));
  }
  return {
    width: width,
    height: height,
    pixels: pixels,
    palette: palette,
    alpha: alpha
  };
}

function createAssets() {
  var sourceDir = path.join(__dirname, "..", "web", "assets");
  var sprites = decodeIndexedPng(path.join(sourceDir,
    "heroes-sprites-8bit.png"));
  var terrainPng = decodeIndexedPng(path.join(sourceDir, "terrain-8bit.png"));
  var rgbSlots = Object.create(null);
  var colours = [];

  function colourSlot(rgb) {
    var key = rgb.join(",");
    if (rgbSlots[key] === undefined) {
      rgbSlots[key] = 32 + colours.length;
      colours.push(rgb);
    }
    return rgbSlots[key];
  }

  function convert(image, cropWidth, cropHeight) {
    var converted = Buffer.alloc(cropWidth * cropHeight);
    var y;
    var x;
    var sourceIndex;
    var rgb;
    var slot;
    for (y = 0; y < cropHeight; y += 1) {
      for (x = 0; x < cropWidth; x += 1) {
        sourceIndex = image.pixels[y * image.width + x];
        if (sourceIndex < image.alpha.length &&
            image.alpha[sourceIndex] === 0) {
          slot = 0;
        } else {
          rgb = image.palette[sourceIndex];
          slot = colourSlot(rgb);
        }
        converted[y * cropWidth + x] = slot;
      }
    }
    return converted;
  }

  var terrain = convert(terrainPng, 32, 32);
  var spriteBytes = convert(sprites, sprites.width, sprites.height);
  var spriteSlots = Buffer.alloc(6 * 2048);
  var frame;
  var y;
  var x;
  var sourceX;
  var sourceY;
  /*
   * app.js draws each 32x64 source cell at 28x46. Precompute that same
   * nearest-neighbour result because the VBXE blitter cannot shrink images.
   * Each converted frame retains a 2 KB slot, keeping source addresses simple.
   */
  for (frame = 0; frame < 6; frame += 1) {
    for (y = 0; y < 46; y += 1) {
      sourceY = Math.floor(y * 64 / 46);
      for (x = 0; x < 28; x += 1) {
        sourceX = Math.floor(x * 32 / 28);
        spriteSlots[frame * 2048 + y * 28 + x] =
          spriteBytes[sourceY * sprites.width + frame * 32 + sourceX];
      }
    }
  }

  function shadowHex(factor) {
    var slot = Buffer.alloc(768);
    var sourceIndex;
    var rgb;
    var darkRgb;
    var inset;
    var y;
    var x;
    for (y = 0; y < 22; y += 1) {
      inset = y < 5 ? 10 - y * 2 :
        (y >= 17 ? 2 + (y - 17) * 2 : 0);
      for (x = inset; x < 26 - inset; x += 1) {
        sourceIndex = terrainPng.pixels[
          ((y + 5) & 31) * terrainPng.width + ((x + 3) & 31)
        ];
        rgb = terrainPng.palette[sourceIndex];
        darkRgb = [
          Math.round(rgb[0] * factor),
          Math.round(rgb[1] * factor),
          Math.round(rgb[2] * factor)
        ];
        slot[y * 26 + x] = colourSlot(darkRgb);
      }
    }
    return slot;
  }

  var lightShadow = shadowHex(0.84);
  var finalShadow = shadowHex(0.82);
  var binary = Buffer.concat([
    terrain, spriteSlots, lightShadow, finalShadow
  ]);
  if (binary.length !== 14848 || colours.length > 64) {
    throw new Error("Unexpected converted asset size/palette");
  }
  fs.writeFileSync(path.join(__dirname, "assets.bin"), binary);
  fs.writeFileSync(path.join(__dirname, "asset-palette.inc"),
    "; Generated from the original web PNG assets.\n" +
    colours.map(function (rgb, index) {
      return "        dta " + (32 + index) + "," + rgb.join(",");
    }).join("\n") + "\n");
}

createAssets();
