"""Names, comments and hand-written parts used by disasm.py."""

PREAMBLE = """\
; Zorro (1985, Datasoft) - disassembly
; Generated by tools/disasm.py from the original XEX; names and comments are
; in tools/symbols.py. Assembles back to the original file byte for byte:
;   mads zorro.asm -o:zorro.xex      (see build.sh)
;
; File layout (the same as the original):
;   $8000        chunk copier (INIT after each chunk below)
;   6 x $4000    data copied into the RAM under the OS ROM
;   $1480        the program, moved to $0480 by the RUN stub
;   $5BE8        sound driver, sprites and more data (runs where it loads)
;   $5000        RUN stub: move $1480-$4D7F to $0480, JMP Start
"""

# hardware, OS and RAM outside the program image
EQU = {
    # OS zero page
    0x0002: 'CASINI', 0x0009: 'BOOT', 0x004D: 'ATRACT',
    # OS page 2 / 3
    0x0200: 'VDSLST', 0x02E0: 'RUNAD', 0x02E2: 'INITAD', 0x0224: 'VVBLKD', 0x022F: 'SDMCTL', 0x0230: 'SDLSTL',
    0x0244: 'COLDST', 0x026F: 'GPRIOR', 0x02C0: 'PCOLR0', 0x02C1: 'PCOLR1',
    0x02C2: 'PCOLR2', 0x02C3: 'PCOLR3', 0x02C4: 'COLOR0', 0x02C5: 'COLOR1',
    0x02C6: 'COLOR2', 0x02C7: 'COLOR3', 0x02C8: 'COLOR4', 0x02F4: 'CHBAS',
    0x02FC: 'CH', 0x0304: 'DBUFLO', 0x0305: 'DBUFHI',
    # GTIA
    0xD000: 'HPOSP0', 0xD001: 'HPOSP1', 0xD002: 'HPOSP2', 0xD003: 'HPOSP3',
    0xD004: 'HPOSM0', 0xD005: 'HPOSM1', 0xD006: 'HPOSM2', 0xD007: 'HPOSM3',
    0xD008: 'SIZEP0', 0xD009: 'SIZEP1', 0xD00A: 'SIZEP2', 0xD00B: 'SIZEP3',
    0xD00C: 'SIZEM', 0xD010: 'TRIG0', 0xD012: 'COLPM0', 0xD013: 'COLPM1',
    0xD014: 'COLPM2', 0xD015: 'COLPM3', 0xD016: 'COLPF0', 0xD017: 'COLPF1',
    0xD018: 'COLPF2', 0xD019: 'COLPF3', 0xD01A: 'COLBK', 0xD01B: 'PRIOR',
    0xD01D: 'GRACTL', 0xD01E: 'HITCLR', 0xD01F: 'CONSOL',
    # POKEY
    0xD200: 'AUDF1', 0xD201: 'AUDC1', 0xD202: 'AUDF2', 0xD203: 'AUDC2',
    0xD204: 'AUDF3', 0xD205: 'AUDC3', 0xD206: 'AUDF4', 0xD207: 'AUDC4',
    0xD208: 'AUDCTL', 0xD20A: 'RANDOM', 0xD20F: 'SKCTL',
    # PIA
    0xD300: 'PORTA', 0xD301: 'PORTB',
    # ANTIC
    0xD400: 'DMACTL', 0xD402: 'DLISTL', 0xD403: 'DLISTH', 0xD404: 'HSCROL',
    0xD405: 'VSCROL', 0xD407: 'PMBASE', 0xD409: 'CHBASE', 0xD40A: 'WSYNC',
    0xD40B: 'VCOUNT', 0xD40E: 'NMIEN',
    # OS ROM
    0xE45C: 'SETVBV', 0xE462: 'XITVBV',
}
EQU_COMMENTS = {}
NO_PLUS1 = set()            # names that must not be used as NAME+1

# immediate operands written as an expression: {insn addr: text}
IMM_EQU = {0x123A: '<room_rects', 0x1240: '>room_rects'}
# memory operands written as an expression: {insn addr: text}
OPERAND_EQU = {0x122D: 'room_rect_map-15'}
# lda #lo / ldy #hi pairs that are not addresses: {insn addr: ()}
NOT_POINTERS = {}
# lda #lo at key, ldy #hi at value: an address the automatic search misses
FORCE_POINTERS = {0x12B8: 0x12BA}
# lda #lo / ldy #hi pairs pointing here are sprite addresses
SPRITES = (0x6420, 0x84E7)
# bytes after an always-taken branch that are data, not code
DATA_RANGES = [(0x11C0, 0x11C2), (0x1614, 0x1614)]

# code that nothing jumps to (dead code, or reached in a way the tracer
# cannot follow)
EXTRA_ENTRIES = [0x0E87, 0x16D1, 0x1735, 0x63EF, 0x63FC]

# split pointer tables: (lo table, hi table, count)
SPLIT_TABLES = [
    (0x266F, 0x26A9, 0x3A),     # object handlers
    (0x26E3, 0x271D, 0x3A),     # object sprites (changed at run time)
    (0x175C, 0x1796, 0x3A),     # Zorro animation frames
    (0x0F67, 0x0F7D, 0x16),     # sprites set by NewGame
    (0x5D7E, 0x5D92, 0x14),     # room exit lists
    (0x5E6D, 0x5E7A, 0x0D),     # soldier patrol data per room
]
# 16-bit words in data that hold addresses
WORD_POINTERS = ([0x60A2 + 2 * i for i in range(15)]     # sound effects
                 + [0x3425 + 2 * i for i in range(75)]    # room rectangles
                 + [0x5E31 + 2 * i for i in range(30)])   # soldier patrols
# big-endian pointers (song lists of the sound driver)
BE_POINTERS = [0x63D1, 0x63D4, 0x63D7]
# display lists, emitted as instructions
DISPLAY_LISTS = [(0x04B5, 0x0575)]
# PrintAt strings: column byte, text, end byte >= $80
STRINGS = [0x0F1B, 0x0F1E, 0x0F3B, 0x12E6, 0x12EE, 0x12F6, 0x1327, 0x1351,
           0x16E9]

# named arrays and variables: {address: (name, size)}. A reference inside
# one is written name+n; an indexed one just before it, name-1.
N = 0x3A                        # number of objects
ARRAYS = {
    # zero page ---------------------------------------------------------
    0x0030: ('cp_src', 2), 0x0032: ('cp_dst', 2), 0x0034: ('cp_n', 1),
    0x0035: ('prot_n', 1),
    0x0050: ('music_off', 1), 0x0051: ('stick_flip', 1),
    0x0052: ('fire', 1), 0x0053: ('cur_obj', 1), 0x0054: ('draw_buf', 1),
    0x0056: ('phys_obj', 1), 0x0057: ('phys_t', 1),
    0x005A: ('bell1_rung', 1), 0x005B: ('bell2_rung', 1),
    0x005C: ('flip_req', 1),
    0x0063: ('fire_delay', 1), 0x006E: ('credits_on', 1),
    0x0071: ('treasures', 1), 0x0072: ('won', 1),
    0x0064: ('phys_fall', 1), 0x0065: ('phys_f65', 3),
    0x0068: ('box_x1', 1), 0x0069: ('box_x2', 1), 0x006A: ('box_y1', 1),
    0x006B: ('box_y2', 1), 0x006C: ('box_h', 1), 0x006D: ('rect_count', 1),
    0x0073: ('room', 1), 0x0074: ('last_room', 1), 0x0075: ('last_key', 1),
    0x0077: ('patrol_len', 1), 0x0078: ('patrol_x', 2), 0x007A: ('patrol_y', 2),
    0x007C: ('patrol_ptr', 2), 0x007E: ('patrol_half', 1),
    0x0080: ('t0', 1), 0x0081: ('t1', 1), 0x0082: ('t2', 1), 0x0083: ('t3', 1),
    0x0084: ('t4', 1), 0x0085: ('t5', 1),
    0x0086: ('ptr0', 2), 0x0088: ('ptr1', 2), 0x008A: ('tile_base', 2),
    0x008C: ('ptr2', 2), 0x008E: ('spr_h', 1), 0x0090: ('ptr3', 2),
    0x0092: ('ptr4', 2), 0x0094: ('t6', 1), 0x0095: ('t7', 1),
    0x0096: ('save_x', 1),
    0x0099: ('stick', 1), 0x009A: ('room_colors', 4),
    0x00A0: ('in_catacombs', 1), 0x00A1: ('was_catacombs', 1),
    0x00B8: ('plat_x', 2), 0x00BA: ('plat_rx1', 2), 0x00BC: ('plat_rx2', 2),
    0x00BE: ('rect_type', 2), 0x00C0: ('rect_x1', 2), 0x00C2: ('rect_y1', 2),
    0x00C4: ('rect_x2', 2), 0x00C6: ('rect_y2', 2),
    0x00C8: ('move_in', 1),
    0x00CF: ('guards_out', 1),
    0x00D0: ('game_over', 1), 0x00D1: ('over_timer', 1),
    0x00D2: ('bonus_tick', 1), 0x00D3: ('frame_wait', 1),
    0x00D5: ('snd_list', 2), 0x00D7: ('snd_ptr', 2), 0x00D9: ('snd_chan', 8),
    0x00E1: ('sfx_ptr', 2), 0x00E3: ('snd_tick', 1), 0x00E4: ('snd_pos', 1),
    0x00E5: ('vbi_music', 1), 0x00E6: ('song_hdr', 19),
    0x00F9: ('cur_song', 1), 0x00FA: ('prot_flag', 1),
    # status line text fields (PrintAt format) --------------------------
    0x0483: ('score_txt', 1), 0x0484: ('score', 6),
    0x048B: ('hiscore_txt', 1), 0x048C: ('hiscore', 6),
    0x0493: ('bonus_txt', 1), 0x0494: ('bonus', 2),
    0x0497: ('lives_txt', 1), 0x0498: ('lives', 1),
    0x049A: ('room_state', 0x1B),
    # object table: 18 arrays of N bytes --------------------------------
    0x0574: ('obj_init', 4 * N),
    0x065C: ('obj_on', N), 0x0696: ('obj_x', N), 0x06D0: ('obj_y', N),
    0x070A: ('obj_room', N), 0x0744: ('obj_held', N),
    0x077E: ('obj_ox', N), 0x07B8: ('obj_oy', N),
    0x07F2: ('obj_h', N), 0x082C: ('obj_w', N),
    0x0866: ('obj_oh', N), 0x08A0: ('obj_ow', N),
    0x08DA: ('obj_mode', N), 0x0914: ('obj_timer', N),
    0x094E: ('obj_dx', N), 0x0988: ('obj_dy', N), 0x09C2: ('obj_redraw', N),
    0x09FC: ('obj_climb', N), 0x0A36: ('obj_var', N),
    0x17D0: ('obj_frame', N),
    0x266F: ('obj_handler_lo', N), 0x26A9: ('obj_handler_hi', N),
    0x26E3: ('obj_spr_lo', N), 0x271D: ('obj_spr_hi', N),
    0x175C: ('zorro_spr_lo', N), 0x1796: ('zorro_spr_hi', N),
    # rooms ---------------------------------------------------------------
    0x1614: ('room_pal', 0x15), 0x1629: ('palettes', 0x10),
    0x163E: ('room_tiles_lo', 0x15), 0x1653: ('room_tiles_hi', 0x15),
    0x1668: ('room_map_lo', 0x15), 0x167D: ('room_map_hi', 0x15),
    0x3505: ('room_tiles_n', 0x15), 0x351A: ('room_map_n', 0x15),
    0x1639: ('room_rect_map', 5),
    0x2E54: ('room_rect_n', 0x14), 0x3425: ('room_rects', 150),
    0x5BE8: ('room_exit_n', 0x14), 0x5D7E: ('room_exit_lo', 0x14),
    0x5D92: ('room_exit_hi', 0x14),
    0x5DA6: ('patrol_n', 0x0D), 0x5E6D: ('patrol_lo', 0x0D),
    0x5E7A: ('patrol_hi', 0x0D),
    0x5E87: ('mask_tab', 0x100),
    0x0F51: ('setup_obj', 0x16), 0x0F67: ('setup_spr_lo', 0x16),
    0x0F7D: ('setup_spr_hi', 0x16),
    0x180A: ('flip_tab', 0x10),
    # physics flags --------------------------------------------------------
    0x68A2: ('hit_type', 8), 0x68AA: ('dir_down', 1), 0x68AB: ('dir_up', 1),
    0x68AC: ('dir_right', 1), 0x68AD: ('dir_left', 1),
    0x68AE: ('in_bit4', 1), 0x68AF: ('in_bit3', 1), 0x68B0: ('in_bit2', 1),
    0x68B1: ('in_bit1', 1), 0x68B2: ('in_bit0', 1), 0x68B3: ('hit_rect', 8),
    # sound driver ----------------------------------------------------------
    0x60A2: ('sfx_table', 30),
    0x63D1: ('song_list1', 3), 0x63D4: ('song_list2', 3),
    0x63D7: ('song_list3', 3),
    0x63DA: ('chan_dur', 8), 0x63E2: ('chan_env', 1), 0x63E3: ('snd_on', 1),
    0x63E5: ('snd_speed', 4), 0x63E9: ('sfx_num', 1), 0x63EA: ('sfx_dur', 1),
    0x63EB: ('snd_save_x', 1), 0x63EC: ('snd_save_y', 1),
    0x63ED: ('music_stop', 1), 0x63EE: ('snd_paused', 1),
    # text line and screens (outside the image) ------------------------
    0xA3F8: ('TEXT_LINE', 0x78),
}

NAMES = {
    0x0480: 'Start',
    0x04B5: 'dlist', 0x04BC: 'dl_cut', 0x04BD: 'dl_cut2', 0x04BE: 'dl_lms1', 0x04BF: 'dl_lms1_hi',
    0x050B: 'dl_lms2_hi',
    0x0A70: 'ColdStart', 0x0A73: 'Reset', 0x0AE6: 'TitleScreen',
    0x0AFD: 'NewGame', 0x0C00: 'MainLoop', 0x0C90: 'NewRoom',
    0x0D07: 'SetBuffers', 0x0D5D: 'EraseAll', 0x0D87: 'RunHandlers',
    0x0DC7: 'call_handler', 0x0DCF: 'CheckKeys', 0x0E61: 'DrawAll',
    0x0E87: 'DebugExit', 0x0E95: 'Room9Check',
    0x0F0A: 'ShowStickMode', 0x0F21: 'LoseLife', 0x0F26: 'ShowLives',
    0x0F31: 'ShowGameOver', 0x0F46: 'StartOrFire', 0x0F93: 'GetKey',
    0x0FA7: 'Vbi', 0x0FD0: 'Dli', 0x0FEB: 'LoadRoom',
    0x10C0: 'lr_unpack', 0x1105: 'lr_draw', 0x1178: 'lr_done',
    0x11C0: 'plat_y_init',
    0x12B2: 'ClearText', 0x12B8: 'ShowStatus', 0x12BC: 'PrintAt',
    0x0F1B: 'txt_flip_on', 0x0F1E: 'txt_flip_off', 0x0F3B: 'txt_game_over',
    0x12E6: 'txt_paused', 0x12EE: 'txt_unpaused', 0x12F6: 'txt_status',
    0x1327: 'txt_credits', 0x1351: 'txt_blank', 0x16E9: 'txt_disk_error',
    0x137B: 'Add200', 0x137F: 'Add100', 0x1385: 'Add5', 0x13BF: 'ShowScore',
    0x13CD: 'ShowBonus', 0x13D4: 'CashBonus', 0x13FE: 'DecBonus',
    0x1416: 'FlashBonus', 0x143E: 'Delay', 0x1449: 'room_item_x',
    0x1456: 'CheckExits', 0x14A5: 'DrawObject', 0x151B: 'save_ptr',
    0x151E: 'back_ptr', 0x155C: 'ScreenBase', 0x1567: 'AddRows',
    0x1579: 'EraseObject', 0x158E: 'restore_lo', 0x1594: 'restore_hi',
    0x15D9: 'restore_ptr', 0x14C0: 'save_lo', 0x14C6: 'save_hi',
    0x1600: 'GetRandom', 0x1607: 'ObjWait',
    0x1692: 'CopyTiles', 0x16AA: 'CopyMap', 0x16C2: 'SetCopyDst',
    0x16D1: 'DiskError', 0x1703: 'WaitBlank', 0x170F: 'Protection',
    0x1736: 'prot_compare',
    0x181A: 'Obj00_Zorro', 0x1861: 'zorro_input', 0x1A43: 'zorro_fight',
    0x1A49: 'Obj04_None', 0x1A33: 'SetFrameSprite', 0x1A36: 'SetFrameSpriteY',
    0x1A3F: 'SetSpriteHi',
    0x1B4D: 'Obj01_Sword', 0x1BDC: 'Obj06_SoldierSword',
    0x1C50: 'Obj02_Bell', 0x1D15: 'ItemInHand', 0x1D99: 'ItemFrame',
    0x1DA7: 'Obj07_Key', 0x1DFE: 'PickUp', 0x1E0F: 'Carry',
    0x1E14: 'HandsFree',
    0x1E38: 'Obj17_Bottle', 0x1E81: 'Obj30_Item', 0x1EB9: 'Obj32_Handler',
    0x1F3A: 'Obj22_Treasure', 0x1FAE: 'Obj25_BigKey', 0x203C: 'Obj05_Soldier',
    0x21AF: 'SoldierBeaten', 0x2238: 'ToggleMode',
    0x2254: 'Obj40_Plant', 0x226F: 'PlaceAtZorro', 0x2288: 'Obj49_Flower',
    0x22A8: 'Obj57_Trapdoor', 0x22EA: 'TouchZorro', 0x235C: 'Obj15_Handler',
    0x23A2: 'MoveObject', 0x23A6: 'MoveSoldier', 0x23B3: 'MoveWith',
    0x25E7: 'BlockLeft', 0x25F0: 'BlockRight', 0x25FC: 'BlockSide',
    0x2606: 'StopX', 0x260E: 'Land', 0x2634: 'HitHead',
    0x2757: 'Obj16_MoneyBag', 0x276F: 'Obj08_Platform', 0x27C1: 'Obj11_Platform',
    0x281F: 'Obj18_Lift', 0x2837: 'Obj19_Chandelier', 0x2867: 'Obj20_Chain',
    0x2870: 'Obj21_Sergeant', 0x28B8: 'Obj23_Bull', 0x2911: 'Obj24_BullBody',
    0x2934: 'Obj26_Handler', 0x294F: 'Obj27_Handler', 0x2988: 'Obj31_Handler',
    0x29BD: 'SetSprite', 0x29C5: 'Obj33_Drop', 0x2A37: 'Obj36_Stone',
    0x2A77: 'Obj39_Handler', 0x2ABE: 'Obj41_SeeSaw', 0x2B22: 'Obj42_SeeSaw',
    0x2B35: 'Obj43_Ball', 0x2B84: 'Obj44_Lift', 0x2BD2: 'Obj45_RopeLadder',
    0x2BDA: 'Obj46_Pole', 0x2BE0: 'SetY', 0x2BE4: 'Obj47_Senorita',
    0x2C8A: 'Obj48_Handler', 0x2D0B: 'Obj50_Prisoner', 0x2DFC: 'Obj56_Handler',
    0x34BB: 'CopyBlocks', 0x34EA: 'Copy128',
    0x3600: 'room19_map', 0x3880: 'title_tiles', 0x3C80: 'title_map',
    0x5F87: 'SndInit', 0x5F8A: 'SndMusicOff', 0x5F8D: 'SndPause',
    0x5F90: 'SndResume', 0x5F93: 'SndUpdate', 0x5F96: 'SndPlay',
    0x5FF7: 'snd_init', 0x6011: 'snd_music_off', 0x601E: 'snd_pause',
    0x602E: 'snd_resume', 0x6034: 'snd_update', 0x6045: 'SfxUpdate',
    0x62B1: 'SongStart', 0x62C0: 'SongNext', 0x632F: 'MusicUpdate',
    0x63EF: 'SndSetup', 0x63FC: 'SndVbi',
    0x640D: 'song1', 0x6588: 'song2', 0x6703: 'song3',
    0x8470: 'screen_a',
}

PROC_DOC = {
    0x0A70: """ColdStart: set up the machine, then show the title screen.
RESET comes back to Reset through CASINI (BOOT=2).""",
    0x0AE6: """TitleScreen: room 20 is the title picture. Wait for START or fire.""",
    0x0AFD: """NewGame: clear variables and the object table, set up the objects,
lives=4, then enter room 5.""",
    0x0C28: """music: song 1 in the town, 2 in the catacombs, 3 after game over
(SndPlay only restarts a song when it changes)""",
    0x0C00: """MainLoop: one game frame. Waits for frame_wait (set to 5, counted
down by the VBI) and for the last screen flip, then: room change, erase all
objects, run each object's handler, keys, draw all objects, flip.""",
    0x0C90: """NewRoom: the room changed (CheckExits set room), fix up objects
that depend on the room.""",
    0x0E87: """DebugExit (not used): copy zero page to $8502 and jump into the
OS ROM. A leftover from development.""",
    0x0E95: """Room9Check: in room 9, count the objects standing on each side of
the see-saw (the result goes to the plank's mode).""",
    0x0F46: """StartOrFire: A=0 (Z set) if START or the fire button is pressed.""",
    0x0F93: """GetKey: A=key code and clear CH, or A=$FF if no key.""",
    0x0FA7: """Vbi: deferred VBI. Flips the screen buffers when the main loop asks
(flip_req), counts down frame_wait and runs the sound driver.""",
    0x0FD0: """Dli: below the status line, set the four room colours.""",
    0x0FEB: """LoadRoom: draw the room in both screen buffers.
Copies the room's tile set to $9FF0 and its packed map to $5480 (from the RAM
under the OS ROM), unpacks the map to $57E8 and draws 8x8 tiles. While it
works, the display list is cut after the status line. Then plays sound
effect 6 and sets the platform tables, collision rectangles and the
soldier's patrol for the room.""",
    0x12BC: """PrintAt(A/Y=text): write text to the status line at $A3F8.
The first byte is the column (+$A3F7); then characters until a byte >= $80.
Codes below $20 are EORed with $10, so digits can be stored as 0-9.""",
    0x137B: """Add200 / Add100 / Add5: add to the score (6 BCD-like digits),
update the high score and print both.""",
    0x13D4: """CashBonus: count the bonus down into the score, with the bonus
field flashing.""",
    0x1456: """CheckExits: if Zorro stands on one of the room's exits (5 bytes:
x, y, new x, new y, new room), move him to the new room.""",
    0x14A5: """DrawObject(X): draw object X's sprite into the back buffer with a
mask, saving the background first. Clipped to y=$18..$C7, x<40 bytes.""",
    0x155C: """ScreenBase: ptr0 = back buffer address of line 0 ($80B0 or $A0B0).""",
    0x1579: """EraseObject(X): put back the background saved by DrawObject.""",
    0x1607: """ObjWait: if obj_timer,x is not 0, count it down and return from
the calling handler (it pulls the return address).""",
    0x16D1: """DiskError (not used any more): the copy protection's failure path.""",
    0x170F: """Protection: in room 5 with prot_flag set, copy 2 KB from $F780 to
$B000 and compare two halves. The jump to DiskError was replaced by NOPs.""",
    0x181A: """Obj00_Zorro: read the joystick, walk/climb/jump through MoveWith,
fight when a soldier is close, fall into the river, pick animation frames.""",
    0x1A49: """Obj04_None: the bell tower ladder; does nothing.""",
    0x1B4D: """Obj01_Sword: Zorro's sword, placed from his animation frame.""",
    0x1BDC: """Obj06_SoldierSword: the soldier's sword, placed from his frame.""",
    0x1C50: """Obj02_Bell (objects 2 and 3): a bell that can be carried and hung
in the tower in room 0. When both are hung, the tower ladder
(object 4) appears.""",
    0x1D15: """ItemInHand: common code for a carried item: drop it with fire,
or give it to the right object.""",
    0x1DFE: """PickUp: Zorro takes the item; the item he held is put down.""",
    0x203C: """Obj05_Soldier: walks the room's patrol path, fights Zorro.""",
    0x22A8: """Obj57_Trapdoor: in the jail, sends Zorro to a random catacomb
room (13-19) and costs a life.""",
    0x22EA: """TouchZorro(X): A=$FF (Z clear) if object X overlaps Zorro.""",
    0x23B3: """MoveWith(move_in): move object X by obj_dx/obj_dy and check it
against the room's rectangles (rect_* tables, rect_count entries). Sets the
hit flags hit_type.. and adjusts the position: walls, floors, ladders, fall.""",
    0x29BD: """SetSprite(A/Y): object X shows the sprite at A/Y.""",
    0x2BE4: """Obj47_Senorita: the lady on the balcony in room 5. When Zorro
reaches her with the flower (object 49), the game ends: each remaining
life is counted into the bonus, then game_over is set.""",
    0x2D0B: """Obj50_Prisoner (objects 50-55): prisoners in the jail.""",
    0x34BB: """CopyBlocks: copy t0 blocks of 128 bytes from cp_src to cp_dst
with the OS ROM switched off (the data lives under the ROM).""",
    0x5F87: """Sound driver jump table.
SndPlay(A): A=1..4 starts a song (1, 2, other = song lists 1, 2, 3);
A>=5 plays sound effect A-4 on channel 4. X and Y are kept.""",
    0x63EF: """SndSetup (not used): install SndVbi as the deferred VBI. The game
has its own VBI that calls SndUpdate instead.""",
}

COMMENTS = {
    0x0A73: 'BASIC off',
    0x0B21: 'reset the stack',
    0x0C00: 'wait for the frame timer and the flip',
    0x0C5B: 'read the joystick: stick = directions + $10 if fire up',
    0x0DC7: 'operand = obj_handler of object X',
    0x0DCF: 'START: new game',
    0x0DF0: 'SPACE: pause',
    0x0E1B: 'L key: flipped joystick',
    0x0E29: 'V key: show credits',
    0x0E44: 'R key: normal joystick',
    0x0E52: 'S key: music on/off',
    0x1065: 'six NOPs: removed code',
    0x14C0: 'operand = save buffer (set by SetBuffers)',
    0x151B: 'operand = save buffer (set by SetBuffers)',
    0x1759: 'NOPs: the jump to DiskError was removed',
}

HEADER = {
    0x0483: """status line fields, in PrintAt format""",
    0x04B5: """display list. The status line is a text line at $A3F8; the room
is a 176-line mode E bitmap, 40 bytes per line, with a second LMS only
because ANTIC cannot cross a 4 KB boundary. The VBI flips the LMS
high bytes between $84/$90 and $A4/$B0. LoadRoom cuts the list after the
status line (dl_cut) while it draws.""",
    0x0574: """initial obj_on, obj_x, obj_y, obj_room (copied by NewGame)""",
    0x065C: """object table: 58 objects, one array per field.
obj_room: room number, $FF = every room, $80 = every catacomb room.
Object 0 is Zorro, 1 his sword, 5 the soldier, 6 the soldier's sword.""",
    0x1614: """room tables (21 rooms: 0-19 the game, 20 the title)""",
    0x266F: """object handlers, called by RunHandlers""",
    0x26E3: """current sprite of each object""",
    0x3505: """room tile/map sizes in 128-byte blocks, then room data that is
not under the ROM""",
    0x5BE8: """room exits: count, then pointers to 5-byte entries""",
    0x2E54: """collision rectangles: count per room, then for each room five
tables (type, x1, y1, x2, y2) that LoadRoom points rect_type..rect_y2 at.
Some objects move their rectangles (platforms, see-saw, stones).""",
    0x5DA6: """soldier patrols: path length per room (0-12), and a pointer to
three pointers: x positions, y positions, order""",
    0x5E87: """mask_tab: for a sprite byte, the mask that clears the screen bits
under its non-zero pixels""",
    0x60A2: """sound effects: 3-byte steps (duration, AUDF4, AUDC4), 0,0 ends""",
    0x63D1: """song lists: big-endian song addresses, 0 = start again""",
    0x6420: """songs, physics flags at $68A2, then sprites (width in bytes,
height, mode E pixels)""",
    0x8470: """screen_a: the first screen buffer starts here ($8470-$9FEF, 176 lines
of 40 bytes); these last bytes of the file are overwritten by LoadRoom""",
}

def handler_table(ram):
    """The object handlers the main loop calls through a patched JSR."""
    return [ram[0x266F + i] | ram[0x26A9 + i] << 8 for i in range(0x3A)]


LOADER = """\
; ======================================================================
; $8000  chunk copier. The file loads each 2.5 KB chunk at $4000 and then
; runs CopyChunk as INIT: with the OS ROM switched off it copies the chunk
; to the RAM under the ROM. $90 counts the chunks (0 at power-on).
; This segment is overwritten later by the $5BE8-$84E7 segment.
; ======================================================================
\topt h-\t\t\t; segment headers are written out below,
\t\t\t\t; to keep the original $FFFF before each one
\tdta a($FFFF),a(cc_dst),a(cc_end_of_code-1)
\torg $8000
cc_dst\tdta $D8,$E2,$EC,$F6,$C0,$C9\t; destination page of each chunk
cc_end\tdta $4A,$54,$5E,$68,$49,$4F\t; source page where it ends
cc_src\tdta $40,$4A,$54,$5E,$40,$49\t; source page
CopyChunk
\tldx $90
\tlda cc_dst,x
\tsta $83
\tlda cc_end,x
\tsta cc_cmp+1
\tlda cc_src,x
\tsta $81
\tlda #$00
\tsta $80
\tsta $82
\tsei
\tlda #$00
\tsta DMACTL
\tsta NMIEN
\tlda #$FE\t\t\t; OS ROM off
\tsta PORTB
\tldy #$00
cc_loop\tlda ($80),y
\tsta ($82),y
\tinc $80
\tbne cc_1
\tinc $81
cc_1\tinc $82
\tbne cc_2
\tinc $83
cc_2\tlda $81
cc_cmp\tcmp #$00\t\t\t; patched: end page
\tbne cc_loop
\tinc $90
\tlda #$FF\t\t\t; OS ROM back on
\tsta PORTB
\tlda #$40
\tsta NMIEN
\tlda #$22
\tsta DMACTL
\tcli
\trts
cc_end_of_code
"""

MAIN_BANNER = """\
; ======================================================================
; $0480-$3D7F  the program. Loaded at $1480; the RUN stub moves it here.
; ======================================================================"""

UPPER_BANNER = """\
; ======================================================================
; $5BE8-$84E7  data, sound driver, sprite and title graphics
; ======================================================================"""

RUN_STUB = """\
; ======================================================================
; $5000  RUN: move $1480-$4D7F down to $0480-$3D7F and start
; ======================================================================
\tdta a($FFFF),a(RunStub),a(rs_end-1)
\torg $5000
RunStub\tlda #$80
\tsta $80
\tlda #$14
\tsta $81
\tlda #$80
\tsta $82
\tlda #$04
\tsta $83
\tldy #$00
bt_loop\tlda ($80),y
\tsta ($82),y
\tinc $80
\tbne bt_1
\tinc $81
bt_1\tinc $82
\tbne bt_2
\tinc $83
bt_2\tlda $80
\tcmp #$80
\tbne bt_loop
\tlda $81
\tcmp #$4D
\tbne bt_loop
\tjmp Start
rs_end
\tdta a(RUNAD),a(RUNAD+1),a(RunStub)
"""
