; auto-generated by tools/extract.js -- PICO-8 16-colour palette
pico_palette
	.he 00,00,00	; 0
	.he 1d,2b,53	; 1
	.he 7e,25,53	; 2
	.he 00,87,51	; 3
	.he ab,52,36	; 4
	.he 5f,57,4f	; 5
	.he c2,c3,c7	; 6
	.he ff,f1,e8	; 7
	.he ff,00,4d	; 8
	.he ff,a3,00	; 9
	.he ff,ec,27	; 10
	.he 00,e4,36	; 11
	.he 29,ad,ff	; 12
	.he 83,76,9c	; 13
	.he ff,77,a8	; 14
	.he ff,cc,aa	; 15
