#!/usr/bin/env python3
"""Convert title and background artwork to 320x200 VBXE framebuffers.

Requires Pillow. Each image uses 32 colours; indices 0..15 are reserved for
the game. Four XEX INIT segments upload each image without persistent CPU RAM.
"""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]


def convert(source_name, name, first_index):
    source = Image.open(ROOT / "assets" / source_name).convert("RGB")
    screen = source.resize((320, 200), Image.Resampling.LANCZOS)
    indexed = screen.quantize(colors=32, method=Image.Quantize.MEDIANCUT,
                              dither=Image.Dither.NONE)
    indexed.save(ROOT / f"assets/porter-{name}-preview.png")
    palette = indexed.getpalette()[:96]
    assert len(palette) == 96
    data = bytes(index + first_index for index in indexed.tobytes())
    assert len(data) == 64000 and min(data) >= first_index and max(data) < first_index + 32
    data += bytes(65536 - len(data))
    out = ROOT / "data"
    out.mkdir(exist_ok=True)
    for bank in range(4):
        (out / f"{name}-{bank}.dat").write_bytes(data[bank * 16384:(bank + 1) * 16384])
    lines = [f"; Generated by tools/make_title.py; palette {first_index}..{first_index + 31}",
             f"{name}_palette"]
    for offset in range(0, 96, 3):
        lines.append("        dta " + ",".join(str(v) for v in palette[offset:offset + 3]))
    (out / f"{name}-palette.inc.asm").write_text("\n".join(lines) + "\n")
    print(f"{name}: 320x200, 32 colours, four 16K VBXE upload segments")


def main():
    convert("porter-title-credits.png", "title", 16)
    convert("porter-background-source.png", "background", 48)


if __name__ == "__main__":
    main()
