// Porter Patch -> Atari VBXE data extractor.
// Usage: node tools/extract.js
// Reads ../js/porterpatch-data.js and ../js/porterpatch1-1.png, writes data/*.

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.resolve(__dirname, '..', '..', 'js');
const OUT = path.join(ROOT, 'data');
fs.mkdirSync(OUT, { recursive: true });

// PICO-8 default palette (RGB) -- used to map PNG pixels back to indices.
const PICO_PAL = [
  [0x00,0x00,0x00],[0x1d,0x2b,0x53],[0x7e,0x25,0x53],[0x00,0x87,0x51],
  [0xab,0x52,0x36],[0x5f,0x57,0x4f],[0xc2,0xc3,0xc7],[0xff,0xf1,0xe8],
  [0xff,0x00,0x4d],[0xff,0xa3,0x00],[0xff,0xec,0x27],[0x00,0xe4,0x36],
  [0x29,0xad,0xff],[0x83,0x76,0x9c],[0xff,0x77,0xa8],[0xff,0xcc,0xaa],
];

// --- load porterpatch-data.js by shim ---
const dataJs = fs.readFileSync(path.join(SRC, 'porterpatch-data.js'), 'utf8');
const shim = { window: {} };
new Function('window', dataJs).call(shim, shim.window);
const { MAP_HEX_TOP, MAP_HEX_SHARED, FLAG_HEX } = shim.window.PORTERPATCH_DATA;

// LEVELS array (copied verbatim from porterpatch.js)
const LEVELS = [
  [4,8,13,7,19,9],[19,9,27,10,35,10],[35,10,44,6,51,3],[51,3,53,11,72,13],
  [72,13,74,3,83,6],[83,6,93,3,99,11],[99,11,98,2,115,10],[115,10,124,1,5,19],
  [5,19,14,22,19,26],[19,26,30,25,36,21],[36,21,38,28,49,28],[49,28,62,19,66,25],
  [66,25,66,30,82,24],[82,24,82,29,99,19],[99,19,109,18,114,26],[114,26,125,24,3,43],
  [3,43,3,33,18,45],[18,45,19,34,33,43],[33,43,33,33,50,44],[50,44,54,33,67,43],
  [67,43,67,35,81,35],[81,35,81,42,99,44],[99,44,98,38,115,44],[115,44,114,33,5,54],
  [5,54,5,58,18,56],[18,56,29,53,35,56],[35,56,35,61,51,52],[51,52,50,55,83,61],
  [83,61,-1,-1,-1,-1],
];

// --- build FULL_MAP (same as JS) ---
function parseByteRows(rows) {
  return rows.map((row) => {
    const out = [];
    for (let i = 0; i < row.length; i += 2) out.push(parseInt(row.slice(i, i + 2), 16));
    return out;
  });
}
const topRows = parseByteRows(MAP_HEX_TOP);
const sharedRows = [];
for (let r = 0; r < MAP_HEX_SHARED.length; r += 2) {
  const out = [];
  for (const line of [MAP_HEX_SHARED[r], MAP_HEX_SHARED[r + 1]]) {
    for (let i = 0; i < line.length; i += 2) out.push(parseInt(line[i + 1] + line[i], 16));
  }
  sharedRows.push(out);
}
const FULL_MAP = [...topRows, ...sharedRows];
// PICO-8 source data only covers 62 of the 64 logical map rows; pad with zeros.
while (FULL_MAP.length < 64) FULL_MAP.push(new Array(128).fill(0));

// --- emit levels.dat (29 * 256 bytes) and level_meta.dat ---
const ROOM = 16;
const levels = Buffer.alloc(29 * ROOM * ROOM);
const meta = Buffer.alloc(29 * 8);
for (let i = 0; i < 29; i++) {
  const [sx, sy, cx, cy, nx, ny] = LEVELS[i];
  const ox = Math.floor(sx / ROOM) * ROOM;
  const oy = Math.floor(sy / ROOM) * ROOM;
  for (let y = 0; y < ROOM; y++) {
    for (let x = 0; x < ROOM; x++) {
      levels[i * 256 + y * ROOM + x] = FULL_MAP[oy + y][ox + x];
    }
  }
  // player start local pixel offset matches JS levelStartPx()
  const yAdj = i === 0 ? -12 : -8;
  const xAdj = i === 0 ? -4 : 0;
  meta[i * 8 + 0] = ((sx - ox) * 8 + xAdj) & 0xff; // start_x lo (signed-ok)
  meta[i * 8 + 1] = ((sy - oy) * 8 + yAdj) & 0xff; // start_y
  meta[i * 8 + 2] = cx < 0 ? 0xff : (cx - ox) * 8;
  meta[i * 8 + 3] = cy < 0 ? 0xff : (cy - oy) * 8;
  meta[i * 8 + 4] = ox;
  meta[i * 8 + 5] = oy;
  meta[i * 8 + 6] = (i === 28) ? 1 : 0;        // end-of-game flag
  meta[i * 8 + 7] = (i === 28) ? 0xff : i + 1; // next level
}
fs.writeFileSync(path.join(OUT, 'levels.dat'), levels);
fs.writeFileSync(path.join(OUT, 'level_meta.dat'), meta);
console.log('wrote levels.dat', levels.length, 'level_meta.dat', meta.length);

// --- emit tile_flags.dat (256 bytes) ---
const flags = Buffer.alloc(256, 0);
for (let i = 0; i * 2 < FLAG_HEX.length; i++) flags[i] = parseInt(FLAG_HEX.slice(i * 2, i * 2 + 2), 16);
fs.writeFileSync(path.join(OUT, 'tile_flags.dat'), flags);
console.log('wrote tile_flags.dat', flags.length);

// --- emit palette.inc.asm (PICO-8 palette -> gacek tab_color triples) ---
let pal = '; auto-generated by tools/extract.js -- PICO-8 16-colour palette\n';
pal += 'pico_palette\n';
for (let i = 0; i < 16; i++) {
  const [r, g, b] = PICO_PAL[i];
  pal += `\t.he ${r.toString(16).padStart(2,'0')},${g.toString(16).padStart(2,'0')},${b.toString(16).padStart(2,'0')}\t; ${i}\n`;
}
fs.writeFileSync(path.join(OUT, 'palette.inc.asm'), pal);
console.log('wrote palette.inc.asm');

// --- decode PNG via ImageMagick, map pixels -> PICO-8 indices, emit shapes.spr ---
const tmpRgb = path.join(OUT, '_sheet.rgb');
execFileSync('convert', [path.join(SRC, 'porterpatch1-1.png'), '-depth', '8', `RGB:${tmpRgb}`]);
const rgb = fs.readFileSync(tmpRgb);
fs.unlinkSync(tmpRgb);
if (rgb.length !== 128 * 128 * 3) throw new Error(`unexpected sheet size ${rgb.length}`);

function nearestPalIndex(r, g, b) {
  let best = 0, bestD = Infinity;
  for (let i = 0; i < 16; i++) {
    const dr = r - PICO_PAL[i][0], dg = g - PICO_PAL[i][1], db = b - PICO_PAL[i][2];
    const d = dr * dr + dg * dg + db * db;
    if (d < bestD) { bestD = d; best = i; }
  }
  return best;
}

// shapes.spr: 256 sprites of 8x8 indices, packed contiguous (64 bytes each).
const shapes = Buffer.alloc(256 * 64);
for (let sid = 0; sid < 256; sid++) {
  const sx = (sid % 16) * 8;
  const sy = Math.floor(sid / 16) * 8;
  for (let y = 0; y < 8; y++) {
    for (let x = 0; x < 8; x++) {
      const off = ((sy + y) * 128 + (sx + x)) * 3;
      shapes[sid * 64 + y * 8 + x] = nearestPalIndex(rgb[off], rgb[off + 1], rgb[off + 2]);
    }
  }
}
fs.writeFileSync(path.join(OUT, 'shapes.spr'), shapes);
console.log('wrote shapes.spr', shapes.length);

// shapes_flip.spr: horizontally mirrored copies (used for player facing-left).
const flip = Buffer.alloc(256 * 64);
for (let sid = 0; sid < 256; sid++) {
  for (let y = 0; y < 8; y++) {
    for (let x = 0; x < 8; x++) {
      flip[sid * 64 + y * 8 + x] = shapes[sid * 64 + y * 8 + (7 - x)];
    }
  }
}
fs.writeFileSync(path.join(OUT, 'shapes_flip.spr'), flip);
console.log('wrote shapes_flip.spr', flip.length);

// Quick stats: which tile ids are referenced in any level (so init can skip empties).
const used = new Set();
for (const b of levels) used.add(b);
console.log('unique tiles referenced in levels:', [...used].sort((a, b) => a - b).join(','));
